// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse
{
    /// <summary>
    /// You can use the *clickhouse_clickpipe_cdc_infrastructure* resource to manage scaling settings for CDC ClickPipes infrastructure shared across all DB ClickPipes in a service.
    /// 
    /// &gt; **Important:** Only one CDC infrastructure resource per service is supported. Creating multiple instances for the same service will cause conflicts.
    /// 
    /// This endpoint becomes available once at least one DB ClickPipe has been provisioned. The resource will poll for up to 10 minutes waiting for the endpoint to become available.
    /// 
    /// For billing purposes, 2 CPU cores and 8 GB of RAM correspond to one compute unit.
    /// 
    /// &gt; **Note:** CDC infrastructure is shared across all DB ClickPipes and cannot be explicitly deleted. Removing this resource only removes it from Terraform state. The infrastructure is automatically cleaned up when all DB ClickPipes are deleted.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Clickhouse = Pulumiverse.Clickhouse;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Clickhouse.ClickpipeCdcInfrastructure("example", new()
    ///     {
    ///         ServiceId = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    ///         ReplicaCpuMillicores = 2000,
    ///         ReplicaMemoryGb = 8,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// The `pulumi import` command can be used, for example:
    /// 
    /// !/bin/bash
    /// CDC infrastructure can be imported by specifying the service ID.
    /// 
    /// ```sh
    /// $ pulumi import clickhouse:index/clickpipeCdcInfrastructure:ClickpipeCdcInfrastructure example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    /// ```
    /// </summary>
    [ClickhouseResourceType("clickhouse:index/clickpipeCdcInfrastructure:ClickpipeCdcInfrastructure")]
    public partial class ClickpipeCdcInfrastructure : global::Pulumi.CustomResource
    {
        /// <summary>
        /// CPU in millicores for DB ClickPipes. Must be a multiple of 1000, between 1000 and 24000.
        /// </summary>
        [Output("replicaCpuMillicores")]
        public Output<int> ReplicaCpuMillicores { get; private set; } = null!;

        /// <summary>
        /// Memory in GiB for DB ClickPipes. Must be a multiple of 4, between 4 and 96. Must be 4× the CPU core count.
        /// </summary>
        [Output("replicaMemoryGb")]
        public Output<double> ReplicaMemoryGb { get; private set; } = null!;

        /// <summary>
        /// ClickHouse Cloud service ID where the CDC infrastructure is located.
        /// </summary>
        [Output("serviceId")]
        public Output<string> ServiceId { get; private set; } = null!;


        /// <summary>
        /// Create a ClickpipeCdcInfrastructure resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ClickpipeCdcInfrastructure(string name, ClickpipeCdcInfrastructureArgs args, CustomResourceOptions? options = null)
            : base("clickhouse:index/clickpipeCdcInfrastructure:ClickpipeCdcInfrastructure", name, args ?? new ClickpipeCdcInfrastructureArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ClickpipeCdcInfrastructure(string name, Input<string> id, ClickpipeCdcInfrastructureState? state = null, CustomResourceOptions? options = null)
            : base("clickhouse:index/clickpipeCdcInfrastructure:ClickpipeCdcInfrastructure", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse/pulumi-clickhouse",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ClickpipeCdcInfrastructure resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ClickpipeCdcInfrastructure Get(string name, Input<string> id, ClickpipeCdcInfrastructureState? state = null, CustomResourceOptions? options = null)
        {
            return new ClickpipeCdcInfrastructure(name, id, state, options);
        }
    }

    public sealed class ClickpipeCdcInfrastructureArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// CPU in millicores for DB ClickPipes. Must be a multiple of 1000, between 1000 and 24000.
        /// </summary>
        [Input("replicaCpuMillicores", required: true)]
        public Input<int> ReplicaCpuMillicores { get; set; } = null!;

        /// <summary>
        /// Memory in GiB for DB ClickPipes. Must be a multiple of 4, between 4 and 96. Must be 4× the CPU core count.
        /// </summary>
        [Input("replicaMemoryGb", required: true)]
        public Input<double> ReplicaMemoryGb { get; set; } = null!;

        /// <summary>
        /// ClickHouse Cloud service ID where the CDC infrastructure is located.
        /// </summary>
        [Input("serviceId", required: true)]
        public Input<string> ServiceId { get; set; } = null!;

        public ClickpipeCdcInfrastructureArgs()
        {
        }
        public static new ClickpipeCdcInfrastructureArgs Empty => new ClickpipeCdcInfrastructureArgs();
    }

    public sealed class ClickpipeCdcInfrastructureState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// CPU in millicores for DB ClickPipes. Must be a multiple of 1000, between 1000 and 24000.
        /// </summary>
        [Input("replicaCpuMillicores")]
        public Input<int>? ReplicaCpuMillicores { get; set; }

        /// <summary>
        /// Memory in GiB for DB ClickPipes. Must be a multiple of 4, between 4 and 96. Must be 4× the CPU core count.
        /// </summary>
        [Input("replicaMemoryGb")]
        public Input<double>? ReplicaMemoryGb { get; set; }

        /// <summary>
        /// ClickHouse Cloud service ID where the CDC infrastructure is located.
        /// </summary>
        [Input("serviceId")]
        public Input<string>? ServiceId { get; set; }

        public ClickpipeCdcInfrastructureState()
        {
        }
        public static new ClickpipeCdcInfrastructureState Empty => new ClickpipeCdcInfrastructureState();
    }
}
