// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse
{
    public static class GetPostgresServices
    {
        /// <summary>
        /// &gt; **Note:** This data source is in alpha and its behavior may change in future provider versions.
        /// 
        /// Lists all [ClickHouse Cloud Managed Postgres](https://clickhouse.com/cloud/postgres)
        /// services in the organization. Returns a `Services` list of summary objects
        /// (`Id`, `Name`, `CloudProvider`, `Region`, `PostgresVersion`, `Size`,
        /// `HaType`, `State`, `CreatedAt`, `IsPrimary`).
        /// 
        /// The list endpoint does not return `ConnectionString`, `Password`, or
        /// `PgConfig`; use the `clickhouse.PostgresService` data source (by ID) for the
        /// full set of attributes.
        /// 
        /// ## Example
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Clickhouse = Pulumiverse.Clickhouse;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = Clickhouse.GetPostgresServices.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["serviceNames"] = .Select(s =&gt; 
        ///         {
        ///             return s.Name;
        ///         }).ToList(),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetPostgresServicesResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPostgresServicesResult>("clickhouse:index/getPostgresServices:getPostgresServices", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// &gt; **Note:** This data source is in alpha and its behavior may change in future provider versions.
        /// 
        /// Lists all [ClickHouse Cloud Managed Postgres](https://clickhouse.com/cloud/postgres)
        /// services in the organization. Returns a `Services` list of summary objects
        /// (`Id`, `Name`, `CloudProvider`, `Region`, `PostgresVersion`, `Size`,
        /// `HaType`, `State`, `CreatedAt`, `IsPrimary`).
        /// 
        /// The list endpoint does not return `ConnectionString`, `Password`, or
        /// `PgConfig`; use the `clickhouse.PostgresService` data source (by ID) for the
        /// full set of attributes.
        /// 
        /// ## Example
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Clickhouse = Pulumiverse.Clickhouse;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = Clickhouse.GetPostgresServices.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["serviceNames"] = .Select(s =&gt; 
        ///         {
        ///             return s.Name;
        ///         }).ToList(),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetPostgresServicesResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPostgresServicesResult>("clickhouse:index/getPostgresServices:getPostgresServices", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// &gt; **Note:** This data source is in alpha and its behavior may change in future provider versions.
        /// 
        /// Lists all [ClickHouse Cloud Managed Postgres](https://clickhouse.com/cloud/postgres)
        /// services in the organization. Returns a `Services` list of summary objects
        /// (`Id`, `Name`, `CloudProvider`, `Region`, `PostgresVersion`, `Size`,
        /// `HaType`, `State`, `CreatedAt`, `IsPrimary`).
        /// 
        /// The list endpoint does not return `ConnectionString`, `Password`, or
        /// `PgConfig`; use the `clickhouse.PostgresService` data source (by ID) for the
        /// full set of attributes.
        /// 
        /// ## Example
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Clickhouse = Pulumiverse.Clickhouse;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = Clickhouse.GetPostgresServices.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["serviceNames"] = .Select(s =&gt; 
        ///         {
        ///             return s.Name;
        ///         }).ToList(),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetPostgresServicesResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPostgresServicesResult>("clickhouse:index/getPostgresServices:getPostgresServices", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetPostgresServicesResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// All Managed Postgres services in the organization (summary fields).
        /// </summary>
        public readonly ImmutableArray<Outputs.GetPostgresServicesServiceResult> Services;

        [OutputConstructor]
        private GetPostgresServicesResult(
            string id,

            ImmutableArray<Outputs.GetPostgresServicesServiceResult> services)
        {
            Id = id;
            Services = services;
        }
    }
}
