// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse
{
    /// <summary>
    /// &gt; **Note:** This resource is in alpha and its behavior may change in future provider versions.
    /// 
    /// Manages a [ClickHouse Cloud Managed Postgres](https://clickhouse.com/cloud/postgres)
    /// service. A Managed Postgres service is a fully-managed Postgres instance
    /// provisioned in the ClickHouse Cloud control plane.
    /// 
    /// ## Supported lifecycle
    /// 
    /// - Create — standard, as a read replica (`ReadReplicaOf`), or by
    ///   point-in-time restore (`RestoreToPointInTime`)
    /// - Read
    /// - Update — `Size`, `HaType`, `Tags`, `PgConfig`, `PgbouncerConfig`,
    ///   `Password` rotation
    /// - Delete
    /// - Import
    /// 
    /// Three companion data sources are also provided (alpha):
    /// `clickhouse.PostgresService`, `clickhouse.getPostgresServices`, and
    /// `clickhouse.getPostgresServiceCaCertificates`.
    /// 
    /// ## Unsupported attributes
    /// 
    /// The following are intentionally absent from the schema:
    /// 
    /// - Operational commands (restart / promote / switchover). See
    ///   "Operational commands" below for the rationale.
    /// - IP allowlist, private endpoints, backup configuration, maintenance
    ///   windows, customer-managed encryption keys, BYOC. These depend on
    ///   server-side endpoint additions.
    /// - Configurable lifecycle timeouts — there is no `timeouts {}` block; the
    ///   provider uses fixed internal poll/retry budgets.
    /// 
    /// ## Tag semantics
    /// 
    /// Tags are a `map(string → string)` — same shape as `clickhouse.Service`.
    /// Values must be non-empty alphanumeric / `.` / `-` / `_` strings (server
    /// regex `^[a-zA-Z0-9._-]+$`); the server's PATCH endpoint returns `400
    /// BAD_REQUEST` on omitted values, so the schema rejects empty values at
    /// plan time.
    /// 
    /// Setting `tags = {}` clears all user-controlled tags. Omitting the
    /// attribute entirely preserves the prior state value (`Optional +
    /// Computed + UseStateForUnknown`).
    /// 
    /// The Postgres PATCH endpoint has PUT-like semantics specifically for the
    /// `Tags` field: omitting it from the request body clears all tags
    /// server-side. The provider works around this by re-asserting the current
    /// state tags in every PATCH that mutates `Size` or `HaType`, so users
    /// won't lose tags when they resize or change HA mode. This is invisible
    /// end-to-end but worth knowing if you inspect `TF_LOG=DEBUG` request
    /// bodies — you'll see tags repeated on non-tag mutations.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Clickhouse = Pulumiverse.Clickhouse;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Clickhouse.PostgresService("example", new()
    ///     {
    ///         Name = "my-postgres",
    ///         CloudProvider = "aws",
    ///         Region = "us-east-1",
    ///         Size = "m6gd.large",
    ///         HaType = "async",
    ///         Tags = 
    ///         {
    ///             { "environment", "production" },
    ///             { "team", "data" },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// The `pulumi import` command can be used, for example:
    /// 
    /// !/bin/bash
    /// Managed Postgres services can be imported by specifying the service ID.
    /// The password is recovered on import (the server echoes it on GET) and stored
    /// in state.
    /// 
    /// ```sh
    /// $ pulumi import clickhouse:index/postgresService:PostgresService example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    /// ```
    /// </summary>
    [ClickhouseResourceType("clickhouse:index/postgresService:PostgresService")]
    public partial class PostgresService : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Cloud provider hosting the instance. Currently only 'aws' is supported. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
        /// </summary>
        [Output("cloudProvider")]
        public Output<string> CloudProvider { get; private set; } = null!;

        /// <summary>
        /// Full connection URI embedding the username and the password. Marked sensitive; the secret-redaction layer also covers it in TF_LOG=DEBUG output. Plan stability is managed in ModifyPlan: pinned to the prior value on unrelated updates, marked unknown when a password rotation is planned (it embeds the password).
        /// </summary>
        [Output("connectionString")]
        public Output<string> ConnectionString { get; private set; } = null!;

        /// <summary>
        /// RFC3339 timestamp when the service was created.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// High-availability mode. One of 'none' (single replica), 'async' (asynchronous replica), or 'sync' (synchronous replica). Mutable post-create; an HA flip triggers a transition. Omitting the attribute preserves the prior value (the server defaults to 'none' on Create); to actively downgrade, set 'ha_type = "none"' explicitly. Omit for a read replica or point-in-time restore (inherited from the source).
        /// </summary>
        [Output("haType")]
        public Output<string> HaType { get; private set; } = null!;

        /// <summary>
        /// Network hostname for client connections.
        /// </summary>
        [Output("hostname")]
        public Output<string> Hostname { get; private set; } = null!;

        /// <summary>
        /// True when this instance is a writeable primary cluster; false only for separately-provisioned read replicas. HA standby servers (`HaType = async`/`Sync`) live inside the same primary instance and don't affect this value.
        /// </summary>
        [Output("isPrimary")]
        public Output<bool> IsPrimary { get; private set; } = null!;

        /// <summary>
        /// Human-readable name. Immutable post-create; changes force destroy-and-recreate. Differs from clickhouse_service, which allows in-place rename.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Superuser password. Optional: set it to manage the password in Terraform, or omit it and the server generates one. Computed and refreshed from each GET (the server echoes it), so it always reflects the live password and an out-of-band rotation is reconciled on the next refresh. Changing this value rotates the password (PATCH /password). Must be ≥12 chars with at least one lowercase, one uppercase, and one digit. Stored in (sensitive) state.
        /// </summary>
        [Output("password")]
        public Output<string> Password { get; private set; } = null!;

        /// <summary>
        /// Postgres server parameters (pgConfig) as a key-value map. Declared parameters are the desired state — every apply sends the full map via POST /config (full replacement), so removing a key from the map removes it server-side. Set `PgConfig = {}` to clear all parameters; omit the attribute to preserve the prior state (read replicas inherit the primary's parameters, and the server may surface values the configuration never declared — so it is Optional+Computed like tags). Out-of-band changes are reverted on the next apply. Some parameters require a database restart; the provider surfaces the server's restart-required hint as a warning (restart out-of-band).
        /// </summary>
        [Output("pgConfig")]
        public Output<ImmutableDictionary<string, string>> PgConfig { get; private set; } = null!;

        /// <summary>
        /// PgBouncer connection-pooler parameters (pgBouncerConfig) as a key-value map. Same Optional+Computed semantics as pg_config; set `PgbouncerConfig = {}` to clear.
        /// </summary>
        [Output("pgbouncerConfig")]
        public Output<ImmutableDictionary<string, string>> PgbouncerConfig { get; private set; } = null!;

        /// <summary>
        /// TCP port for client connections. Hardcoded to 5432 today; will become server-supplied once the API exposes a per-instance port field.
        /// </summary>
        [Output("port")]
        public Output<int> Port { get; private set; } = null!;

        /// <summary>
        /// Major Postgres version (e.g. '18'). The server picks the patch release within that major. Changing the major triggers destroy-and-recreate. Omit for a read replica or point-in-time restore (inherited from the source).
        /// </summary>
        [Output("postgresVersion")]
        public Output<string> PostgresVersion { get; private set; } = null!;

        /// <summary>
        /// ID of the primary instance to replicate. When set, this instance is created as a read replica (streaming replication) of that primary. Immutable for a live replica: changing or removing it destroys and recreates the instance as a standalone primary. The one exception is an out-of-band promotion — if you promote the replica via the API/UI (is*primary becomes true), changing or removing read*replica*of then reconciles state in place without destroying the promoted primary. Mutually exclusive with restore*to*point*in_time and with password (a replica inherits the primary's superuser).
        /// </summary>
        [Output("readReplicaOf")]
        public Output<string?> ReadReplicaOf { get; private set; } = null!;

        /// <summary>
        /// Cloud region (e.g. 'us-east-1'). No client-side validation; the server rejects unsupported regions. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
        /// </summary>
        [Output("region")]
        public Output<string> Region { get; private set; } = null!;

        /// <summary>
        /// Create this instance by restoring another Postgres instance's backup to a point in time. The whole block is create-time only: changing source*id / restore*target (re-restore to a new point) OR removing it both destroy and recreate the instance. The restored instance's name is this resource's top-level `Name` and it is independent of its source. cloud*provider / region / postgres*version are inherited from the source — omit them, or set them to match (a mismatch is a plan-time error); size and ha*type must be omitted (the restored instance comes up at the backup's size and a server-assigned HA mode). Mutually exclusive with read*replica*of.
        /// </summary>
        [Output("restoreToPointInTime")]
        public Output<Outputs.PostgresServiceRestoreToPointInTime?> RestoreToPointInTime { get; private set; } = null!;

        /// <summary>
        /// Instance size (VM SKU). See https://clickhouse.com/docs/cloud/managed-postgres/scaling for the supported instance families. No client-side enum; the server rejects unsupported sizes with HTTP 400 at apply time. Resizable in place. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
        /// </summary>
        [Output("size")]
        public Output<string> Size { get; private set; } = null!;

        /// <summary>
        /// Server-reported state. Examples: 'creating', 'running', 'restarting', 'unavailable', 'deleting'. Forward-compatible: unknown values from the server are surfaced verbatim.
        /// </summary>
        [Output("state")]
        public Output<string> State { get; private set; } = null!;

        /// <summary>
        /// Resource tags as a key-value map. Values must be non-empty (server's PATCH returns 400 on omitted value). Set `tags = {}` to clear all tags; omit the attribute to preserve the prior value.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableDictionary<string, string>> Tags { get; private set; } = null!;

        /// <summary>
        /// Default superuser name.
        /// </summary>
        [Output("username")]
        public Output<string> Username { get; private set; } = null!;


        /// <summary>
        /// Create a PostgresService resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PostgresService(string name, PostgresServiceArgs? args = null, CustomResourceOptions? options = null)
            : base("clickhouse:index/postgresService:PostgresService", name, args ?? new PostgresServiceArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PostgresService(string name, Input<string> id, PostgresServiceState? state = null, CustomResourceOptions? options = null)
            : base("clickhouse:index/postgresService:PostgresService", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse/pulumi-clickhouse",
                AdditionalSecretOutputs =
                {
                    "connectionString",
                    "password",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PostgresService resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PostgresService Get(string name, Input<string> id, PostgresServiceState? state = null, CustomResourceOptions? options = null)
        {
            return new PostgresService(name, id, state, options);
        }
    }

    public sealed class PostgresServiceArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Cloud provider hosting the instance. Currently only 'aws' is supported. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
        /// </summary>
        [Input("cloudProvider")]
        public Input<string>? CloudProvider { get; set; }

        /// <summary>
        /// High-availability mode. One of 'none' (single replica), 'async' (asynchronous replica), or 'sync' (synchronous replica). Mutable post-create; an HA flip triggers a transition. Omitting the attribute preserves the prior value (the server defaults to 'none' on Create); to actively downgrade, set 'ha_type = "none"' explicitly. Omit for a read replica or point-in-time restore (inherited from the source).
        /// </summary>
        [Input("haType")]
        public Input<string>? HaType { get; set; }

        /// <summary>
        /// Human-readable name. Immutable post-create; changes force destroy-and-recreate. Differs from clickhouse_service, which allows in-place rename.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// Superuser password. Optional: set it to manage the password in Terraform, or omit it and the server generates one. Computed and refreshed from each GET (the server echoes it), so it always reflects the live password and an out-of-band rotation is reconciled on the next refresh. Changing this value rotates the password (PATCH /password). Must be ≥12 chars with at least one lowercase, one uppercase, and one digit. Stored in (sensitive) state.
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("pgConfig")]
        private InputMap<string>? _pgConfig;

        /// <summary>
        /// Postgres server parameters (pgConfig) as a key-value map. Declared parameters are the desired state — every apply sends the full map via POST /config (full replacement), so removing a key from the map removes it server-side. Set `PgConfig = {}` to clear all parameters; omit the attribute to preserve the prior state (read replicas inherit the primary's parameters, and the server may surface values the configuration never declared — so it is Optional+Computed like tags). Out-of-band changes are reverted on the next apply. Some parameters require a database restart; the provider surfaces the server's restart-required hint as a warning (restart out-of-band).
        /// </summary>
        public InputMap<string> PgConfig
        {
            get => _pgConfig ?? (_pgConfig = new InputMap<string>());
            set => _pgConfig = value;
        }

        [Input("pgbouncerConfig")]
        private InputMap<string>? _pgbouncerConfig;

        /// <summary>
        /// PgBouncer connection-pooler parameters (pgBouncerConfig) as a key-value map. Same Optional+Computed semantics as pg_config; set `PgbouncerConfig = {}` to clear.
        /// </summary>
        public InputMap<string> PgbouncerConfig
        {
            get => _pgbouncerConfig ?? (_pgbouncerConfig = new InputMap<string>());
            set => _pgbouncerConfig = value;
        }

        /// <summary>
        /// Major Postgres version (e.g. '18'). The server picks the patch release within that major. Changing the major triggers destroy-and-recreate. Omit for a read replica or point-in-time restore (inherited from the source).
        /// </summary>
        [Input("postgresVersion")]
        public Input<string>? PostgresVersion { get; set; }

        /// <summary>
        /// ID of the primary instance to replicate. When set, this instance is created as a read replica (streaming replication) of that primary. Immutable for a live replica: changing or removing it destroys and recreates the instance as a standalone primary. The one exception is an out-of-band promotion — if you promote the replica via the API/UI (is*primary becomes true), changing or removing read*replica*of then reconciles state in place without destroying the promoted primary. Mutually exclusive with restore*to*point*in_time and with password (a replica inherits the primary's superuser).
        /// </summary>
        [Input("readReplicaOf")]
        public Input<string>? ReadReplicaOf { get; set; }

        /// <summary>
        /// Cloud region (e.g. 'us-east-1'). No client-side validation; the server rejects unsupported regions. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// Create this instance by restoring another Postgres instance's backup to a point in time. The whole block is create-time only: changing source*id / restore*target (re-restore to a new point) OR removing it both destroy and recreate the instance. The restored instance's name is this resource's top-level `Name` and it is independent of its source. cloud*provider / region / postgres*version are inherited from the source — omit them, or set them to match (a mismatch is a plan-time error); size and ha*type must be omitted (the restored instance comes up at the backup's size and a server-assigned HA mode). Mutually exclusive with read*replica*of.
        /// </summary>
        [Input("restoreToPointInTime")]
        public Input<Inputs.PostgresServiceRestoreToPointInTimeArgs>? RestoreToPointInTime { get; set; }

        /// <summary>
        /// Instance size (VM SKU). See https://clickhouse.com/docs/cloud/managed-postgres/scaling for the supported instance families. No client-side enum; the server rejects unsupported sizes with HTTP 400 at apply time. Resizable in place. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
        /// </summary>
        [Input("size")]
        public Input<string>? Size { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// Resource tags as a key-value map. Values must be non-empty (server's PATCH returns 400 on omitted value). Set `tags = {}` to clear all tags; omit the attribute to preserve the prior value.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        public PostgresServiceArgs()
        {
        }
        public static new PostgresServiceArgs Empty => new PostgresServiceArgs();
    }

    public sealed class PostgresServiceState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Cloud provider hosting the instance. Currently only 'aws' is supported. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
        /// </summary>
        [Input("cloudProvider")]
        public Input<string>? CloudProvider { get; set; }

        [Input("connectionString")]
        private Input<string>? _connectionString;

        /// <summary>
        /// Full connection URI embedding the username and the password. Marked sensitive; the secret-redaction layer also covers it in TF_LOG=DEBUG output. Plan stability is managed in ModifyPlan: pinned to the prior value on unrelated updates, marked unknown when a password rotation is planned (it embeds the password).
        /// </summary>
        public Input<string>? ConnectionString
        {
            get => _connectionString;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _connectionString = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// RFC3339 timestamp when the service was created.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// High-availability mode. One of 'none' (single replica), 'async' (asynchronous replica), or 'sync' (synchronous replica). Mutable post-create; an HA flip triggers a transition. Omitting the attribute preserves the prior value (the server defaults to 'none' on Create); to actively downgrade, set 'ha_type = "none"' explicitly. Omit for a read replica or point-in-time restore (inherited from the source).
        /// </summary>
        [Input("haType")]
        public Input<string>? HaType { get; set; }

        /// <summary>
        /// Network hostname for client connections.
        /// </summary>
        [Input("hostname")]
        public Input<string>? Hostname { get; set; }

        /// <summary>
        /// True when this instance is a writeable primary cluster; false only for separately-provisioned read replicas. HA standby servers (`HaType = async`/`Sync`) live inside the same primary instance and don't affect this value.
        /// </summary>
        [Input("isPrimary")]
        public Input<bool>? IsPrimary { get; set; }

        /// <summary>
        /// Human-readable name. Immutable post-create; changes force destroy-and-recreate. Differs from clickhouse_service, which allows in-place rename.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// Superuser password. Optional: set it to manage the password in Terraform, or omit it and the server generates one. Computed and refreshed from each GET (the server echoes it), so it always reflects the live password and an out-of-band rotation is reconciled on the next refresh. Changing this value rotates the password (PATCH /password). Must be ≥12 chars with at least one lowercase, one uppercase, and one digit. Stored in (sensitive) state.
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("pgConfig")]
        private InputMap<string>? _pgConfig;

        /// <summary>
        /// Postgres server parameters (pgConfig) as a key-value map. Declared parameters are the desired state — every apply sends the full map via POST /config (full replacement), so removing a key from the map removes it server-side. Set `PgConfig = {}` to clear all parameters; omit the attribute to preserve the prior state (read replicas inherit the primary's parameters, and the server may surface values the configuration never declared — so it is Optional+Computed like tags). Out-of-band changes are reverted on the next apply. Some parameters require a database restart; the provider surfaces the server's restart-required hint as a warning (restart out-of-band).
        /// </summary>
        public InputMap<string> PgConfig
        {
            get => _pgConfig ?? (_pgConfig = new InputMap<string>());
            set => _pgConfig = value;
        }

        [Input("pgbouncerConfig")]
        private InputMap<string>? _pgbouncerConfig;

        /// <summary>
        /// PgBouncer connection-pooler parameters (pgBouncerConfig) as a key-value map. Same Optional+Computed semantics as pg_config; set `PgbouncerConfig = {}` to clear.
        /// </summary>
        public InputMap<string> PgbouncerConfig
        {
            get => _pgbouncerConfig ?? (_pgbouncerConfig = new InputMap<string>());
            set => _pgbouncerConfig = value;
        }

        /// <summary>
        /// TCP port for client connections. Hardcoded to 5432 today; will become server-supplied once the API exposes a per-instance port field.
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        /// <summary>
        /// Major Postgres version (e.g. '18'). The server picks the patch release within that major. Changing the major triggers destroy-and-recreate. Omit for a read replica or point-in-time restore (inherited from the source).
        /// </summary>
        [Input("postgresVersion")]
        public Input<string>? PostgresVersion { get; set; }

        /// <summary>
        /// ID of the primary instance to replicate. When set, this instance is created as a read replica (streaming replication) of that primary. Immutable for a live replica: changing or removing it destroys and recreates the instance as a standalone primary. The one exception is an out-of-band promotion — if you promote the replica via the API/UI (is*primary becomes true), changing or removing read*replica*of then reconciles state in place without destroying the promoted primary. Mutually exclusive with restore*to*point*in_time and with password (a replica inherits the primary's superuser).
        /// </summary>
        [Input("readReplicaOf")]
        public Input<string>? ReadReplicaOf { get; set; }

        /// <summary>
        /// Cloud region (e.g. 'us-east-1'). No client-side validation; the server rejects unsupported regions. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        /// <summary>
        /// Create this instance by restoring another Postgres instance's backup to a point in time. The whole block is create-time only: changing source*id / restore*target (re-restore to a new point) OR removing it both destroy and recreate the instance. The restored instance's name is this resource's top-level `Name` and it is independent of its source. cloud*provider / region / postgres*version are inherited from the source — omit them, or set them to match (a mismatch is a plan-time error); size and ha*type must be omitted (the restored instance comes up at the backup's size and a server-assigned HA mode). Mutually exclusive with read*replica*of.
        /// </summary>
        [Input("restoreToPointInTime")]
        public Input<Inputs.PostgresServiceRestoreToPointInTimeGetArgs>? RestoreToPointInTime { get; set; }

        /// <summary>
        /// Instance size (VM SKU). See https://clickhouse.com/docs/cloud/managed-postgres/scaling for the supported instance families. No client-side enum; the server rejects unsupported sizes with HTTP 400 at apply time. Resizable in place. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
        /// </summary>
        [Input("size")]
        public Input<string>? Size { get; set; }

        /// <summary>
        /// Server-reported state. Examples: 'creating', 'running', 'restarting', 'unavailable', 'deleting'. Forward-compatible: unknown values from the server are surfaced verbatim.
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// Resource tags as a key-value map. Values must be non-empty (server's PATCH returns 400 on omitted value). Set `tags = {}` to clear all tags; omit the attribute to preserve the prior value.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        /// <summary>
        /// Default superuser name.
        /// </summary>
        [Input("username")]
        public Input<string>? Username { get; set; }

        public PostgresServiceState()
        {
        }
        public static new PostgresServiceState Empty => new PostgresServiceState();
    }
}
