// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse
{
    /// <summary>
    /// You can use the *clickhouse_service_scheduled_scaling* resource to manage time-based scaling rules for a ClickHouse Cloud service.
    /// 
    /// A schedule is a set of recurring weekly windows. The server rejects any pair of entries that overlap in time, so at most one window is active at any moment. While a window is active the service uses the replica count, memory bounds, and idle-scaling settings declared on that entry; otherwise the service falls back to its base auto-scaling configuration.
    /// 
    /// &gt; **Note:** This resource is in alpha. Scheduled scaling must be enabled for your organization (`canUseScheduledAutoscaling`). Reach out to ClickHouse support if the API returns `403 FORBIDDEN`. The server currently requires `MinReplicas == MaxReplicas` per entry, and a maximum of 10 entries per schedule.
    /// 
    /// ## Hour ranges
    /// 
    /// Hour ranges are asymmetric:
    /// 
    /// - `StartHourUtc` accepts `0`–`23`.
    /// - `EndHourUtc` accepts `1`–`24`.
    /// - `StartHourUtc` and `EndHourUtc` must differ.
    /// - Set `StartHourUtc = 0` and `EndHourUtc = 24` for a 24-hour window.
    /// - Set `EndHourUtc &lt; StartHourUtc` to wrap overnight (e.g. `22` to `6` covers 22:00–06:00 next day).
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Clickhouse = Pulumiverse.Clickhouse;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Clickhouse.ServiceScheduledScaling("example", new()
    ///     {
    ///         ServiceId = exampleClickhouseService.Id,
    ///         Entries = new[]
    ///         {
    ///             new Clickhouse.Inputs.ServiceScheduledScalingEntryArgs
    ///             {
    ///                 Name = "Business hours",
    ///                 Weekdays = new[]
    ///                 {
    ///                     1,
    ///                     2,
    ///                     3,
    ///                     4,
    ///                     5,
    ///                 },
    ///                 StartHourUtc = 8,
    ///                 EndHourUtc = 18,
    ///                 MinReplicas = 3,
    ///                 MaxReplicas = 3,
    ///                 IdleScaling = false,
    ///             },
    ///             new Clickhouse.Inputs.ServiceScheduledScalingEntryArgs
    ///             {
    ///                 Name = "Overnight",
    ///                 Weekdays = new[]
    ///                 {
    ///                     0,
    ///                     1,
    ///                     2,
    ///                     3,
    ///                     4,
    ///                     5,
    ///                     6,
    ///                 },
    ///                 StartHourUtc = 22,
    ///                 EndHourUtc = 6,
    ///                 MinReplicas = 1,
    ///                 MaxReplicas = 1,
    ///                 IdleScaling = true,
    ///                 IdleTimeoutMinutes = 5,
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// The `pulumi import` command can be used, for example:
    /// 
    /// !/bin/bash
    /// Scheduled scaling can be imported by specifying the service ID.
    /// 
    /// ```sh
    /// $ pulumi import clickhouse:index/serviceScheduledScaling:ServiceScheduledScaling example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    /// ```
    /// </summary>
    [ClickhouseResourceType("clickhouse:index/serviceScheduledScaling:ServiceScheduledScaling")]
    public partial class ServiceScheduledScaling : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Fallback configuration applied when no entry is currently active. Server-managed.
        /// </summary>
        [Output("baseConfig")]
        public Output<Outputs.ServiceScheduledScalingBaseConfig> BaseConfig { get; private set; } = null!;

        /// <summary>
        /// Recurring scaling windows. The server rejects any pair of entries that overlap in time, so at most one window is active at any moment; otherwise BaseConfig applies.
        /// </summary>
        [Output("entries")]
        public Output<ImmutableArray<Outputs.ServiceScheduledScalingEntry>> Entries { get; private set; } = null!;

        /// <summary>
        /// ClickHouse Cloud service ID this schedule applies to.
        /// </summary>
        [Output("serviceId")]
        public Output<string> ServiceId { get; private set; } = null!;


        /// <summary>
        /// Create a ServiceScheduledScaling resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ServiceScheduledScaling(string name, ServiceScheduledScalingArgs args, CustomResourceOptions? options = null)
            : base("clickhouse:index/serviceScheduledScaling:ServiceScheduledScaling", name, args ?? new ServiceScheduledScalingArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ServiceScheduledScaling(string name, Input<string> id, ServiceScheduledScalingState? state = null, CustomResourceOptions? options = null)
            : base("clickhouse:index/serviceScheduledScaling:ServiceScheduledScaling", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse/pulumi-clickhouse",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ServiceScheduledScaling resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ServiceScheduledScaling Get(string name, Input<string> id, ServiceScheduledScalingState? state = null, CustomResourceOptions? options = null)
        {
            return new ServiceScheduledScaling(name, id, state, options);
        }
    }

    public sealed class ServiceScheduledScalingArgs : global::Pulumi.ResourceArgs
    {
        [Input("entries", required: true)]
        private InputList<Inputs.ServiceScheduledScalingEntryArgs>? _entries;

        /// <summary>
        /// Recurring scaling windows. The server rejects any pair of entries that overlap in time, so at most one window is active at any moment; otherwise BaseConfig applies.
        /// </summary>
        public InputList<Inputs.ServiceScheduledScalingEntryArgs> Entries
        {
            get => _entries ?? (_entries = new InputList<Inputs.ServiceScheduledScalingEntryArgs>());
            set => _entries = value;
        }

        /// <summary>
        /// ClickHouse Cloud service ID this schedule applies to.
        /// </summary>
        [Input("serviceId", required: true)]
        public Input<string> ServiceId { get; set; } = null!;

        public ServiceScheduledScalingArgs()
        {
        }
        public static new ServiceScheduledScalingArgs Empty => new ServiceScheduledScalingArgs();
    }

    public sealed class ServiceScheduledScalingState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Fallback configuration applied when no entry is currently active. Server-managed.
        /// </summary>
        [Input("baseConfig")]
        public Input<Inputs.ServiceScheduledScalingBaseConfigGetArgs>? BaseConfig { get; set; }

        [Input("entries")]
        private InputList<Inputs.ServiceScheduledScalingEntryGetArgs>? _entries;

        /// <summary>
        /// Recurring scaling windows. The server rejects any pair of entries that overlap in time, so at most one window is active at any moment; otherwise BaseConfig applies.
        /// </summary>
        public InputList<Inputs.ServiceScheduledScalingEntryGetArgs> Entries
        {
            get => _entries ?? (_entries = new InputList<Inputs.ServiceScheduledScalingEntryGetArgs>());
            set => _entries = value;
        }

        /// <summary>
        /// ClickHouse Cloud service ID this schedule applies to.
        /// </summary>
        [Input("serviceId")]
        public Input<string>? ServiceId { get; set; }

        public ServiceScheduledScalingState()
        {
        }
        public static new ServiceScheduledScalingState Empty => new ServiceScheduledScalingState();
    }
}
