// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Outputs
{

    [OutputType]
    public sealed class ClickpipeSourcePubsubServiceAccountKey
    {
        /// <summary>
        /// Base64-encoded GCP service account JSON key file contents.
        /// </summary>
        public readonly string ServiceAccountFile;

        [OutputConstructor]
        private ClickpipeSourcePubsubServiceAccountKey(string serviceAccountFile)
        {
            ServiceAccountFile = serviceAccountFile;
        }
    }
}
