// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Outputs
{

    [OutputType]
    public sealed class ClickpipeSourceKafka
    {
        /// <summary>
        /// The authentication method for the Kafka source. (`PLAIN`, `SCRAM-SHA-256`, `SCRAM-SHA-512`, `IAM_ROLE`, `IAM_USER`, `MUTUAL_TLS`). Default is `PLAIN`.
        /// </summary>
        public readonly string? Authentication;
        /// <summary>
        /// The list of Kafka bootstrap brokers. (comma separated)
        /// </summary>
        public readonly string Brokers;
        /// <summary>
        /// PEM encoded CA certificates to validate the broker's certificate.
        /// </summary>
        public readonly string? CaCertificate;
        /// <summary>
        /// Consumer group of the Kafka source. If not provided `clickpipes-&lt;ID&gt;` will be used.
        /// </summary>
        public readonly string? ConsumerGroup;
        /// <summary>
        /// The credentials for the Kafka source.
        /// </summary>
        public readonly Outputs.ClickpipeSourceKafkaCredentials? Credentials;
        /// <summary>
        /// Enable exactly-once delivery. Guarantees every Kafka record is inserted exactly once across restarts and rebalances.
        /// </summary>
        public readonly bool? ExactlyOnce;
        /// <summary>
        /// The format of the Kafka source. (`JSONEachRow`, `Avro`, `AvroConfluent`, `Protobuf`)
        /// </summary>
        public readonly string Format;
        /// <summary>
        /// The IAM role for the Kafka source. Use with `IAM_ROLE` authentication. It can be used with AWS ClickHouse service only. Read more at https://clickhouse.com/docs/en/integrations/clickpipes/kafka#iam
        /// </summary>
        public readonly string? IamRole;
        /// <summary>
        /// The Kafka offset.
        /// </summary>
        public readonly Outputs.ClickpipeSourceKafkaOffset? Offset;
        /// <summary>
        /// The list of reverse private endpoint IDs for the Kafka source. (comma separated)
        /// </summary>
        public readonly ImmutableArray<string> ReversePrivateEndpointIds;
        /// <summary>
        /// The schema registry for the Kafka source.
        /// </summary>
        public readonly Outputs.ClickpipeSourceKafkaSchemaRegistry? SchemaRegistry;
        /// <summary>
        /// The list of Kafka topics. (comma separated)
        /// </summary>
        public readonly string Topics;
        /// <summary>
        /// The type of the Kafka source. (`Kafka`, `Redpanda`, `Confluent`, `Msk`, `Warpstream`, `Azureeventhub`, `Gcmk`). Default is `Kafka`.
        /// </summary>
        public readonly string? Type;

        [OutputConstructor]
        private ClickpipeSourceKafka(
            string? authentication,

            string brokers,

            string? caCertificate,

            string? consumerGroup,

            Outputs.ClickpipeSourceKafkaCredentials? credentials,

            bool? exactlyOnce,

            string format,

            string? iamRole,

            Outputs.ClickpipeSourceKafkaOffset? offset,

            ImmutableArray<string> reversePrivateEndpointIds,

            Outputs.ClickpipeSourceKafkaSchemaRegistry? schemaRegistry,

            string topics,

            string? type)
        {
            Authentication = authentication;
            Brokers = brokers;
            CaCertificate = caCertificate;
            ConsumerGroup = consumerGroup;
            Credentials = credentials;
            ExactlyOnce = exactlyOnce;
            Format = format;
            IamRole = iamRole;
            Offset = offset;
            ReversePrivateEndpointIds = reversePrivateEndpointIds;
            SchemaRegistry = schemaRegistry;
            Topics = topics;
            Type = type;
        }
    }
}
