// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Outputs
{

    [OutputType]
    public sealed class ClickpipeSourceKinesis
    {
        /// <summary>
        /// The access key for the Kinesis source. Use with `IAM_USER` authentication. Can be rotated in place via an update.
        /// </summary>
        public readonly Outputs.ClickpipeSourceKinesisAccessKey? AccessKey;
        /// <summary>
        /// The authentication method for the Kinesis source. (`IAM_ROLE`, `IAM_USER`).
        /// </summary>
        public readonly string Authentication;
        /// <summary>
        /// The format of the Kinesis source. (`JSONEachRow`, `Avro`, `AvroConfluent`)
        /// </summary>
        public readonly string Format;
        /// <summary>
        /// The IAM role for the Kinesis source. Use with `IAM_ROLE` authentication. It can be used with AWS ClickHouse service only. Read more at https://clickhouse.com/docs/en/integrations/clickpipes/kinesis.
        /// </summary>
        public readonly string? IamRole;
        /// <summary>
        /// The iterator type for the Kinesis source. (`TRIM_HORIZON`, `LATEST`, `AT_TIMESTAMP`)
        /// </summary>
        public readonly string IteratorType;
        /// <summary>
        /// The AWS region of the Kinesis stream.
        /// </summary>
        public readonly string Region;
        /// <summary>
        /// The name of the Kinesis stream.
        /// </summary>
        public readonly string StreamName;
        /// <summary>
        /// The timestamp for the Kinesis source. Use with `AT_TIMESTAMP` iterator type. (format `2021-01-01T00:00`)
        /// </summary>
        public readonly string? Timestamp;
        /// <summary>
        /// Whether to use enhanced fan-out consumer.
        /// </summary>
        public readonly bool? UseEnhancedFanOut;

        [OutputConstructor]
        private ClickpipeSourceKinesis(
            Outputs.ClickpipeSourceKinesisAccessKey? accessKey,

            string authentication,

            string format,

            string? iamRole,

            string iteratorType,

            string region,

            string streamName,

            string? timestamp,

            bool? useEnhancedFanOut)
        {
            AccessKey = accessKey;
            Authentication = authentication;
            Format = format;
            IamRole = iamRole;
            IteratorType = iteratorType;
            Region = region;
            StreamName = streamName;
            Timestamp = timestamp;
            UseEnhancedFanOut = useEnhancedFanOut;
        }
    }
}
