// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Outputs
{

    [OutputType]
    public sealed class ClickpipeSourceMongodbSettings
    {
        /// <summary>
        /// Enable hard delete behavior in ReplacingMergeTree for MongoDB DELETE operations.
        /// </summary>
        public readonly bool? DeleteOnMerge;
        /// <summary>
        /// Number of rows to pull in each batch during CDC replication.
        /// </summary>
        public readonly int? PullBatchSize;
        /// <summary>
        /// Replication mode for the MongoDB pipe. (`Cdc`, `Snapshot`, `CdcOnly`)
        /// </summary>
        public readonly string ReplicationMode;
        /// <summary>
        /// Number of rows per partition during the snapshot phase.
        /// </summary>
        public readonly int? SnapshotNumRowsPerPartition;
        /// <summary>
        /// Number of collections to snapshot in parallel during the initial load phase.
        /// </summary>
        public readonly int? SnapshotNumberOfParallelTables;
        /// <summary>
        /// Interval in seconds to sync data from MongoDB during CDC replication.
        /// </summary>
        public readonly int? SyncIntervalSeconds;
        /// <summary>
        /// Store JSON values in native ClickHouse JSON format. When disabled, JSON data is stored as String.
        /// </summary>
        public readonly bool? UseJsonNativeFormat;

        [OutputConstructor]
        private ClickpipeSourceMongodbSettings(
            bool? deleteOnMerge,

            int? pullBatchSize,

            string replicationMode,

            int? snapshotNumRowsPerPartition,

            int? snapshotNumberOfParallelTables,

            int? syncIntervalSeconds,

            bool? useJsonNativeFormat)
        {
            DeleteOnMerge = deleteOnMerge;
            PullBatchSize = pullBatchSize;
            ReplicationMode = replicationMode;
            SnapshotNumRowsPerPartition = snapshotNumRowsPerPartition;
            SnapshotNumberOfParallelTables = snapshotNumberOfParallelTables;
            SyncIntervalSeconds = syncIntervalSeconds;
            UseJsonNativeFormat = useJsonNativeFormat;
        }
    }
}
