// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Outputs
{

    [OutputType]
    public sealed class ClickpipeSourceMysqlTableMapping
    {
        /// <summary>
        /// Columns to exclude from replication.
        /// </summary>
        public readonly ImmutableArray<string> ExcludedColumns;
        /// <summary>
        /// Custom partitioning column used for parallel snapshotting. Must be an indexed column of integer, date, datetime, or timestamp type.
        /// </summary>
        public readonly string? PartitionKey;
        /// <summary>
        /// Ordered list of columns to use as sorting key for the target table. Required when use*custom*sorting_key is true.
        /// </summary>
        public readonly ImmutableArray<string> SortingKeys;
        /// <summary>
        /// Source schema (database) name in MySQL.
        /// </summary>
        public readonly string SourceSchemaName;
        /// <summary>
        /// Source table name in MySQL.
        /// </summary>
        public readonly string SourceTable;
        /// <summary>
        /// Table engine to use for the target table. (`MergeTree`, `ReplacingMergeTree`, `Null`)
        /// </summary>
        public readonly string? TableEngine;
        /// <summary>
        /// Target table name in ClickHouse.
        /// </summary>
        public readonly string TargetTable;
        /// <summary>
        /// Whether to use a custom sorting key for the target table.
        /// </summary>
        public readonly bool? UseCustomSortingKey;

        [OutputConstructor]
        private ClickpipeSourceMysqlTableMapping(
            ImmutableArray<string> excludedColumns,

            string? partitionKey,

            ImmutableArray<string> sortingKeys,

            string sourceSchemaName,

            string sourceTable,

            string? tableEngine,

            string targetTable,

            bool? useCustomSortingKey)
        {
            ExcludedColumns = excludedColumns;
            PartitionKey = partitionKey;
            SortingKeys = sortingKeys;
            SourceSchemaName = sourceSchemaName;
            SourceTable = sourceTable;
            TableEngine = tableEngine;
            TargetTable = targetTable;
            UseCustomSortingKey = useCustomSortingKey;
        }
    }
}
