// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Outputs
{

    [OutputType]
    public sealed class ClickpipeSourcePostgresSettings
    {
        /// <summary>
        /// Allow nullable columns in the destination table.
        /// </summary>
        public readonly bool? AllowNullableColumns;
        /// <summary>
        /// Enable hard delete behavior in ReplacingMergeTree for PostgreSQL DELETE operations.
        /// </summary>
        public readonly bool? DeleteOnMerge;
        /// <summary>
        /// Enable failover for created replication slot. Requires a replication slot to NOT be set.
        /// </summary>
        public readonly bool? EnableFailoverSlots;
        /// <summary>
        /// Number of parallel connections to use during initial load.
        /// </summary>
        public readonly int? InitialLoadParallelism;
        /// <summary>
        /// Publication name to use for replication. If not provided, ClickPipes will create one.
        /// </summary>
        public readonly string? PublicationName;
        /// <summary>
        /// Number of rows to pull in each batch.
        /// </summary>
        public readonly int? PullBatchSize;
        /// <summary>
        /// Replication mode for the Postgres pipe. (`Cdc`, `Snapshot`, `CdcOnly`)
        /// </summary>
        public readonly string ReplicationMode;
        /// <summary>
        /// Replication slot name to use for replication. Only applicable when ReplicationMode is `CdcOnly`.
        /// </summary>
        public readonly string? ReplicationSlotName;
        /// <summary>
        /// Number of rows to snapshot per partition.
        /// </summary>
        public readonly int? SnapshotNumRowsPerPartition;
        /// <summary>
        /// Number of parallel tables to snapshot.
        /// </summary>
        public readonly int? SnapshotNumberOfParallelTables;
        /// <summary>
        /// Interval in seconds to sync data from Postgres.
        /// </summary>
        public readonly int? SyncIntervalSeconds;

        [OutputConstructor]
        private ClickpipeSourcePostgresSettings(
            bool? allowNullableColumns,

            bool? deleteOnMerge,

            bool? enableFailoverSlots,

            int? initialLoadParallelism,

            string? publicationName,

            int? pullBatchSize,

            string replicationMode,

            string? replicationSlotName,

            int? snapshotNumRowsPerPartition,

            int? snapshotNumberOfParallelTables,

            int? syncIntervalSeconds)
        {
            AllowNullableColumns = allowNullableColumns;
            DeleteOnMerge = deleteOnMerge;
            EnableFailoverSlots = enableFailoverSlots;
            InitialLoadParallelism = initialLoadParallelism;
            PublicationName = publicationName;
            PullBatchSize = pullBatchSize;
            ReplicationMode = replicationMode;
            ReplicationSlotName = replicationSlotName;
            SnapshotNumRowsPerPartition = snapshotNumRowsPerPartition;
            SnapshotNumberOfParallelTables = snapshotNumberOfParallelTables;
            SyncIntervalSeconds = syncIntervalSeconds;
        }
    }
}
