// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Outputs
{

    [OutputType]
    public sealed class ClickpipeSourceBigquerySettings
    {
        /// <summary>
        /// Allow nullable columns in the destination table.
        /// </summary>
        public readonly bool? AllowNullableColumns;
        /// <summary>
        /// Number of parallel workers during initial load.
        /// </summary>
        public readonly int? InitialLoadParallelism;
        /// <summary>
        /// Replication mode for the BigQuery pipe. (`Snapshot`)
        /// </summary>
        public readonly string ReplicationMode;
        /// <summary>
        /// Number of rows to snapshot per partition.
        /// </summary>
        public readonly int? SnapshotNumRowsPerPartition;
        /// <summary>
        /// Number of parallel tables to snapshot.
        /// </summary>
        public readonly int? SnapshotNumberOfParallelTables;

        [OutputConstructor]
        private ClickpipeSourceBigquerySettings(
            bool? allowNullableColumns,

            int? initialLoadParallelism,

            string replicationMode,

            int? snapshotNumRowsPerPartition,

            int? snapshotNumberOfParallelTables)
        {
            AllowNullableColumns = allowNullableColumns;
            InitialLoadParallelism = initialLoadParallelism;
            ReplicationMode = replicationMode;
            SnapshotNumRowsPerPartition = snapshotNumRowsPerPartition;
            SnapshotNumberOfParallelTables = snapshotNumberOfParallelTables;
        }
    }
}
