// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Outputs
{

    [OutputType]
    public sealed class ClickpipeSourceBigquery
    {
        /// <summary>
        /// The credentials for BigQuery access.
        /// </summary>
        public readonly Outputs.ClickpipeSourceBigqueryCredentials Credentials;
        /// <summary>
        /// Settings for the BigQuery pipe.
        /// </summary>
        public readonly Outputs.ClickpipeSourceBigquerySettings Settings;
        /// <summary>
        /// GCS bucket path for staging snapshot data (e.g., gs://my-bucket/staging/). Data will be automatically cleaned up after initial load.
        /// </summary>
        public readonly string SnapshotStagingPath;
        /// <summary>
        /// Table mappings from BigQuery source to ClickHouse destination.
        /// </summary>
        public readonly ImmutableArray<Outputs.ClickpipeSourceBigqueryTableMapping> TableMappings;

        [OutputConstructor]
        private ClickpipeSourceBigquery(
            Outputs.ClickpipeSourceBigqueryCredentials credentials,

            Outputs.ClickpipeSourceBigquerySettings settings,

            string snapshotStagingPath,

            ImmutableArray<Outputs.ClickpipeSourceBigqueryTableMapping> tableMappings)
        {
            Credentials = credentials;
            Settings = settings;
            SnapshotStagingPath = snapshotStagingPath;
            TableMappings = tableMappings;
        }
    }
}
