// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Outputs
{

    [OutputType]
    public sealed class ServiceQueryApiEndpoints
    {
        /// <summary>
        /// Comma separated list of domain names to be allowed cross-origin resource sharing (CORS) access to the query API. Leave this field empty to restrict access to backend servers only
        /// </summary>
        public readonly string? AllowedOrigins;
        /// <summary>
        /// The UUIDs of the API Keys to grant access to the query API.
        /// </summary>
        public readonly ImmutableArray<string> ApiKeyIds;
        /// <summary>
        /// The Database role that will be used to run the query.
        /// </summary>
        public readonly ImmutableArray<string> Roles;

        [OutputConstructor]
        private ServiceQueryApiEndpoints(
            string? allowedOrigins,

            ImmutableArray<string> apiKeyIds,

            ImmutableArray<string> roles)
        {
            AllowedOrigins = allowedOrigins;
            ApiKeyIds = apiKeyIds;
            Roles = roles;
        }
    }
}
