// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Outputs
{

    [OutputType]
    public sealed class ServiceEndpoint
    {
        /// <summary>
        /// Endpoint host.
        /// </summary>
        public readonly string? Host;
        /// <summary>
        /// Endpoint port.
        /// </summary>
        public readonly int? Port;
        /// <summary>
        /// Endpoint protocol: https or nativesecure
        /// </summary>
        public readonly string? Protocol;

        [OutputConstructor]
        private ServiceEndpoint(
            string? host,

            int? port,

            string? protocol)
        {
            Host = host;
            Port = port;
            Protocol = protocol;
        }
    }
}
