// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Outputs
{

    [OutputType]
    public sealed class ServiceEndpoints
    {
        public readonly Outputs.ServiceEndpointsHttps? Https;
        public readonly Outputs.ServiceEndpointsMysql? Mysql;
        public readonly Outputs.ServiceEndpointsNativesecure? Nativesecure;

        [OutputConstructor]
        private ServiceEndpoints(
            Outputs.ServiceEndpointsHttps? https,

            Outputs.ServiceEndpointsMysql? mysql,

            Outputs.ServiceEndpointsNativesecure? nativesecure)
        {
            Https = https;
            Mysql = mysql;
            Nativesecure = nativesecure;
        }
    }
}
