// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Outputs
{

    [OutputType]
    public sealed class ServiceEndpointsMysql
    {
        /// <summary>
        /// Wether to enable the mysql endpoint or not.
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// Endpoint host.
        /// </summary>
        public readonly string? Host;
        /// <summary>
        /// Endpoint port.
        /// </summary>
        public readonly int? Port;

        [OutputConstructor]
        private ServiceEndpointsMysql(
            bool enabled,

            string? host,

            int? port)
        {
            Enabled = enabled;
            Host = host;
            Port = port;
        }
    }
}
