// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Outputs
{

    [OutputType]
    public sealed class ServiceBackupConfiguration
    {
        /// <summary>
        /// Interval in hours between each backup.
        /// </summary>
        public readonly int? BackupPeriodInHours;
        /// <summary>
        /// How long in hours to keep a backup before deleting it.
        /// </summary>
        public readonly int? BackupRetentionPeriodInHours;
        /// <summary>
        /// Time of the day in UTC that indicates the start time of a 2 hours window to be used for backup. If set, backup*period*in_hours must be null and backups are created once a day.
        /// </summary>
        public readonly string? BackupStartTime;

        [OutputConstructor]
        private ServiceBackupConfiguration(
            int? backupPeriodInHours,

            int? backupRetentionPeriodInHours,

            string? backupStartTime)
        {
            BackupPeriodInHours = backupPeriodInHours;
            BackupRetentionPeriodInHours = backupRetentionPeriodInHours;
            BackupStartTime = backupStartTime;
        }
    }
}
