// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package clickhouse

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-clickhouse/sdk/v2/go/clickhouse/internal"
)

// You can use the *clickhouse_clickpipe_cdc_infrastructure* resource to manage scaling settings for CDC ClickPipes infrastructure shared across all DB ClickPipes in a service.
//
// > **Important:** Only one CDC infrastructure resource per service is supported. Creating multiple instances for the same service will cause conflicts.
//
// This endpoint becomes available once at least one DB ClickPipe has been provisioned. The resource will poll for up to 10 minutes waiting for the endpoint to become available.
//
// For billing purposes, 2 CPU cores and 8 GB of RAM correspond to one compute unit.
//
// > **Note:** CDC infrastructure is shared across all DB ClickPipes and cannot be explicitly deleted. Removing this resource only removes it from Terraform state. The infrastructure is automatically cleaned up when all DB ClickPipes are deleted.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-clickhouse/sdk/v2/go/clickhouse"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := clickhouse.NewClickpipeCdcInfrastructure(ctx, "example", &clickhouse.ClickpipeCdcInfrastructureArgs{
//				ServiceId:            pulumi.String("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"),
//				ReplicaCpuMillicores: pulumi.Int(2000),
//				ReplicaMemoryGb:      pulumi.Float64(8),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// !/bin/bash
// CDC infrastructure can be imported by specifying the service ID.
//
// ```sh
// $ pulumi import clickhouse:index/clickpipeCdcInfrastructure:ClickpipeCdcInfrastructure example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
// ```
type ClickpipeCdcInfrastructure struct {
	pulumi.CustomResourceState

	// CPU in millicores for DB ClickPipes. Must be a multiple of 1000, between 1000 and 24000.
	ReplicaCpuMillicores pulumi.IntOutput `pulumi:"replicaCpuMillicores"`
	// Memory in GiB for DB ClickPipes. Must be a multiple of 4, between 4 and 96. Must be 4× the CPU core count.
	ReplicaMemoryGb pulumi.Float64Output `pulumi:"replicaMemoryGb"`
	// ClickHouse Cloud service ID where the CDC infrastructure is located.
	ServiceId pulumi.StringOutput `pulumi:"serviceId"`
}

// NewClickpipeCdcInfrastructure registers a new resource with the given unique name, arguments, and options.
func NewClickpipeCdcInfrastructure(ctx *pulumi.Context,
	name string, args *ClickpipeCdcInfrastructureArgs, opts ...pulumi.ResourceOption) (*ClickpipeCdcInfrastructure, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ReplicaCpuMillicores == nil {
		return nil, errors.New("invalid value for required argument 'ReplicaCpuMillicores'")
	}
	if args.ReplicaMemoryGb == nil {
		return nil, errors.New("invalid value for required argument 'ReplicaMemoryGb'")
	}
	if args.ServiceId == nil {
		return nil, errors.New("invalid value for required argument 'ServiceId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ClickpipeCdcInfrastructure
	err := ctx.RegisterResource("clickhouse:index/clickpipeCdcInfrastructure:ClickpipeCdcInfrastructure", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetClickpipeCdcInfrastructure gets an existing ClickpipeCdcInfrastructure resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetClickpipeCdcInfrastructure(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ClickpipeCdcInfrastructureState, opts ...pulumi.ResourceOption) (*ClickpipeCdcInfrastructure, error) {
	var resource ClickpipeCdcInfrastructure
	err := ctx.ReadResource("clickhouse:index/clickpipeCdcInfrastructure:ClickpipeCdcInfrastructure", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ClickpipeCdcInfrastructure resources.
type clickpipeCdcInfrastructureState struct {
	// CPU in millicores for DB ClickPipes. Must be a multiple of 1000, between 1000 and 24000.
	ReplicaCpuMillicores *int `pulumi:"replicaCpuMillicores"`
	// Memory in GiB for DB ClickPipes. Must be a multiple of 4, between 4 and 96. Must be 4× the CPU core count.
	ReplicaMemoryGb *float64 `pulumi:"replicaMemoryGb"`
	// ClickHouse Cloud service ID where the CDC infrastructure is located.
	ServiceId *string `pulumi:"serviceId"`
}

type ClickpipeCdcInfrastructureState struct {
	// CPU in millicores for DB ClickPipes. Must be a multiple of 1000, between 1000 and 24000.
	ReplicaCpuMillicores pulumi.IntPtrInput
	// Memory in GiB for DB ClickPipes. Must be a multiple of 4, between 4 and 96. Must be 4× the CPU core count.
	ReplicaMemoryGb pulumi.Float64PtrInput
	// ClickHouse Cloud service ID where the CDC infrastructure is located.
	ServiceId pulumi.StringPtrInput
}

func (ClickpipeCdcInfrastructureState) ElementType() reflect.Type {
	return reflect.TypeOf((*clickpipeCdcInfrastructureState)(nil)).Elem()
}

type clickpipeCdcInfrastructureArgs struct {
	// CPU in millicores for DB ClickPipes. Must be a multiple of 1000, between 1000 and 24000.
	ReplicaCpuMillicores int `pulumi:"replicaCpuMillicores"`
	// Memory in GiB for DB ClickPipes. Must be a multiple of 4, between 4 and 96. Must be 4× the CPU core count.
	ReplicaMemoryGb float64 `pulumi:"replicaMemoryGb"`
	// ClickHouse Cloud service ID where the CDC infrastructure is located.
	ServiceId string `pulumi:"serviceId"`
}

// The set of arguments for constructing a ClickpipeCdcInfrastructure resource.
type ClickpipeCdcInfrastructureArgs struct {
	// CPU in millicores for DB ClickPipes. Must be a multiple of 1000, between 1000 and 24000.
	ReplicaCpuMillicores pulumi.IntInput
	// Memory in GiB for DB ClickPipes. Must be a multiple of 4, between 4 and 96. Must be 4× the CPU core count.
	ReplicaMemoryGb pulumi.Float64Input
	// ClickHouse Cloud service ID where the CDC infrastructure is located.
	ServiceId pulumi.StringInput
}

func (ClickpipeCdcInfrastructureArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*clickpipeCdcInfrastructureArgs)(nil)).Elem()
}

type ClickpipeCdcInfrastructureInput interface {
	pulumi.Input

	ToClickpipeCdcInfrastructureOutput() ClickpipeCdcInfrastructureOutput
	ToClickpipeCdcInfrastructureOutputWithContext(ctx context.Context) ClickpipeCdcInfrastructureOutput
}

func (*ClickpipeCdcInfrastructure) ElementType() reflect.Type {
	return reflect.TypeOf((**ClickpipeCdcInfrastructure)(nil)).Elem()
}

func (i *ClickpipeCdcInfrastructure) ToClickpipeCdcInfrastructureOutput() ClickpipeCdcInfrastructureOutput {
	return i.ToClickpipeCdcInfrastructureOutputWithContext(context.Background())
}

func (i *ClickpipeCdcInfrastructure) ToClickpipeCdcInfrastructureOutputWithContext(ctx context.Context) ClickpipeCdcInfrastructureOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClickpipeCdcInfrastructureOutput)
}

// ClickpipeCdcInfrastructureArrayInput is an input type that accepts ClickpipeCdcInfrastructureArray and ClickpipeCdcInfrastructureArrayOutput values.
// You can construct a concrete instance of `ClickpipeCdcInfrastructureArrayInput` via:
//
//	ClickpipeCdcInfrastructureArray{ ClickpipeCdcInfrastructureArgs{...} }
type ClickpipeCdcInfrastructureArrayInput interface {
	pulumi.Input

	ToClickpipeCdcInfrastructureArrayOutput() ClickpipeCdcInfrastructureArrayOutput
	ToClickpipeCdcInfrastructureArrayOutputWithContext(context.Context) ClickpipeCdcInfrastructureArrayOutput
}

type ClickpipeCdcInfrastructureArray []ClickpipeCdcInfrastructureInput

func (ClickpipeCdcInfrastructureArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ClickpipeCdcInfrastructure)(nil)).Elem()
}

func (i ClickpipeCdcInfrastructureArray) ToClickpipeCdcInfrastructureArrayOutput() ClickpipeCdcInfrastructureArrayOutput {
	return i.ToClickpipeCdcInfrastructureArrayOutputWithContext(context.Background())
}

func (i ClickpipeCdcInfrastructureArray) ToClickpipeCdcInfrastructureArrayOutputWithContext(ctx context.Context) ClickpipeCdcInfrastructureArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClickpipeCdcInfrastructureArrayOutput)
}

// ClickpipeCdcInfrastructureMapInput is an input type that accepts ClickpipeCdcInfrastructureMap and ClickpipeCdcInfrastructureMapOutput values.
// You can construct a concrete instance of `ClickpipeCdcInfrastructureMapInput` via:
//
//	ClickpipeCdcInfrastructureMap{ "key": ClickpipeCdcInfrastructureArgs{...} }
type ClickpipeCdcInfrastructureMapInput interface {
	pulumi.Input

	ToClickpipeCdcInfrastructureMapOutput() ClickpipeCdcInfrastructureMapOutput
	ToClickpipeCdcInfrastructureMapOutputWithContext(context.Context) ClickpipeCdcInfrastructureMapOutput
}

type ClickpipeCdcInfrastructureMap map[string]ClickpipeCdcInfrastructureInput

func (ClickpipeCdcInfrastructureMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ClickpipeCdcInfrastructure)(nil)).Elem()
}

func (i ClickpipeCdcInfrastructureMap) ToClickpipeCdcInfrastructureMapOutput() ClickpipeCdcInfrastructureMapOutput {
	return i.ToClickpipeCdcInfrastructureMapOutputWithContext(context.Background())
}

func (i ClickpipeCdcInfrastructureMap) ToClickpipeCdcInfrastructureMapOutputWithContext(ctx context.Context) ClickpipeCdcInfrastructureMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClickpipeCdcInfrastructureMapOutput)
}

type ClickpipeCdcInfrastructureOutput struct{ *pulumi.OutputState }

func (ClickpipeCdcInfrastructureOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ClickpipeCdcInfrastructure)(nil)).Elem()
}

func (o ClickpipeCdcInfrastructureOutput) ToClickpipeCdcInfrastructureOutput() ClickpipeCdcInfrastructureOutput {
	return o
}

func (o ClickpipeCdcInfrastructureOutput) ToClickpipeCdcInfrastructureOutputWithContext(ctx context.Context) ClickpipeCdcInfrastructureOutput {
	return o
}

// CPU in millicores for DB ClickPipes. Must be a multiple of 1000, between 1000 and 24000.
func (o ClickpipeCdcInfrastructureOutput) ReplicaCpuMillicores() pulumi.IntOutput {
	return o.ApplyT(func(v *ClickpipeCdcInfrastructure) pulumi.IntOutput { return v.ReplicaCpuMillicores }).(pulumi.IntOutput)
}

// Memory in GiB for DB ClickPipes. Must be a multiple of 4, between 4 and 96. Must be 4× the CPU core count.
func (o ClickpipeCdcInfrastructureOutput) ReplicaMemoryGb() pulumi.Float64Output {
	return o.ApplyT(func(v *ClickpipeCdcInfrastructure) pulumi.Float64Output { return v.ReplicaMemoryGb }).(pulumi.Float64Output)
}

// ClickHouse Cloud service ID where the CDC infrastructure is located.
func (o ClickpipeCdcInfrastructureOutput) ServiceId() pulumi.StringOutput {
	return o.ApplyT(func(v *ClickpipeCdcInfrastructure) pulumi.StringOutput { return v.ServiceId }).(pulumi.StringOutput)
}

type ClickpipeCdcInfrastructureArrayOutput struct{ *pulumi.OutputState }

func (ClickpipeCdcInfrastructureArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ClickpipeCdcInfrastructure)(nil)).Elem()
}

func (o ClickpipeCdcInfrastructureArrayOutput) ToClickpipeCdcInfrastructureArrayOutput() ClickpipeCdcInfrastructureArrayOutput {
	return o
}

func (o ClickpipeCdcInfrastructureArrayOutput) ToClickpipeCdcInfrastructureArrayOutputWithContext(ctx context.Context) ClickpipeCdcInfrastructureArrayOutput {
	return o
}

func (o ClickpipeCdcInfrastructureArrayOutput) Index(i pulumi.IntInput) ClickpipeCdcInfrastructureOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ClickpipeCdcInfrastructure {
		return vs[0].([]*ClickpipeCdcInfrastructure)[vs[1].(int)]
	}).(ClickpipeCdcInfrastructureOutput)
}

type ClickpipeCdcInfrastructureMapOutput struct{ *pulumi.OutputState }

func (ClickpipeCdcInfrastructureMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ClickpipeCdcInfrastructure)(nil)).Elem()
}

func (o ClickpipeCdcInfrastructureMapOutput) ToClickpipeCdcInfrastructureMapOutput() ClickpipeCdcInfrastructureMapOutput {
	return o
}

func (o ClickpipeCdcInfrastructureMapOutput) ToClickpipeCdcInfrastructureMapOutputWithContext(ctx context.Context) ClickpipeCdcInfrastructureMapOutput {
	return o
}

func (o ClickpipeCdcInfrastructureMapOutput) MapIndex(k pulumi.StringInput) ClickpipeCdcInfrastructureOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ClickpipeCdcInfrastructure {
		return vs[0].(map[string]*ClickpipeCdcInfrastructure)[vs[1].(string)]
	}).(ClickpipeCdcInfrastructureOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ClickpipeCdcInfrastructureInput)(nil)).Elem(), &ClickpipeCdcInfrastructure{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClickpipeCdcInfrastructureArrayInput)(nil)).Elem(), ClickpipeCdcInfrastructureArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClickpipeCdcInfrastructureMapInput)(nil)).Elem(), ClickpipeCdcInfrastructureMap{})
	pulumi.RegisterOutputType(ClickpipeCdcInfrastructureOutput{})
	pulumi.RegisterOutputType(ClickpipeCdcInfrastructureArrayOutput{})
	pulumi.RegisterOutputType(ClickpipeCdcInfrastructureMapOutput{})
}
