// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package clickhouse

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-clickhouse/sdk/v2/go/clickhouse/internal"
)

// You can use the *clickhouse_clickpipe* resource to create and manage ClickPipes data ingestion pipelines in ClickHouse Cloud.
//
// Supported source types: Kafka (Confluent, MSK, Azure Event Hubs, Redpanda, WarpStream), Object Storage (S3, GCS, Azure Blob), Kinesis, Postgres CDC, MySQL CDC, BigQuery, and MongoDB CDC.
//
// Known limitations:
//
// - ClickPipe does not support table updates for managed tables. If you need to update the table schema, you will have to do that externally.
// - Changing the source type of an existing ClickPipe will force replacement (destroy and recreate).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-clickhouse/sdk/v2/go/clickhouse"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := clickhouse.NewClickpipe(ctx, "kafka_clickpipe", &clickhouse.ClickpipeArgs{
//				Name:      pulumi.String("My Kafka ClickPipe"),
//				ServiceId: pulumi.String("e9465b4b-f7e5-4937-8e21-8d508b02843d"),
//				Scaling: &clickhouse.ClickpipeScalingArgs{
//					Replicas:             pulumi.Int(2),
//					ReplicaCpuMillicores: pulumi.Int(250),
//					ReplicaMemoryGb:      pulumi.Float64(1),
//				},
//				Source: &clickhouse.ClickpipeSourceArgs{
//					Kafka: &clickhouse.ClickpipeSourceKafkaArgs{
//						Type:          pulumi.String("confluent"),
//						Format:        pulumi.String("JSONEachRow"),
//						Brokers:       pulumi.String("my-kafka-broker:9092"),
//						Topics:        pulumi.String("my_topic"),
//						ConsumerGroup: pulumi.String("clickpipe-test"),
//						Credentials: &clickhouse.ClickpipeSourceKafkaCredentialsArgs{
//							Username: pulumi.String("user"),
//							Password: pulumi.String("***"),
//						},
//					},
//				},
//				Destination: &clickhouse.ClickpipeDestinationArgs{
//					Table:        pulumi.String("my_table"),
//					ManagedTable: pulumi.Bool(true),
//					TableDefinition: &clickhouse.ClickpipeDestinationTableDefinitionArgs{
//						Engine: &clickhouse.ClickpipeDestinationTableDefinitionEngineArgs{
//							Type: pulumi.String("MergeTree"),
//						},
//					},
//					Columns: clickhouse.ClickpipeDestinationColumnArray{
//						&clickhouse.ClickpipeDestinationColumnArgs{
//							Name: pulumi.String("my_field1"),
//							Type: pulumi.String("String"),
//						},
//						&clickhouse.ClickpipeDestinationColumnArgs{
//							Name: pulumi.String("my_field2"),
//							Type: pulumi.String("UInt64"),
//						},
//					},
//				},
//				FieldMappings: clickhouse.ClickpipeFieldMappingArray{
//					&clickhouse.ClickpipeFieldMappingArgs{
//						SourceField:      pulumi.String("my_field"),
//						DestinationField: pulumi.String("my_field1"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// ClickPipes can be imported by specifying both service ID and clickpipe ID.
//
// ```sh
// $ pulumi import clickhouse:index/clickpipe:Clickpipe example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
// ```
type Clickpipe struct {
	pulumi.CustomResourceState

	// The destination for the ClickPipe.
	Destination ClickpipeDestinationOutput `pulumi:"destination"`
	// Field mapping between source and destination table.
	FieldMappings ClickpipeFieldMappingArrayOutput `pulumi:"fieldMappings"`
	// The name of the ClickPipe.
	Name    pulumi.StringOutput       `pulumi:"name"`
	Scaling ClickpipeScalingPtrOutput `pulumi:"scaling"`
	// The ID of the service to which the ClickPipe belongs.
	ServiceId pulumi.StringOutput `pulumi:"serviceId"`
	// Advanced configuration options for the ClickPipe. These settings are specific to each pipe. For the complete list of available options, see the OpenAPI documentation at https://clickhouse.com/docs/cloud/manage/api/swagger (search for the ClickPipes settings endpoint).
	Settings pulumi.AnyOutput `pulumi:"settings"`
	// The data source for the ClickPipe. At least one source configuration must be provided.
	Source ClickpipeSourceOutput `pulumi:"source"`
	// The current state of the ClickPipe. This is a read-only field that reports the actual state from ClickHouse Cloud. Possible values include `Running`, `Stopped`, `Paused`, `Provisioning`, `Failed`, `InternalError`, etc.
	State pulumi.StringOutput `pulumi:"state"`
	// Whether the ClickPipe should be stopped. Default is `false` (ClickPipe will be running). Cannot be set to `true` on creation — the ClickPipe must be created in a running state and then stopped via a subsequent apply.
	Stopped pulumi.BoolOutput `pulumi:"stopped"`
	// Set to `true` to trigger a resync operation. Only applicable for Postgres pipes. Automatically resets to `false` after the resync is triggered. **Note:** This will always show a diff in `pulumi preview` after setting to `true` since it resets to `false` in state.
	TriggerResync pulumi.BoolOutput `pulumi:"triggerResync"`
}

// NewClickpipe registers a new resource with the given unique name, arguments, and options.
func NewClickpipe(ctx *pulumi.Context,
	name string, args *ClickpipeArgs, opts ...pulumi.ResourceOption) (*Clickpipe, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Destination == nil {
		return nil, errors.New("invalid value for required argument 'Destination'")
	}
	if args.ServiceId == nil {
		return nil, errors.New("invalid value for required argument 'ServiceId'")
	}
	if args.Source == nil {
		return nil, errors.New("invalid value for required argument 'Source'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Clickpipe
	err := ctx.RegisterResource("clickhouse:index/clickpipe:Clickpipe", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetClickpipe gets an existing Clickpipe resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetClickpipe(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ClickpipeState, opts ...pulumi.ResourceOption) (*Clickpipe, error) {
	var resource Clickpipe
	err := ctx.ReadResource("clickhouse:index/clickpipe:Clickpipe", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Clickpipe resources.
type clickpipeState struct {
	// The destination for the ClickPipe.
	Destination *ClickpipeDestination `pulumi:"destination"`
	// Field mapping between source and destination table.
	FieldMappings []ClickpipeFieldMapping `pulumi:"fieldMappings"`
	// The name of the ClickPipe.
	Name    *string           `pulumi:"name"`
	Scaling *ClickpipeScaling `pulumi:"scaling"`
	// The ID of the service to which the ClickPipe belongs.
	ServiceId *string `pulumi:"serviceId"`
	// Advanced configuration options for the ClickPipe. These settings are specific to each pipe. For the complete list of available options, see the OpenAPI documentation at https://clickhouse.com/docs/cloud/manage/api/swagger (search for the ClickPipes settings endpoint).
	Settings interface{} `pulumi:"settings"`
	// The data source for the ClickPipe. At least one source configuration must be provided.
	Source *ClickpipeSource `pulumi:"source"`
	// The current state of the ClickPipe. This is a read-only field that reports the actual state from ClickHouse Cloud. Possible values include `Running`, `Stopped`, `Paused`, `Provisioning`, `Failed`, `InternalError`, etc.
	State *string `pulumi:"state"`
	// Whether the ClickPipe should be stopped. Default is `false` (ClickPipe will be running). Cannot be set to `true` on creation — the ClickPipe must be created in a running state and then stopped via a subsequent apply.
	Stopped *bool `pulumi:"stopped"`
	// Set to `true` to trigger a resync operation. Only applicable for Postgres pipes. Automatically resets to `false` after the resync is triggered. **Note:** This will always show a diff in `pulumi preview` after setting to `true` since it resets to `false` in state.
	TriggerResync *bool `pulumi:"triggerResync"`
}

type ClickpipeState struct {
	// The destination for the ClickPipe.
	Destination ClickpipeDestinationPtrInput
	// Field mapping between source and destination table.
	FieldMappings ClickpipeFieldMappingArrayInput
	// The name of the ClickPipe.
	Name    pulumi.StringPtrInput
	Scaling ClickpipeScalingPtrInput
	// The ID of the service to which the ClickPipe belongs.
	ServiceId pulumi.StringPtrInput
	// Advanced configuration options for the ClickPipe. These settings are specific to each pipe. For the complete list of available options, see the OpenAPI documentation at https://clickhouse.com/docs/cloud/manage/api/swagger (search for the ClickPipes settings endpoint).
	Settings pulumi.Input
	// The data source for the ClickPipe. At least one source configuration must be provided.
	Source ClickpipeSourcePtrInput
	// The current state of the ClickPipe. This is a read-only field that reports the actual state from ClickHouse Cloud. Possible values include `Running`, `Stopped`, `Paused`, `Provisioning`, `Failed`, `InternalError`, etc.
	State pulumi.StringPtrInput
	// Whether the ClickPipe should be stopped. Default is `false` (ClickPipe will be running). Cannot be set to `true` on creation — the ClickPipe must be created in a running state and then stopped via a subsequent apply.
	Stopped pulumi.BoolPtrInput
	// Set to `true` to trigger a resync operation. Only applicable for Postgres pipes. Automatically resets to `false` after the resync is triggered. **Note:** This will always show a diff in `pulumi preview` after setting to `true` since it resets to `false` in state.
	TriggerResync pulumi.BoolPtrInput
}

func (ClickpipeState) ElementType() reflect.Type {
	return reflect.TypeOf((*clickpipeState)(nil)).Elem()
}

type clickpipeArgs struct {
	// The destination for the ClickPipe.
	Destination ClickpipeDestination `pulumi:"destination"`
	// Field mapping between source and destination table.
	FieldMappings []ClickpipeFieldMapping `pulumi:"fieldMappings"`
	// The name of the ClickPipe.
	Name    *string           `pulumi:"name"`
	Scaling *ClickpipeScaling `pulumi:"scaling"`
	// The ID of the service to which the ClickPipe belongs.
	ServiceId string `pulumi:"serviceId"`
	// Advanced configuration options for the ClickPipe. These settings are specific to each pipe. For the complete list of available options, see the OpenAPI documentation at https://clickhouse.com/docs/cloud/manage/api/swagger (search for the ClickPipes settings endpoint).
	Settings interface{} `pulumi:"settings"`
	// The data source for the ClickPipe. At least one source configuration must be provided.
	Source ClickpipeSource `pulumi:"source"`
	// Whether the ClickPipe should be stopped. Default is `false` (ClickPipe will be running). Cannot be set to `true` on creation — the ClickPipe must be created in a running state and then stopped via a subsequent apply.
	Stopped *bool `pulumi:"stopped"`
	// Set to `true` to trigger a resync operation. Only applicable for Postgres pipes. Automatically resets to `false` after the resync is triggered. **Note:** This will always show a diff in `pulumi preview` after setting to `true` since it resets to `false` in state.
	TriggerResync *bool `pulumi:"triggerResync"`
}

// The set of arguments for constructing a Clickpipe resource.
type ClickpipeArgs struct {
	// The destination for the ClickPipe.
	Destination ClickpipeDestinationInput
	// Field mapping between source and destination table.
	FieldMappings ClickpipeFieldMappingArrayInput
	// The name of the ClickPipe.
	Name    pulumi.StringPtrInput
	Scaling ClickpipeScalingPtrInput
	// The ID of the service to which the ClickPipe belongs.
	ServiceId pulumi.StringInput
	// Advanced configuration options for the ClickPipe. These settings are specific to each pipe. For the complete list of available options, see the OpenAPI documentation at https://clickhouse.com/docs/cloud/manage/api/swagger (search for the ClickPipes settings endpoint).
	Settings pulumi.Input
	// The data source for the ClickPipe. At least one source configuration must be provided.
	Source ClickpipeSourceInput
	// Whether the ClickPipe should be stopped. Default is `false` (ClickPipe will be running). Cannot be set to `true` on creation — the ClickPipe must be created in a running state and then stopped via a subsequent apply.
	Stopped pulumi.BoolPtrInput
	// Set to `true` to trigger a resync operation. Only applicable for Postgres pipes. Automatically resets to `false` after the resync is triggered. **Note:** This will always show a diff in `pulumi preview` after setting to `true` since it resets to `false` in state.
	TriggerResync pulumi.BoolPtrInput
}

func (ClickpipeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*clickpipeArgs)(nil)).Elem()
}

type ClickpipeInput interface {
	pulumi.Input

	ToClickpipeOutput() ClickpipeOutput
	ToClickpipeOutputWithContext(ctx context.Context) ClickpipeOutput
}

func (*Clickpipe) ElementType() reflect.Type {
	return reflect.TypeOf((**Clickpipe)(nil)).Elem()
}

func (i *Clickpipe) ToClickpipeOutput() ClickpipeOutput {
	return i.ToClickpipeOutputWithContext(context.Background())
}

func (i *Clickpipe) ToClickpipeOutputWithContext(ctx context.Context) ClickpipeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClickpipeOutput)
}

// ClickpipeArrayInput is an input type that accepts ClickpipeArray and ClickpipeArrayOutput values.
// You can construct a concrete instance of `ClickpipeArrayInput` via:
//
//	ClickpipeArray{ ClickpipeArgs{...} }
type ClickpipeArrayInput interface {
	pulumi.Input

	ToClickpipeArrayOutput() ClickpipeArrayOutput
	ToClickpipeArrayOutputWithContext(context.Context) ClickpipeArrayOutput
}

type ClickpipeArray []ClickpipeInput

func (ClickpipeArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Clickpipe)(nil)).Elem()
}

func (i ClickpipeArray) ToClickpipeArrayOutput() ClickpipeArrayOutput {
	return i.ToClickpipeArrayOutputWithContext(context.Background())
}

func (i ClickpipeArray) ToClickpipeArrayOutputWithContext(ctx context.Context) ClickpipeArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClickpipeArrayOutput)
}

// ClickpipeMapInput is an input type that accepts ClickpipeMap and ClickpipeMapOutput values.
// You can construct a concrete instance of `ClickpipeMapInput` via:
//
//	ClickpipeMap{ "key": ClickpipeArgs{...} }
type ClickpipeMapInput interface {
	pulumi.Input

	ToClickpipeMapOutput() ClickpipeMapOutput
	ToClickpipeMapOutputWithContext(context.Context) ClickpipeMapOutput
}

type ClickpipeMap map[string]ClickpipeInput

func (ClickpipeMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Clickpipe)(nil)).Elem()
}

func (i ClickpipeMap) ToClickpipeMapOutput() ClickpipeMapOutput {
	return i.ToClickpipeMapOutputWithContext(context.Background())
}

func (i ClickpipeMap) ToClickpipeMapOutputWithContext(ctx context.Context) ClickpipeMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClickpipeMapOutput)
}

type ClickpipeOutput struct{ *pulumi.OutputState }

func (ClickpipeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Clickpipe)(nil)).Elem()
}

func (o ClickpipeOutput) ToClickpipeOutput() ClickpipeOutput {
	return o
}

func (o ClickpipeOutput) ToClickpipeOutputWithContext(ctx context.Context) ClickpipeOutput {
	return o
}

// The destination for the ClickPipe.
func (o ClickpipeOutput) Destination() ClickpipeDestinationOutput {
	return o.ApplyT(func(v *Clickpipe) ClickpipeDestinationOutput { return v.Destination }).(ClickpipeDestinationOutput)
}

// Field mapping between source and destination table.
func (o ClickpipeOutput) FieldMappings() ClickpipeFieldMappingArrayOutput {
	return o.ApplyT(func(v *Clickpipe) ClickpipeFieldMappingArrayOutput { return v.FieldMappings }).(ClickpipeFieldMappingArrayOutput)
}

// The name of the ClickPipe.
func (o ClickpipeOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Clickpipe) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o ClickpipeOutput) Scaling() ClickpipeScalingPtrOutput {
	return o.ApplyT(func(v *Clickpipe) ClickpipeScalingPtrOutput { return v.Scaling }).(ClickpipeScalingPtrOutput)
}

// The ID of the service to which the ClickPipe belongs.
func (o ClickpipeOutput) ServiceId() pulumi.StringOutput {
	return o.ApplyT(func(v *Clickpipe) pulumi.StringOutput { return v.ServiceId }).(pulumi.StringOutput)
}

// Advanced configuration options for the ClickPipe. These settings are specific to each pipe. For the complete list of available options, see the OpenAPI documentation at https://clickhouse.com/docs/cloud/manage/api/swagger (search for the ClickPipes settings endpoint).
func (o ClickpipeOutput) Settings() pulumi.AnyOutput {
	return o.ApplyT(func(v *Clickpipe) pulumi.AnyOutput { return v.Settings }).(pulumi.AnyOutput)
}

// The data source for the ClickPipe. At least one source configuration must be provided.
func (o ClickpipeOutput) Source() ClickpipeSourceOutput {
	return o.ApplyT(func(v *Clickpipe) ClickpipeSourceOutput { return v.Source }).(ClickpipeSourceOutput)
}

// The current state of the ClickPipe. This is a read-only field that reports the actual state from ClickHouse Cloud. Possible values include `Running`, `Stopped`, `Paused`, `Provisioning`, `Failed`, `InternalError`, etc.
func (o ClickpipeOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *Clickpipe) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

// Whether the ClickPipe should be stopped. Default is `false` (ClickPipe will be running). Cannot be set to `true` on creation — the ClickPipe must be created in a running state and then stopped via a subsequent apply.
func (o ClickpipeOutput) Stopped() pulumi.BoolOutput {
	return o.ApplyT(func(v *Clickpipe) pulumi.BoolOutput { return v.Stopped }).(pulumi.BoolOutput)
}

// Set to `true` to trigger a resync operation. Only applicable for Postgres pipes. Automatically resets to `false` after the resync is triggered. **Note:** This will always show a diff in `pulumi preview` after setting to `true` since it resets to `false` in state.
func (o ClickpipeOutput) TriggerResync() pulumi.BoolOutput {
	return o.ApplyT(func(v *Clickpipe) pulumi.BoolOutput { return v.TriggerResync }).(pulumi.BoolOutput)
}

type ClickpipeArrayOutput struct{ *pulumi.OutputState }

func (ClickpipeArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Clickpipe)(nil)).Elem()
}

func (o ClickpipeArrayOutput) ToClickpipeArrayOutput() ClickpipeArrayOutput {
	return o
}

func (o ClickpipeArrayOutput) ToClickpipeArrayOutputWithContext(ctx context.Context) ClickpipeArrayOutput {
	return o
}

func (o ClickpipeArrayOutput) Index(i pulumi.IntInput) ClickpipeOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Clickpipe {
		return vs[0].([]*Clickpipe)[vs[1].(int)]
	}).(ClickpipeOutput)
}

type ClickpipeMapOutput struct{ *pulumi.OutputState }

func (ClickpipeMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Clickpipe)(nil)).Elem()
}

func (o ClickpipeMapOutput) ToClickpipeMapOutput() ClickpipeMapOutput {
	return o
}

func (o ClickpipeMapOutput) ToClickpipeMapOutputWithContext(ctx context.Context) ClickpipeMapOutput {
	return o
}

func (o ClickpipeMapOutput) MapIndex(k pulumi.StringInput) ClickpipeOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Clickpipe {
		return vs[0].(map[string]*Clickpipe)[vs[1].(string)]
	}).(ClickpipeOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ClickpipeInput)(nil)).Elem(), &Clickpipe{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClickpipeArrayInput)(nil)).Elem(), ClickpipeArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClickpipeMapInput)(nil)).Elem(), ClickpipeMap{})
	pulumi.RegisterOutputType(ClickpipeOutput{})
	pulumi.RegisterOutputType(ClickpipeArrayOutput{})
	pulumi.RegisterOutputType(ClickpipeMapOutput{})
}
