// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package clickhouse

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-clickhouse/sdk/v2/go/clickhouse/internal"
)

// Use this data source to look up a single RBAC role by ID or name. Exactly one of `id` or `name` must be set.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-clickhouse/sdk/v2/go/clickhouse"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Look up a system role by name
//			_, err := clickhouse.LookupRole(ctx, &clickhouse.LookupRoleArgs{
//				Name: pulumi.StringRef("Admin"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			// Look up a custom role by ID
//			_, err = clickhouse.LookupRole(ctx, &clickhouse.LookupRoleArgs{
//				Id: pulumi.StringRef("47f0b035-d6ca-4600-8c69-9955551857e5"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupRole(ctx *pulumi.Context, args *LookupRoleArgs, opts ...pulumi.InvokeOption) (*LookupRoleResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupRoleResult
	err := ctx.Invoke("clickhouse:index/getRole:getRole", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getRole.
type LookupRoleArgs struct {
	// Unique identifier of the role. Exactly one of id or name must be set.
	Id *string `pulumi:"id"`
	// Name of the role to look up. Exactly one of id or name must be set.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getRole.
type LookupRoleResult struct {
	// List of actors assigned to this role.
	Actors []string `pulumi:"actors"`
	// Timestamp when the role was created.
	CreatedAt string `pulumi:"createdAt"`
	// Unique identifier of the role. Exactly one of id or name must be set.
	Id string `pulumi:"id"`
	// Name of the role to look up. Exactly one of id or name must be set.
	Name string `pulumi:"name"`
	// Owner ID of this role.
	OwnerId string `pulumi:"ownerId"`
	// List of policies attached to this role.
	Policies []GetRolePolicy `pulumi:"policies"`
	// Tenant ID that owns this role.
	TenantId string `pulumi:"tenantId"`
	// Type of the role: 'system' or 'custom'.
	Type string `pulumi:"type"`
	// Timestamp when the role was last updated.
	UpdatedAt string `pulumi:"updatedAt"`
}

func LookupRoleOutput(ctx *pulumi.Context, args LookupRoleOutputArgs, opts ...pulumi.InvokeOption) LookupRoleResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupRoleResultOutput, error) {
			args := v.(LookupRoleArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("clickhouse:index/getRole:getRole", args, LookupRoleResultOutput{}, options).(LookupRoleResultOutput), nil
		}).(LookupRoleResultOutput)
}

// A collection of arguments for invoking getRole.
type LookupRoleOutputArgs struct {
	// Unique identifier of the role. Exactly one of id or name must be set.
	Id pulumi.StringPtrInput `pulumi:"id"`
	// Name of the role to look up. Exactly one of id or name must be set.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (LookupRoleOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupRoleArgs)(nil)).Elem()
}

// A collection of values returned by getRole.
type LookupRoleResultOutput struct{ *pulumi.OutputState }

func (LookupRoleResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupRoleResult)(nil)).Elem()
}

func (o LookupRoleResultOutput) ToLookupRoleResultOutput() LookupRoleResultOutput {
	return o
}

func (o LookupRoleResultOutput) ToLookupRoleResultOutputWithContext(ctx context.Context) LookupRoleResultOutput {
	return o
}

// List of actors assigned to this role.
func (o LookupRoleResultOutput) Actors() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupRoleResult) []string { return v.Actors }).(pulumi.StringArrayOutput)
}

// Timestamp when the role was created.
func (o LookupRoleResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRoleResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// Unique identifier of the role. Exactly one of id or name must be set.
func (o LookupRoleResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRoleResult) string { return v.Id }).(pulumi.StringOutput)
}

// Name of the role to look up. Exactly one of id or name must be set.
func (o LookupRoleResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRoleResult) string { return v.Name }).(pulumi.StringOutput)
}

// Owner ID of this role.
func (o LookupRoleResultOutput) OwnerId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRoleResult) string { return v.OwnerId }).(pulumi.StringOutput)
}

// List of policies attached to this role.
func (o LookupRoleResultOutput) Policies() GetRolePolicyArrayOutput {
	return o.ApplyT(func(v LookupRoleResult) []GetRolePolicy { return v.Policies }).(GetRolePolicyArrayOutput)
}

// Tenant ID that owns this role.
func (o LookupRoleResultOutput) TenantId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRoleResult) string { return v.TenantId }).(pulumi.StringOutput)
}

// Type of the role: 'system' or 'custom'.
func (o LookupRoleResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRoleResult) string { return v.Type }).(pulumi.StringOutput)
}

// Timestamp when the role was last updated.
func (o LookupRoleResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRoleResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupRoleResultOutput{})
}
