// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package clickhouse

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-clickhouse/sdk/v2/go/clickhouse/internal"
)

// > **Note:** This resource is in alpha and its behavior may change in future provider versions.
//
// Manages a [ClickHouse Cloud Managed Postgres](https://clickhouse.com/cloud/postgres)
// service. A Managed Postgres service is a fully-managed Postgres instance
// provisioned in the ClickHouse Cloud control plane.
//
// ## Supported lifecycle
//
//   - Create — standard, as a read replica (`readReplicaOf`), or by
//     point-in-time restore (`restoreToPointInTime`)
//   - Read
//   - Update — `size`, `haType`, `tags`, `pgConfig`, `pgbouncerConfig`,
//     `password` rotation
//   - Delete
//   - Import
//
// Three companion data sources are also provided (alpha):
// `PostgresService`, `getPostgresServices`, and
// `getPostgresServiceCaCertificates`.
//
// ## Unsupported attributes
//
// The following are intentionally absent from the schema:
//
//   - Operational commands (restart / promote / switchover). See
//     "Operational commands" below for the rationale.
//   - IP allowlist, private endpoints, backup configuration, maintenance
//     windows, customer-managed encryption keys, BYOC. These depend on
//     server-side endpoint additions.
//   - Configurable lifecycle timeouts — there is no `timeouts {}` block; the
//     provider uses fixed internal poll/retry budgets.
//
// ## Tag semantics
//
// Tags are a `map(string → string)` — same shape as `Service`.
// Values must be non-empty alphanumeric / `.` / `-` / `_` strings (server
// regex `^[a-zA-Z0-9._-]+$`); the server's PATCH endpoint returns `400
// BAD_REQUEST` on omitted values, so the schema rejects empty values at
// plan time.
//
// Setting `tags = {}` clears all user-controlled tags. Omitting the
// attribute entirely preserves the prior state value (`Optional +
// Computed + UseStateForUnknown`).
//
// The Postgres PATCH endpoint has PUT-like semantics specifically for the
// `tags` field: omitting it from the request body clears all tags
// server-side. The provider works around this by re-asserting the current
// state tags in every PATCH that mutates `size` or `haType`, so users
// won't lose tags when they resize or change HA mode. This is invisible
// end-to-end but worth knowing if you inspect `TF_LOG=DEBUG` request
// bodies — you'll see tags repeated on non-tag mutations.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-clickhouse/sdk/v2/go/clickhouse"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := clickhouse.NewPostgresService(ctx, "example", &clickhouse.PostgresServiceArgs{
//				Name:          pulumi.String("my-postgres"),
//				CloudProvider: pulumi.String("aws"),
//				Region:        pulumi.String("us-east-1"),
//				Size:          pulumi.String("m6gd.large"),
//				HaType:        pulumi.String("async"),
//				Tags: pulumi.StringMap{
//					"environment": pulumi.String("production"),
//					"team":        pulumi.String("data"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// !/bin/bash
// Managed Postgres services can be imported by specifying the service ID.
// The password is recovered on import (the server echoes it on GET) and stored
// in state.
//
// ```sh
// $ pulumi import clickhouse:index/postgresService:PostgresService example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
// ```
type PostgresService struct {
	pulumi.CustomResourceState

	// Cloud provider hosting the instance. Currently only 'aws' is supported. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
	CloudProvider pulumi.StringOutput `pulumi:"cloudProvider"`
	// Full connection URI embedding the username and the password. Marked sensitive; the secret-redaction layer also covers it in TF_LOG=DEBUG output. Plan stability is managed in ModifyPlan: pinned to the prior value on unrelated updates, marked unknown when a password rotation is planned (it embeds the password).
	ConnectionString pulumi.StringOutput `pulumi:"connectionString"`
	// RFC3339 timestamp when the service was created.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// High-availability mode. One of 'none' (single replica), 'async' (asynchronous replica), or 'sync' (synchronous replica). Mutable post-create; an HA flip triggers a transition. Omitting the attribute preserves the prior value (the server defaults to 'none' on Create); to actively downgrade, set 'ha_type = "none"' explicitly. Omit for a read replica or point-in-time restore (inherited from the source).
	HaType pulumi.StringOutput `pulumi:"haType"`
	// Network hostname for client connections.
	Hostname pulumi.StringOutput `pulumi:"hostname"`
	// True when this instance is a writeable primary cluster; false only for separately-provisioned read replicas. HA standby servers (`haType = async`/`sync`) live inside the same primary instance and don't affect this value.
	IsPrimary pulumi.BoolOutput `pulumi:"isPrimary"`
	// Human-readable name. Immutable post-create; changes force destroy-and-recreate. Differs from clickhouse_service, which allows in-place rename.
	Name pulumi.StringOutput `pulumi:"name"`
	// Superuser password. Optional: set it to manage the password in Terraform, or omit it and the server generates one. Computed and refreshed from each GET (the server echoes it), so it always reflects the live password and an out-of-band rotation is reconciled on the next refresh. Changing this value rotates the password (PATCH /password). Must be ≥12 chars with at least one lowercase, one uppercase, and one digit. Stored in (sensitive) state.
	Password pulumi.StringOutput `pulumi:"password"`
	// Postgres server parameters (pgConfig) as a key-value map. Declared parameters are the desired state — every apply sends the full map via POST /config (full replacement), so removing a key from the map removes it server-side. Set `pgConfig = {}` to clear all parameters; omit the attribute to preserve the prior state (read replicas inherit the primary's parameters, and the server may surface values the configuration never declared — so it is Optional+Computed like tags). Out-of-band changes are reverted on the next apply. Some parameters require a database restart; the provider surfaces the server's restart-required hint as a warning (restart out-of-band).
	PgConfig pulumi.StringMapOutput `pulumi:"pgConfig"`
	// PgBouncer connection-pooler parameters (pgBouncerConfig) as a key-value map. Same Optional+Computed semantics as pg_config; set `pgbouncerConfig = {}` to clear.
	PgbouncerConfig pulumi.StringMapOutput `pulumi:"pgbouncerConfig"`
	// TCP port for client connections. Hardcoded to 5432 today; will become server-supplied once the API exposes a per-instance port field.
	Port pulumi.IntOutput `pulumi:"port"`
	// Major Postgres version (e.g. '18'). The server picks the patch release within that major. Changing the major triggers destroy-and-recreate. Omit for a read replica or point-in-time restore (inherited from the source).
	PostgresVersion pulumi.StringOutput `pulumi:"postgresVersion"`
	// ID of the primary instance to replicate. When set, this instance is created as a read replica (streaming replication) of that primary. Immutable for a live replica: changing or removing it destroys and recreates the instance as a standalone primary. The one exception is an out-of-band promotion — if you promote the replica via the API/UI (is*primary becomes true), changing or removing read*replica*of then reconciles state in place without destroying the promoted primary. Mutually exclusive with restore*to*point*in_time and with password (a replica inherits the primary's superuser).
	ReadReplicaOf pulumi.StringPtrOutput `pulumi:"readReplicaOf"`
	// Cloud region (e.g. 'us-east-1'). No client-side validation; the server rejects unsupported regions. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
	Region pulumi.StringOutput `pulumi:"region"`
	// Create this instance by restoring another Postgres instance's backup to a point in time. The whole block is create-time only: changing source*id / restore*target (re-restore to a new point) OR removing it both destroy and recreate the instance. The restored instance's name is this resource's top-level `name` and it is independent of its source. cloud*provider / region / postgres*version are inherited from the source — omit them, or set them to match (a mismatch is a plan-time error); size and ha*type must be omitted (the restored instance comes up at the backup's size and a server-assigned HA mode). Mutually exclusive with read*replica*of.
	RestoreToPointInTime PostgresServiceRestoreToPointInTimePtrOutput `pulumi:"restoreToPointInTime"`
	// Instance size (VM SKU). See https://clickhouse.com/docs/cloud/managed-postgres/scaling for the supported instance families. No client-side enum; the server rejects unsupported sizes with HTTP 400 at apply time. Resizable in place. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
	Size pulumi.StringOutput `pulumi:"size"`
	// Server-reported state. Examples: 'creating', 'running', 'restarting', 'unavailable', 'deleting'. Forward-compatible: unknown values from the server are surfaced verbatim.
	State pulumi.StringOutput `pulumi:"state"`
	// Resource tags as a key-value map. Values must be non-empty (server's PATCH returns 400 on omitted value). Set `tags = {}` to clear all tags; omit the attribute to preserve the prior value.
	Tags pulumi.StringMapOutput `pulumi:"tags"`
	// Default superuser name.
	Username pulumi.StringOutput `pulumi:"username"`
}

// NewPostgresService registers a new resource with the given unique name, arguments, and options.
func NewPostgresService(ctx *pulumi.Context,
	name string, args *PostgresServiceArgs, opts ...pulumi.ResourceOption) (*PostgresService, error) {
	if args == nil {
		args = &PostgresServiceArgs{}
	}

	if args.Password != nil {
		args.Password = pulumi.ToSecret(args.Password).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"connectionString",
		"password",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PostgresService
	err := ctx.RegisterResource("clickhouse:index/postgresService:PostgresService", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPostgresService gets an existing PostgresService resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPostgresService(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PostgresServiceState, opts ...pulumi.ResourceOption) (*PostgresService, error) {
	var resource PostgresService
	err := ctx.ReadResource("clickhouse:index/postgresService:PostgresService", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PostgresService resources.
type postgresServiceState struct {
	// Cloud provider hosting the instance. Currently only 'aws' is supported. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
	CloudProvider *string `pulumi:"cloudProvider"`
	// Full connection URI embedding the username and the password. Marked sensitive; the secret-redaction layer also covers it in TF_LOG=DEBUG output. Plan stability is managed in ModifyPlan: pinned to the prior value on unrelated updates, marked unknown when a password rotation is planned (it embeds the password).
	ConnectionString *string `pulumi:"connectionString"`
	// RFC3339 timestamp when the service was created.
	CreatedAt *string `pulumi:"createdAt"`
	// High-availability mode. One of 'none' (single replica), 'async' (asynchronous replica), or 'sync' (synchronous replica). Mutable post-create; an HA flip triggers a transition. Omitting the attribute preserves the prior value (the server defaults to 'none' on Create); to actively downgrade, set 'ha_type = "none"' explicitly. Omit for a read replica or point-in-time restore (inherited from the source).
	HaType *string `pulumi:"haType"`
	// Network hostname for client connections.
	Hostname *string `pulumi:"hostname"`
	// True when this instance is a writeable primary cluster; false only for separately-provisioned read replicas. HA standby servers (`haType = async`/`sync`) live inside the same primary instance and don't affect this value.
	IsPrimary *bool `pulumi:"isPrimary"`
	// Human-readable name. Immutable post-create; changes force destroy-and-recreate. Differs from clickhouse_service, which allows in-place rename.
	Name *string `pulumi:"name"`
	// Superuser password. Optional: set it to manage the password in Terraform, or omit it and the server generates one. Computed and refreshed from each GET (the server echoes it), so it always reflects the live password and an out-of-band rotation is reconciled on the next refresh. Changing this value rotates the password (PATCH /password). Must be ≥12 chars with at least one lowercase, one uppercase, and one digit. Stored in (sensitive) state.
	Password *string `pulumi:"password"`
	// Postgres server parameters (pgConfig) as a key-value map. Declared parameters are the desired state — every apply sends the full map via POST /config (full replacement), so removing a key from the map removes it server-side. Set `pgConfig = {}` to clear all parameters; omit the attribute to preserve the prior state (read replicas inherit the primary's parameters, and the server may surface values the configuration never declared — so it is Optional+Computed like tags). Out-of-band changes are reverted on the next apply. Some parameters require a database restart; the provider surfaces the server's restart-required hint as a warning (restart out-of-band).
	PgConfig map[string]string `pulumi:"pgConfig"`
	// PgBouncer connection-pooler parameters (pgBouncerConfig) as a key-value map. Same Optional+Computed semantics as pg_config; set `pgbouncerConfig = {}` to clear.
	PgbouncerConfig map[string]string `pulumi:"pgbouncerConfig"`
	// TCP port for client connections. Hardcoded to 5432 today; will become server-supplied once the API exposes a per-instance port field.
	Port *int `pulumi:"port"`
	// Major Postgres version (e.g. '18'). The server picks the patch release within that major. Changing the major triggers destroy-and-recreate. Omit for a read replica or point-in-time restore (inherited from the source).
	PostgresVersion *string `pulumi:"postgresVersion"`
	// ID of the primary instance to replicate. When set, this instance is created as a read replica (streaming replication) of that primary. Immutable for a live replica: changing or removing it destroys and recreates the instance as a standalone primary. The one exception is an out-of-band promotion — if you promote the replica via the API/UI (is*primary becomes true), changing or removing read*replica*of then reconciles state in place without destroying the promoted primary. Mutually exclusive with restore*to*point*in_time and with password (a replica inherits the primary's superuser).
	ReadReplicaOf *string `pulumi:"readReplicaOf"`
	// Cloud region (e.g. 'us-east-1'). No client-side validation; the server rejects unsupported regions. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
	Region *string `pulumi:"region"`
	// Create this instance by restoring another Postgres instance's backup to a point in time. The whole block is create-time only: changing source*id / restore*target (re-restore to a new point) OR removing it both destroy and recreate the instance. The restored instance's name is this resource's top-level `name` and it is independent of its source. cloud*provider / region / postgres*version are inherited from the source — omit them, or set them to match (a mismatch is a plan-time error); size and ha*type must be omitted (the restored instance comes up at the backup's size and a server-assigned HA mode). Mutually exclusive with read*replica*of.
	RestoreToPointInTime *PostgresServiceRestoreToPointInTime `pulumi:"restoreToPointInTime"`
	// Instance size (VM SKU). See https://clickhouse.com/docs/cloud/managed-postgres/scaling for the supported instance families. No client-side enum; the server rejects unsupported sizes with HTTP 400 at apply time. Resizable in place. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
	Size *string `pulumi:"size"`
	// Server-reported state. Examples: 'creating', 'running', 'restarting', 'unavailable', 'deleting'. Forward-compatible: unknown values from the server are surfaced verbatim.
	State *string `pulumi:"state"`
	// Resource tags as a key-value map. Values must be non-empty (server's PATCH returns 400 on omitted value). Set `tags = {}` to clear all tags; omit the attribute to preserve the prior value.
	Tags map[string]string `pulumi:"tags"`
	// Default superuser name.
	Username *string `pulumi:"username"`
}

type PostgresServiceState struct {
	// Cloud provider hosting the instance. Currently only 'aws' is supported. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
	CloudProvider pulumi.StringPtrInput
	// Full connection URI embedding the username and the password. Marked sensitive; the secret-redaction layer also covers it in TF_LOG=DEBUG output. Plan stability is managed in ModifyPlan: pinned to the prior value on unrelated updates, marked unknown when a password rotation is planned (it embeds the password).
	ConnectionString pulumi.StringPtrInput
	// RFC3339 timestamp when the service was created.
	CreatedAt pulumi.StringPtrInput
	// High-availability mode. One of 'none' (single replica), 'async' (asynchronous replica), or 'sync' (synchronous replica). Mutable post-create; an HA flip triggers a transition. Omitting the attribute preserves the prior value (the server defaults to 'none' on Create); to actively downgrade, set 'ha_type = "none"' explicitly. Omit for a read replica or point-in-time restore (inherited from the source).
	HaType pulumi.StringPtrInput
	// Network hostname for client connections.
	Hostname pulumi.StringPtrInput
	// True when this instance is a writeable primary cluster; false only for separately-provisioned read replicas. HA standby servers (`haType = async`/`sync`) live inside the same primary instance and don't affect this value.
	IsPrimary pulumi.BoolPtrInput
	// Human-readable name. Immutable post-create; changes force destroy-and-recreate. Differs from clickhouse_service, which allows in-place rename.
	Name pulumi.StringPtrInput
	// Superuser password. Optional: set it to manage the password in Terraform, or omit it and the server generates one. Computed and refreshed from each GET (the server echoes it), so it always reflects the live password and an out-of-band rotation is reconciled on the next refresh. Changing this value rotates the password (PATCH /password). Must be ≥12 chars with at least one lowercase, one uppercase, and one digit. Stored in (sensitive) state.
	Password pulumi.StringPtrInput
	// Postgres server parameters (pgConfig) as a key-value map. Declared parameters are the desired state — every apply sends the full map via POST /config (full replacement), so removing a key from the map removes it server-side. Set `pgConfig = {}` to clear all parameters; omit the attribute to preserve the prior state (read replicas inherit the primary's parameters, and the server may surface values the configuration never declared — so it is Optional+Computed like tags). Out-of-band changes are reverted on the next apply. Some parameters require a database restart; the provider surfaces the server's restart-required hint as a warning (restart out-of-band).
	PgConfig pulumi.StringMapInput
	// PgBouncer connection-pooler parameters (pgBouncerConfig) as a key-value map. Same Optional+Computed semantics as pg_config; set `pgbouncerConfig = {}` to clear.
	PgbouncerConfig pulumi.StringMapInput
	// TCP port for client connections. Hardcoded to 5432 today; will become server-supplied once the API exposes a per-instance port field.
	Port pulumi.IntPtrInput
	// Major Postgres version (e.g. '18'). The server picks the patch release within that major. Changing the major triggers destroy-and-recreate. Omit for a read replica or point-in-time restore (inherited from the source).
	PostgresVersion pulumi.StringPtrInput
	// ID of the primary instance to replicate. When set, this instance is created as a read replica (streaming replication) of that primary. Immutable for a live replica: changing or removing it destroys and recreates the instance as a standalone primary. The one exception is an out-of-band promotion — if you promote the replica via the API/UI (is*primary becomes true), changing or removing read*replica*of then reconciles state in place without destroying the promoted primary. Mutually exclusive with restore*to*point*in_time and with password (a replica inherits the primary's superuser).
	ReadReplicaOf pulumi.StringPtrInput
	// Cloud region (e.g. 'us-east-1'). No client-side validation; the server rejects unsupported regions. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
	Region pulumi.StringPtrInput
	// Create this instance by restoring another Postgres instance's backup to a point in time. The whole block is create-time only: changing source*id / restore*target (re-restore to a new point) OR removing it both destroy and recreate the instance. The restored instance's name is this resource's top-level `name` and it is independent of its source. cloud*provider / region / postgres*version are inherited from the source — omit them, or set them to match (a mismatch is a plan-time error); size and ha*type must be omitted (the restored instance comes up at the backup's size and a server-assigned HA mode). Mutually exclusive with read*replica*of.
	RestoreToPointInTime PostgresServiceRestoreToPointInTimePtrInput
	// Instance size (VM SKU). See https://clickhouse.com/docs/cloud/managed-postgres/scaling for the supported instance families. No client-side enum; the server rejects unsupported sizes with HTTP 400 at apply time. Resizable in place. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
	Size pulumi.StringPtrInput
	// Server-reported state. Examples: 'creating', 'running', 'restarting', 'unavailable', 'deleting'. Forward-compatible: unknown values from the server are surfaced verbatim.
	State pulumi.StringPtrInput
	// Resource tags as a key-value map. Values must be non-empty (server's PATCH returns 400 on omitted value). Set `tags = {}` to clear all tags; omit the attribute to preserve the prior value.
	Tags pulumi.StringMapInput
	// Default superuser name.
	Username pulumi.StringPtrInput
}

func (PostgresServiceState) ElementType() reflect.Type {
	return reflect.TypeOf((*postgresServiceState)(nil)).Elem()
}

type postgresServiceArgs struct {
	// Cloud provider hosting the instance. Currently only 'aws' is supported. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
	CloudProvider *string `pulumi:"cloudProvider"`
	// High-availability mode. One of 'none' (single replica), 'async' (asynchronous replica), or 'sync' (synchronous replica). Mutable post-create; an HA flip triggers a transition. Omitting the attribute preserves the prior value (the server defaults to 'none' on Create); to actively downgrade, set 'ha_type = "none"' explicitly. Omit for a read replica or point-in-time restore (inherited from the source).
	HaType *string `pulumi:"haType"`
	// Human-readable name. Immutable post-create; changes force destroy-and-recreate. Differs from clickhouse_service, which allows in-place rename.
	Name *string `pulumi:"name"`
	// Superuser password. Optional: set it to manage the password in Terraform, or omit it and the server generates one. Computed and refreshed from each GET (the server echoes it), so it always reflects the live password and an out-of-band rotation is reconciled on the next refresh. Changing this value rotates the password (PATCH /password). Must be ≥12 chars with at least one lowercase, one uppercase, and one digit. Stored in (sensitive) state.
	Password *string `pulumi:"password"`
	// Postgres server parameters (pgConfig) as a key-value map. Declared parameters are the desired state — every apply sends the full map via POST /config (full replacement), so removing a key from the map removes it server-side. Set `pgConfig = {}` to clear all parameters; omit the attribute to preserve the prior state (read replicas inherit the primary's parameters, and the server may surface values the configuration never declared — so it is Optional+Computed like tags). Out-of-band changes are reverted on the next apply. Some parameters require a database restart; the provider surfaces the server's restart-required hint as a warning (restart out-of-band).
	PgConfig map[string]string `pulumi:"pgConfig"`
	// PgBouncer connection-pooler parameters (pgBouncerConfig) as a key-value map. Same Optional+Computed semantics as pg_config; set `pgbouncerConfig = {}` to clear.
	PgbouncerConfig map[string]string `pulumi:"pgbouncerConfig"`
	// Major Postgres version (e.g. '18'). The server picks the patch release within that major. Changing the major triggers destroy-and-recreate. Omit for a read replica or point-in-time restore (inherited from the source).
	PostgresVersion *string `pulumi:"postgresVersion"`
	// ID of the primary instance to replicate. When set, this instance is created as a read replica (streaming replication) of that primary. Immutable for a live replica: changing or removing it destroys and recreates the instance as a standalone primary. The one exception is an out-of-band promotion — if you promote the replica via the API/UI (is*primary becomes true), changing or removing read*replica*of then reconciles state in place without destroying the promoted primary. Mutually exclusive with restore*to*point*in_time and with password (a replica inherits the primary's superuser).
	ReadReplicaOf *string `pulumi:"readReplicaOf"`
	// Cloud region (e.g. 'us-east-1'). No client-side validation; the server rejects unsupported regions. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
	Region *string `pulumi:"region"`
	// Create this instance by restoring another Postgres instance's backup to a point in time. The whole block is create-time only: changing source*id / restore*target (re-restore to a new point) OR removing it both destroy and recreate the instance. The restored instance's name is this resource's top-level `name` and it is independent of its source. cloud*provider / region / postgres*version are inherited from the source — omit them, or set them to match (a mismatch is a plan-time error); size and ha*type must be omitted (the restored instance comes up at the backup's size and a server-assigned HA mode). Mutually exclusive with read*replica*of.
	RestoreToPointInTime *PostgresServiceRestoreToPointInTime `pulumi:"restoreToPointInTime"`
	// Instance size (VM SKU). See https://clickhouse.com/docs/cloud/managed-postgres/scaling for the supported instance families. No client-side enum; the server rejects unsupported sizes with HTTP 400 at apply time. Resizable in place. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
	Size *string `pulumi:"size"`
	// Resource tags as a key-value map. Values must be non-empty (server's PATCH returns 400 on omitted value). Set `tags = {}` to clear all tags; omit the attribute to preserve the prior value.
	Tags map[string]string `pulumi:"tags"`
}

// The set of arguments for constructing a PostgresService resource.
type PostgresServiceArgs struct {
	// Cloud provider hosting the instance. Currently only 'aws' is supported. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
	CloudProvider pulumi.StringPtrInput
	// High-availability mode. One of 'none' (single replica), 'async' (asynchronous replica), or 'sync' (synchronous replica). Mutable post-create; an HA flip triggers a transition. Omitting the attribute preserves the prior value (the server defaults to 'none' on Create); to actively downgrade, set 'ha_type = "none"' explicitly. Omit for a read replica or point-in-time restore (inherited from the source).
	HaType pulumi.StringPtrInput
	// Human-readable name. Immutable post-create; changes force destroy-and-recreate. Differs from clickhouse_service, which allows in-place rename.
	Name pulumi.StringPtrInput
	// Superuser password. Optional: set it to manage the password in Terraform, or omit it and the server generates one. Computed and refreshed from each GET (the server echoes it), so it always reflects the live password and an out-of-band rotation is reconciled on the next refresh. Changing this value rotates the password (PATCH /password). Must be ≥12 chars with at least one lowercase, one uppercase, and one digit. Stored in (sensitive) state.
	Password pulumi.StringPtrInput
	// Postgres server parameters (pgConfig) as a key-value map. Declared parameters are the desired state — every apply sends the full map via POST /config (full replacement), so removing a key from the map removes it server-side. Set `pgConfig = {}` to clear all parameters; omit the attribute to preserve the prior state (read replicas inherit the primary's parameters, and the server may surface values the configuration never declared — so it is Optional+Computed like tags). Out-of-band changes are reverted on the next apply. Some parameters require a database restart; the provider surfaces the server's restart-required hint as a warning (restart out-of-band).
	PgConfig pulumi.StringMapInput
	// PgBouncer connection-pooler parameters (pgBouncerConfig) as a key-value map. Same Optional+Computed semantics as pg_config; set `pgbouncerConfig = {}` to clear.
	PgbouncerConfig pulumi.StringMapInput
	// Major Postgres version (e.g. '18'). The server picks the patch release within that major. Changing the major triggers destroy-and-recreate. Omit for a read replica or point-in-time restore (inherited from the source).
	PostgresVersion pulumi.StringPtrInput
	// ID of the primary instance to replicate. When set, this instance is created as a read replica (streaming replication) of that primary. Immutable for a live replica: changing or removing it destroys and recreates the instance as a standalone primary. The one exception is an out-of-band promotion — if you promote the replica via the API/UI (is*primary becomes true), changing or removing read*replica*of then reconciles state in place without destroying the promoted primary. Mutually exclusive with restore*to*point*in_time and with password (a replica inherits the primary's superuser).
	ReadReplicaOf pulumi.StringPtrInput
	// Cloud region (e.g. 'us-east-1'). No client-side validation; the server rejects unsupported regions. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
	Region pulumi.StringPtrInput
	// Create this instance by restoring another Postgres instance's backup to a point in time. The whole block is create-time only: changing source*id / restore*target (re-restore to a new point) OR removing it both destroy and recreate the instance. The restored instance's name is this resource's top-level `name` and it is independent of its source. cloud*provider / region / postgres*version are inherited from the source — omit them, or set them to match (a mismatch is a plan-time error); size and ha*type must be omitted (the restored instance comes up at the backup's size and a server-assigned HA mode). Mutually exclusive with read*replica*of.
	RestoreToPointInTime PostgresServiceRestoreToPointInTimePtrInput
	// Instance size (VM SKU). See https://clickhouse.com/docs/cloud/managed-postgres/scaling for the supported instance families. No client-side enum; the server rejects unsupported sizes with HTTP 400 at apply time. Resizable in place. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
	Size pulumi.StringPtrInput
	// Resource tags as a key-value map. Values must be non-empty (server's PATCH returns 400 on omitted value). Set `tags = {}` to clear all tags; omit the attribute to preserve the prior value.
	Tags pulumi.StringMapInput
}

func (PostgresServiceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*postgresServiceArgs)(nil)).Elem()
}

type PostgresServiceInput interface {
	pulumi.Input

	ToPostgresServiceOutput() PostgresServiceOutput
	ToPostgresServiceOutputWithContext(ctx context.Context) PostgresServiceOutput
}

func (*PostgresService) ElementType() reflect.Type {
	return reflect.TypeOf((**PostgresService)(nil)).Elem()
}

func (i *PostgresService) ToPostgresServiceOutput() PostgresServiceOutput {
	return i.ToPostgresServiceOutputWithContext(context.Background())
}

func (i *PostgresService) ToPostgresServiceOutputWithContext(ctx context.Context) PostgresServiceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PostgresServiceOutput)
}

// PostgresServiceArrayInput is an input type that accepts PostgresServiceArray and PostgresServiceArrayOutput values.
// You can construct a concrete instance of `PostgresServiceArrayInput` via:
//
//	PostgresServiceArray{ PostgresServiceArgs{...} }
type PostgresServiceArrayInput interface {
	pulumi.Input

	ToPostgresServiceArrayOutput() PostgresServiceArrayOutput
	ToPostgresServiceArrayOutputWithContext(context.Context) PostgresServiceArrayOutput
}

type PostgresServiceArray []PostgresServiceInput

func (PostgresServiceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PostgresService)(nil)).Elem()
}

func (i PostgresServiceArray) ToPostgresServiceArrayOutput() PostgresServiceArrayOutput {
	return i.ToPostgresServiceArrayOutputWithContext(context.Background())
}

func (i PostgresServiceArray) ToPostgresServiceArrayOutputWithContext(ctx context.Context) PostgresServiceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PostgresServiceArrayOutput)
}

// PostgresServiceMapInput is an input type that accepts PostgresServiceMap and PostgresServiceMapOutput values.
// You can construct a concrete instance of `PostgresServiceMapInput` via:
//
//	PostgresServiceMap{ "key": PostgresServiceArgs{...} }
type PostgresServiceMapInput interface {
	pulumi.Input

	ToPostgresServiceMapOutput() PostgresServiceMapOutput
	ToPostgresServiceMapOutputWithContext(context.Context) PostgresServiceMapOutput
}

type PostgresServiceMap map[string]PostgresServiceInput

func (PostgresServiceMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PostgresService)(nil)).Elem()
}

func (i PostgresServiceMap) ToPostgresServiceMapOutput() PostgresServiceMapOutput {
	return i.ToPostgresServiceMapOutputWithContext(context.Background())
}

func (i PostgresServiceMap) ToPostgresServiceMapOutputWithContext(ctx context.Context) PostgresServiceMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PostgresServiceMapOutput)
}

type PostgresServiceOutput struct{ *pulumi.OutputState }

func (PostgresServiceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PostgresService)(nil)).Elem()
}

func (o PostgresServiceOutput) ToPostgresServiceOutput() PostgresServiceOutput {
	return o
}

func (o PostgresServiceOutput) ToPostgresServiceOutputWithContext(ctx context.Context) PostgresServiceOutput {
	return o
}

// Cloud provider hosting the instance. Currently only 'aws' is supported. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
func (o PostgresServiceOutput) CloudProvider() pulumi.StringOutput {
	return o.ApplyT(func(v *PostgresService) pulumi.StringOutput { return v.CloudProvider }).(pulumi.StringOutput)
}

// Full connection URI embedding the username and the password. Marked sensitive; the secret-redaction layer also covers it in TF_LOG=DEBUG output. Plan stability is managed in ModifyPlan: pinned to the prior value on unrelated updates, marked unknown when a password rotation is planned (it embeds the password).
func (o PostgresServiceOutput) ConnectionString() pulumi.StringOutput {
	return o.ApplyT(func(v *PostgresService) pulumi.StringOutput { return v.ConnectionString }).(pulumi.StringOutput)
}

// RFC3339 timestamp when the service was created.
func (o PostgresServiceOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *PostgresService) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// High-availability mode. One of 'none' (single replica), 'async' (asynchronous replica), or 'sync' (synchronous replica). Mutable post-create; an HA flip triggers a transition. Omitting the attribute preserves the prior value (the server defaults to 'none' on Create); to actively downgrade, set 'ha_type = "none"' explicitly. Omit for a read replica or point-in-time restore (inherited from the source).
func (o PostgresServiceOutput) HaType() pulumi.StringOutput {
	return o.ApplyT(func(v *PostgresService) pulumi.StringOutput { return v.HaType }).(pulumi.StringOutput)
}

// Network hostname for client connections.
func (o PostgresServiceOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v *PostgresService) pulumi.StringOutput { return v.Hostname }).(pulumi.StringOutput)
}

// True when this instance is a writeable primary cluster; false only for separately-provisioned read replicas. HA standby servers (`haType = async`/`sync`) live inside the same primary instance and don't affect this value.
func (o PostgresServiceOutput) IsPrimary() pulumi.BoolOutput {
	return o.ApplyT(func(v *PostgresService) pulumi.BoolOutput { return v.IsPrimary }).(pulumi.BoolOutput)
}

// Human-readable name. Immutable post-create; changes force destroy-and-recreate. Differs from clickhouse_service, which allows in-place rename.
func (o PostgresServiceOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *PostgresService) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Superuser password. Optional: set it to manage the password in Terraform, or omit it and the server generates one. Computed and refreshed from each GET (the server echoes it), so it always reflects the live password and an out-of-band rotation is reconciled on the next refresh. Changing this value rotates the password (PATCH /password). Must be ≥12 chars with at least one lowercase, one uppercase, and one digit. Stored in (sensitive) state.
func (o PostgresServiceOutput) Password() pulumi.StringOutput {
	return o.ApplyT(func(v *PostgresService) pulumi.StringOutput { return v.Password }).(pulumi.StringOutput)
}

// Postgres server parameters (pgConfig) as a key-value map. Declared parameters are the desired state — every apply sends the full map via POST /config (full replacement), so removing a key from the map removes it server-side. Set `pgConfig = {}` to clear all parameters; omit the attribute to preserve the prior state (read replicas inherit the primary's parameters, and the server may surface values the configuration never declared — so it is Optional+Computed like tags). Out-of-band changes are reverted on the next apply. Some parameters require a database restart; the provider surfaces the server's restart-required hint as a warning (restart out-of-band).
func (o PostgresServiceOutput) PgConfig() pulumi.StringMapOutput {
	return o.ApplyT(func(v *PostgresService) pulumi.StringMapOutput { return v.PgConfig }).(pulumi.StringMapOutput)
}

// PgBouncer connection-pooler parameters (pgBouncerConfig) as a key-value map. Same Optional+Computed semantics as pg_config; set `pgbouncerConfig = {}` to clear.
func (o PostgresServiceOutput) PgbouncerConfig() pulumi.StringMapOutput {
	return o.ApplyT(func(v *PostgresService) pulumi.StringMapOutput { return v.PgbouncerConfig }).(pulumi.StringMapOutput)
}

// TCP port for client connections. Hardcoded to 5432 today; will become server-supplied once the API exposes a per-instance port field.
func (o PostgresServiceOutput) Port() pulumi.IntOutput {
	return o.ApplyT(func(v *PostgresService) pulumi.IntOutput { return v.Port }).(pulumi.IntOutput)
}

// Major Postgres version (e.g. '18'). The server picks the patch release within that major. Changing the major triggers destroy-and-recreate. Omit for a read replica or point-in-time restore (inherited from the source).
func (o PostgresServiceOutput) PostgresVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *PostgresService) pulumi.StringOutput { return v.PostgresVersion }).(pulumi.StringOutput)
}

// ID of the primary instance to replicate. When set, this instance is created as a read replica (streaming replication) of that primary. Immutable for a live replica: changing or removing it destroys and recreates the instance as a standalone primary. The one exception is an out-of-band promotion — if you promote the replica via the API/UI (is*primary becomes true), changing or removing read*replica*of then reconciles state in place without destroying the promoted primary. Mutually exclusive with restore*to*point*in_time and with password (a replica inherits the primary's superuser).
func (o PostgresServiceOutput) ReadReplicaOf() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PostgresService) pulumi.StringPtrOutput { return v.ReadReplicaOf }).(pulumi.StringPtrOutput)
}

// Cloud region (e.g. 'us-east-1'). No client-side validation; the server rejects unsupported regions. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
func (o PostgresServiceOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *PostgresService) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

// Create this instance by restoring another Postgres instance's backup to a point in time. The whole block is create-time only: changing source*id / restore*target (re-restore to a new point) OR removing it both destroy and recreate the instance. The restored instance's name is this resource's top-level `name` and it is independent of its source. cloud*provider / region / postgres*version are inherited from the source — omit them, or set them to match (a mismatch is a plan-time error); size and ha*type must be omitted (the restored instance comes up at the backup's size and a server-assigned HA mode). Mutually exclusive with read*replica*of.
func (o PostgresServiceOutput) RestoreToPointInTime() PostgresServiceRestoreToPointInTimePtrOutput {
	return o.ApplyT(func(v *PostgresService) PostgresServiceRestoreToPointInTimePtrOutput { return v.RestoreToPointInTime }).(PostgresServiceRestoreToPointInTimePtrOutput)
}

// Instance size (VM SKU). See https://clickhouse.com/docs/cloud/managed-postgres/scaling for the supported instance families. No client-side enum; the server rejects unsupported sizes with HTTP 400 at apply time. Resizable in place. Required for a standard create; omit for a read replica or point-in-time restore (inherited from the source).
func (o PostgresServiceOutput) Size() pulumi.StringOutput {
	return o.ApplyT(func(v *PostgresService) pulumi.StringOutput { return v.Size }).(pulumi.StringOutput)
}

// Server-reported state. Examples: 'creating', 'running', 'restarting', 'unavailable', 'deleting'. Forward-compatible: unknown values from the server are surfaced verbatim.
func (o PostgresServiceOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *PostgresService) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

// Resource tags as a key-value map. Values must be non-empty (server's PATCH returns 400 on omitted value). Set `tags = {}` to clear all tags; omit the attribute to preserve the prior value.
func (o PostgresServiceOutput) Tags() pulumi.StringMapOutput {
	return o.ApplyT(func(v *PostgresService) pulumi.StringMapOutput { return v.Tags }).(pulumi.StringMapOutput)
}

// Default superuser name.
func (o PostgresServiceOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v *PostgresService) pulumi.StringOutput { return v.Username }).(pulumi.StringOutput)
}

type PostgresServiceArrayOutput struct{ *pulumi.OutputState }

func (PostgresServiceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PostgresService)(nil)).Elem()
}

func (o PostgresServiceArrayOutput) ToPostgresServiceArrayOutput() PostgresServiceArrayOutput {
	return o
}

func (o PostgresServiceArrayOutput) ToPostgresServiceArrayOutputWithContext(ctx context.Context) PostgresServiceArrayOutput {
	return o
}

func (o PostgresServiceArrayOutput) Index(i pulumi.IntInput) PostgresServiceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *PostgresService {
		return vs[0].([]*PostgresService)[vs[1].(int)]
	}).(PostgresServiceOutput)
}

type PostgresServiceMapOutput struct{ *pulumi.OutputState }

func (PostgresServiceMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PostgresService)(nil)).Elem()
}

func (o PostgresServiceMapOutput) ToPostgresServiceMapOutput() PostgresServiceMapOutput {
	return o
}

func (o PostgresServiceMapOutput) ToPostgresServiceMapOutputWithContext(ctx context.Context) PostgresServiceMapOutput {
	return o
}

func (o PostgresServiceMapOutput) MapIndex(k pulumi.StringInput) PostgresServiceOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *PostgresService {
		return vs[0].(map[string]*PostgresService)[vs[1].(string)]
	}).(PostgresServiceOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PostgresServiceInput)(nil)).Elem(), &PostgresService{})
	pulumi.RegisterInputType(reflect.TypeOf((*PostgresServiceArrayInput)(nil)).Elem(), PostgresServiceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PostgresServiceMapInput)(nil)).Elem(), PostgresServiceMap{})
	pulumi.RegisterOutputType(PostgresServiceOutput{})
	pulumi.RegisterOutputType(PostgresServiceArrayOutput{})
	pulumi.RegisterOutputType(PostgresServiceMapOutput{})
}
