# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'ServiceBackupConfigurationArgs',
    'ServiceBackupConfigurationArgsDict',
    'ServiceEndpointsArgs',
    'ServiceEndpointsArgsDict',
    'ServiceEndpointsHttpsArgs',
    'ServiceEndpointsHttpsArgsDict',
    'ServiceEndpointsMysqlArgs',
    'ServiceEndpointsMysqlArgsDict',
    'ServiceEndpointsNativesecureArgs',
    'ServiceEndpointsNativesecureArgsDict',
    'ServiceIpAccessArgs',
    'ServiceIpAccessArgsDict',
    'ServicePrivateEndpointConfigArgs',
    'ServicePrivateEndpointConfigArgsDict',
    'ServiceQueryApiEndpointsArgs',
    'ServiceQueryApiEndpointsArgsDict',
    'ServiceTransparentDataEncryptionArgs',
    'ServiceTransparentDataEncryptionArgsDict',
]

class ServiceBackupConfigurationArgsDict(TypedDict):
    backup_period_in_hours: NotRequired[pulumi.Input[_builtins.int]]
    """
    Interval in hours between each backup.
    """
    backup_retention_period_in_hours: NotRequired[pulumi.Input[_builtins.int]]
    """
    How long in hours to keep a backup before deleting it.
    """
    backup_start_time: NotRequired[pulumi.Input[_builtins.str]]
    """
    Time of the day in UTC that indicates the start time of a 2 hours window to be used for backup. If set, backup*period*in_hours must be null and backups are created once a day.
    """

@pulumi.input_type
class ServiceBackupConfigurationArgs:
    def __init__(__self__, *,
                 backup_period_in_hours: Optional[pulumi.Input[_builtins.int]] = None,
                 backup_retention_period_in_hours: Optional[pulumi.Input[_builtins.int]] = None,
                 backup_start_time: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.int] backup_period_in_hours: Interval in hours between each backup.
        :param pulumi.Input[_builtins.int] backup_retention_period_in_hours: How long in hours to keep a backup before deleting it.
        :param pulumi.Input[_builtins.str] backup_start_time: Time of the day in UTC that indicates the start time of a 2 hours window to be used for backup. If set, backup*period*in_hours must be null and backups are created once a day.
        """
        if backup_period_in_hours is not None:
            pulumi.set(__self__, "backup_period_in_hours", backup_period_in_hours)
        if backup_retention_period_in_hours is not None:
            pulumi.set(__self__, "backup_retention_period_in_hours", backup_retention_period_in_hours)
        if backup_start_time is not None:
            pulumi.set(__self__, "backup_start_time", backup_start_time)

    @_builtins.property
    @pulumi.getter(name="backupPeriodInHours")
    def backup_period_in_hours(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Interval in hours between each backup.
        """
        return pulumi.get(self, "backup_period_in_hours")

    @backup_period_in_hours.setter
    def backup_period_in_hours(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "backup_period_in_hours", value)

    @_builtins.property
    @pulumi.getter(name="backupRetentionPeriodInHours")
    def backup_retention_period_in_hours(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        How long in hours to keep a backup before deleting it.
        """
        return pulumi.get(self, "backup_retention_period_in_hours")

    @backup_retention_period_in_hours.setter
    def backup_retention_period_in_hours(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "backup_retention_period_in_hours", value)

    @_builtins.property
    @pulumi.getter(name="backupStartTime")
    def backup_start_time(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Time of the day in UTC that indicates the start time of a 2 hours window to be used for backup. If set, backup*period*in_hours must be null and backups are created once a day.
        """
        return pulumi.get(self, "backup_start_time")

    @backup_start_time.setter
    def backup_start_time(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "backup_start_time", value)


class ServiceEndpointsArgsDict(TypedDict):
    https: NotRequired[pulumi.Input['ServiceEndpointsHttpsArgsDict']]
    mysql: NotRequired[pulumi.Input['ServiceEndpointsMysqlArgsDict']]
    nativesecure: NotRequired[pulumi.Input['ServiceEndpointsNativesecureArgsDict']]

@pulumi.input_type
class ServiceEndpointsArgs:
    def __init__(__self__, *,
                 https: Optional[pulumi.Input['ServiceEndpointsHttpsArgs']] = None,
                 mysql: Optional[pulumi.Input['ServiceEndpointsMysqlArgs']] = None,
                 nativesecure: Optional[pulumi.Input['ServiceEndpointsNativesecureArgs']] = None):
        if https is not None:
            pulumi.set(__self__, "https", https)
        if mysql is not None:
            pulumi.set(__self__, "mysql", mysql)
        if nativesecure is not None:
            pulumi.set(__self__, "nativesecure", nativesecure)

    @_builtins.property
    @pulumi.getter
    def https(self) -> Optional[pulumi.Input['ServiceEndpointsHttpsArgs']]:
        return pulumi.get(self, "https")

    @https.setter
    def https(self, value: Optional[pulumi.Input['ServiceEndpointsHttpsArgs']]):
        pulumi.set(self, "https", value)

    @_builtins.property
    @pulumi.getter
    def mysql(self) -> Optional[pulumi.Input['ServiceEndpointsMysqlArgs']]:
        return pulumi.get(self, "mysql")

    @mysql.setter
    def mysql(self, value: Optional[pulumi.Input['ServiceEndpointsMysqlArgs']]):
        pulumi.set(self, "mysql", value)

    @_builtins.property
    @pulumi.getter
    def nativesecure(self) -> Optional[pulumi.Input['ServiceEndpointsNativesecureArgs']]:
        return pulumi.get(self, "nativesecure")

    @nativesecure.setter
    def nativesecure(self, value: Optional[pulumi.Input['ServiceEndpointsNativesecureArgs']]):
        pulumi.set(self, "nativesecure", value)


class ServiceEndpointsHttpsArgsDict(TypedDict):
    host: NotRequired[pulumi.Input[_builtins.str]]
    """
    Endpoint host.
    """
    port: NotRequired[pulumi.Input[_builtins.int]]
    """
    Endpoint port.
    """

@pulumi.input_type
class ServiceEndpointsHttpsArgs:
    def __init__(__self__, *,
                 host: Optional[pulumi.Input[_builtins.str]] = None,
                 port: Optional[pulumi.Input[_builtins.int]] = None):
        """
        :param pulumi.Input[_builtins.str] host: Endpoint host.
        :param pulumi.Input[_builtins.int] port: Endpoint port.
        """
        if host is not None:
            pulumi.set(__self__, "host", host)
        if port is not None:
            pulumi.set(__self__, "port", port)

    @_builtins.property
    @pulumi.getter
    def host(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Endpoint host.
        """
        return pulumi.get(self, "host")

    @host.setter
    def host(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "host", value)

    @_builtins.property
    @pulumi.getter
    def port(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Endpoint port.
        """
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "port", value)


class ServiceEndpointsMysqlArgsDict(TypedDict):
    enabled: pulumi.Input[_builtins.bool]
    """
    Wether to enable the mysql endpoint or not.
    """
    host: NotRequired[pulumi.Input[_builtins.str]]
    """
    Endpoint host.
    """
    port: NotRequired[pulumi.Input[_builtins.int]]
    """
    Endpoint port.
    """

@pulumi.input_type
class ServiceEndpointsMysqlArgs:
    def __init__(__self__, *,
                 enabled: pulumi.Input[_builtins.bool],
                 host: Optional[pulumi.Input[_builtins.str]] = None,
                 port: Optional[pulumi.Input[_builtins.int]] = None):
        """
        :param pulumi.Input[_builtins.bool] enabled: Wether to enable the mysql endpoint or not.
        :param pulumi.Input[_builtins.str] host: Endpoint host.
        :param pulumi.Input[_builtins.int] port: Endpoint port.
        """
        pulumi.set(__self__, "enabled", enabled)
        if host is not None:
            pulumi.set(__self__, "host", host)
        if port is not None:
            pulumi.set(__self__, "port", port)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Input[_builtins.bool]:
        """
        Wether to enable the mysql endpoint or not.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: pulumi.Input[_builtins.bool]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter
    def host(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Endpoint host.
        """
        return pulumi.get(self, "host")

    @host.setter
    def host(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "host", value)

    @_builtins.property
    @pulumi.getter
    def port(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Endpoint port.
        """
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "port", value)


class ServiceEndpointsNativesecureArgsDict(TypedDict):
    host: NotRequired[pulumi.Input[_builtins.str]]
    """
    Endpoint host.
    """
    port: NotRequired[pulumi.Input[_builtins.int]]
    """
    Endpoint port.
    """

@pulumi.input_type
class ServiceEndpointsNativesecureArgs:
    def __init__(__self__, *,
                 host: Optional[pulumi.Input[_builtins.str]] = None,
                 port: Optional[pulumi.Input[_builtins.int]] = None):
        """
        :param pulumi.Input[_builtins.str] host: Endpoint host.
        :param pulumi.Input[_builtins.int] port: Endpoint port.
        """
        if host is not None:
            pulumi.set(__self__, "host", host)
        if port is not None:
            pulumi.set(__self__, "port", port)

    @_builtins.property
    @pulumi.getter
    def host(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Endpoint host.
        """
        return pulumi.get(self, "host")

    @host.setter
    def host(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "host", value)

    @_builtins.property
    @pulumi.getter
    def port(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Endpoint port.
        """
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "port", value)


class ServiceIpAccessArgsDict(TypedDict):
    description: pulumi.Input[_builtins.str]
    """
    Description of the IP address.
    """
    source: pulumi.Input[_builtins.str]
    """
    IP address allowed to access the service. In case you want to set the ip_access to anywhere you should set source to 0.0.0.0/0
    """

@pulumi.input_type
class ServiceIpAccessArgs:
    def __init__(__self__, *,
                 description: pulumi.Input[_builtins.str],
                 source: pulumi.Input[_builtins.str]):
        """
        :param pulumi.Input[_builtins.str] description: Description of the IP address.
        :param pulumi.Input[_builtins.str] source: IP address allowed to access the service. In case you want to set the ip_access to anywhere you should set source to 0.0.0.0/0
        """
        pulumi.set(__self__, "description", description)
        pulumi.set(__self__, "source", source)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[_builtins.str]:
        """
        Description of the IP address.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Input[_builtins.str]:
        """
        IP address allowed to access the service. In case you want to set the ip_access to anywhere you should set source to 0.0.0.0/0
        """
        return pulumi.get(self, "source")

    @source.setter
    def source(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "source", value)


class ServicePrivateEndpointConfigArgsDict(TypedDict):
    endpoint_service_id: NotRequired[pulumi.Input[_builtins.str]]
    """
    Unique identifier of the interface endpoint you created in your VPC with the AWS(Service Name) or GCP(Target Service) resource.
    """
    private_dns_hostname: NotRequired[pulumi.Input[_builtins.str]]
    """
    Private DNS Hostname of the VPC you created.
    """

@pulumi.input_type
class ServicePrivateEndpointConfigArgs:
    def __init__(__self__, *,
                 endpoint_service_id: Optional[pulumi.Input[_builtins.str]] = None,
                 private_dns_hostname: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] endpoint_service_id: Unique identifier of the interface endpoint you created in your VPC with the AWS(Service Name) or GCP(Target Service) resource.
        :param pulumi.Input[_builtins.str] private_dns_hostname: Private DNS Hostname of the VPC you created.
        """
        if endpoint_service_id is not None:
            pulumi.set(__self__, "endpoint_service_id", endpoint_service_id)
        if private_dns_hostname is not None:
            pulumi.set(__self__, "private_dns_hostname", private_dns_hostname)

    @_builtins.property
    @pulumi.getter(name="endpointServiceId")
    def endpoint_service_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Unique identifier of the interface endpoint you created in your VPC with the AWS(Service Name) or GCP(Target Service) resource.
        """
        return pulumi.get(self, "endpoint_service_id")

    @endpoint_service_id.setter
    def endpoint_service_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "endpoint_service_id", value)

    @_builtins.property
    @pulumi.getter(name="privateDnsHostname")
    def private_dns_hostname(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Private DNS Hostname of the VPC you created.
        """
        return pulumi.get(self, "private_dns_hostname")

    @private_dns_hostname.setter
    def private_dns_hostname(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "private_dns_hostname", value)


class ServiceQueryApiEndpointsArgsDict(TypedDict):
    api_key_ids: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]
    """
    The UUIDs of the API Keys to grant access to the query API.
    """
    roles: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]
    """
    The Database role that will be used to run the query.
    """
    allowed_origins: NotRequired[pulumi.Input[_builtins.str]]
    """
    Comma separated list of domain names to be allowed cross-origin resource sharing (CORS) access to the query API. Leave this field empty to restrict access to backend servers only
    """

@pulumi.input_type
class ServiceQueryApiEndpointsArgs:
    def __init__(__self__, *,
                 api_key_ids: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 roles: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 allowed_origins: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] api_key_ids: The UUIDs of the API Keys to grant access to the query API.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] roles: The Database role that will be used to run the query.
        :param pulumi.Input[_builtins.str] allowed_origins: Comma separated list of domain names to be allowed cross-origin resource sharing (CORS) access to the query API. Leave this field empty to restrict access to backend servers only
        """
        pulumi.set(__self__, "api_key_ids", api_key_ids)
        pulumi.set(__self__, "roles", roles)
        if allowed_origins is not None:
            pulumi.set(__self__, "allowed_origins", allowed_origins)

    @_builtins.property
    @pulumi.getter(name="apiKeyIds")
    def api_key_ids(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        The UUIDs of the API Keys to grant access to the query API.
        """
        return pulumi.get(self, "api_key_ids")

    @api_key_ids.setter
    def api_key_ids(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "api_key_ids", value)

    @_builtins.property
    @pulumi.getter
    def roles(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        The Database role that will be used to run the query.
        """
        return pulumi.get(self, "roles")

    @roles.setter
    def roles(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "roles", value)

    @_builtins.property
    @pulumi.getter(name="allowedOrigins")
    def allowed_origins(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Comma separated list of domain names to be allowed cross-origin resource sharing (CORS) access to the query API. Leave this field empty to restrict access to backend servers only
        """
        return pulumi.get(self, "allowed_origins")

    @allowed_origins.setter
    def allowed_origins(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "allowed_origins", value)


class ServiceTransparentDataEncryptionArgsDict(TypedDict):
    enabled: NotRequired[pulumi.Input[_builtins.bool]]
    """
    If true, TDE is enabled for the service.
    """
    role_id: NotRequired[pulumi.Input[_builtins.str]]
    """
    ID of Role to be used for granting access to the Encryption Key. This is an ARN for AWS services and a Service Account Identifier for GCP.
    """

@pulumi.input_type
class ServiceTransparentDataEncryptionArgs:
    def __init__(__self__, *,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 role_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.bool] enabled: If true, TDE is enabled for the service.
        :param pulumi.Input[_builtins.str] role_id: ID of Role to be used for granting access to the Encryption Key. This is an ARN for AWS services and a Service Account Identifier for GCP.
        """
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if role_id is not None:
            pulumi.set(__self__, "role_id", role_id)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        If true, TDE is enabled for the service.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="roleId")
    def role_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        ID of Role to be used for granting access to the Encryption Key. This is an ARN for AWS services and a Service Account Identifier for GCP.
        """
        return pulumi.get(self, "role_id")

    @role_id.setter
    def role_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "role_id", value)


