# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetRoleResult',
    'AwaitableGetRoleResult',
    'get_role',
    'get_role_output',
]

@pulumi.output_type
class GetRoleResult:
    """
    A collection of values returned by getRole.
    """
    def __init__(__self__, actors=None, created_at=None, id=None, name=None, owner_id=None, policies=None, tenant_id=None, type=None, updated_at=None):
        if actors and not isinstance(actors, list):
            raise TypeError("Expected argument 'actors' to be a list")
        pulumi.set(__self__, "actors", actors)
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if owner_id and not isinstance(owner_id, str):
            raise TypeError("Expected argument 'owner_id' to be a str")
        pulumi.set(__self__, "owner_id", owner_id)
        if policies and not isinstance(policies, list):
            raise TypeError("Expected argument 'policies' to be a list")
        pulumi.set(__self__, "policies", policies)
        if tenant_id and not isinstance(tenant_id, str):
            raise TypeError("Expected argument 'tenant_id' to be a str")
        pulumi.set(__self__, "tenant_id", tenant_id)
        if type and not isinstance(type, str):
            raise TypeError("Expected argument 'type' to be a str")
        pulumi.set(__self__, "type", type)
        if updated_at and not isinstance(updated_at, str):
            raise TypeError("Expected argument 'updated_at' to be a str")
        pulumi.set(__self__, "updated_at", updated_at)

    @_builtins.property
    @pulumi.getter
    def actors(self) -> Sequence[_builtins.str]:
        """
        List of actors assigned to this role.
        """
        return pulumi.get(self, "actors")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> _builtins.str:
        """
        Timestamp when the role was created.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        Unique identifier of the role. Exactly one of id or name must be set.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        Name of the role to look up. Exactly one of id or name must be set.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="ownerId")
    def owner_id(self) -> _builtins.str:
        """
        Owner ID of this role.
        """
        return pulumi.get(self, "owner_id")

    @_builtins.property
    @pulumi.getter
    def policies(self) -> Sequence['outputs.GetRolePolicyResult']:
        """
        List of policies attached to this role.
        """
        return pulumi.get(self, "policies")

    @_builtins.property
    @pulumi.getter(name="tenantId")
    def tenant_id(self) -> _builtins.str:
        """
        Tenant ID that owns this role.
        """
        return pulumi.get(self, "tenant_id")

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        """
        Type of the role: 'system' or 'custom'.
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> _builtins.str:
        """
        Timestamp when the role was last updated.
        """
        return pulumi.get(self, "updated_at")


class AwaitableGetRoleResult(GetRoleResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetRoleResult(
            actors=self.actors,
            created_at=self.created_at,
            id=self.id,
            name=self.name,
            owner_id=self.owner_id,
            policies=self.policies,
            tenant_id=self.tenant_id,
            type=self.type,
            updated_at=self.updated_at)


def get_role(id: Optional[_builtins.str] = None,
             name: Optional[_builtins.str] = None,
             opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetRoleResult:
    """
    Use this data source to look up a single RBAC role by ID or name. Exactly one of `id` or `name` must be set.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_clickhouse as clickhouse

    # Look up a system role by name
    admin = clickhouse.get_role(name="Admin")
    # Look up a custom role by ID
    custom = clickhouse.get_role(id="47f0b035-d6ca-4600-8c69-9955551857e5")
    ```


    :param _builtins.str id: Unique identifier of the role. Exactly one of id or name must be set.
    :param _builtins.str name: Name of the role to look up. Exactly one of id or name must be set.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('clickhouse:index/getRole:getRole', __args__, opts=opts, typ=GetRoleResult).value

    return AwaitableGetRoleResult(
        actors=pulumi.get(__ret__, 'actors'),
        created_at=pulumi.get(__ret__, 'created_at'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        owner_id=pulumi.get(__ret__, 'owner_id'),
        policies=pulumi.get(__ret__, 'policies'),
        tenant_id=pulumi.get(__ret__, 'tenant_id'),
        type=pulumi.get(__ret__, 'type'),
        updated_at=pulumi.get(__ret__, 'updated_at'))
def get_role_output(id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                    name: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetRoleResult]:
    """
    Use this data source to look up a single RBAC role by ID or name. Exactly one of `id` or `name` must be set.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_clickhouse as clickhouse

    # Look up a system role by name
    admin = clickhouse.get_role(name="Admin")
    # Look up a custom role by ID
    custom = clickhouse.get_role(id="47f0b035-d6ca-4600-8c69-9955551857e5")
    ```


    :param _builtins.str id: Unique identifier of the role. Exactly one of id or name must be set.
    :param _builtins.str name: Name of the role to look up. Exactly one of id or name must be set.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('clickhouse:index/getRole:getRole', __args__, opts=opts, typ=GetRoleResult)
    return __ret__.apply(lambda __response__: GetRoleResult(
        actors=pulumi.get(__response__, 'actors'),
        created_at=pulumi.get(__response__, 'created_at'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        owner_id=pulumi.get(__response__, 'owner_id'),
        policies=pulumi.get(__response__, 'policies'),
        tenant_id=pulumi.get(__response__, 'tenant_id'),
        type=pulumi.get(__response__, 'type'),
        updated_at=pulumi.get(__response__, 'updated_at')))
