# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetPostgresServiceCaCertificatesResult',
    'AwaitableGetPostgresServiceCaCertificatesResult',
    'get_postgres_service_ca_certificates',
    'get_postgres_service_ca_certificates_output',
]

@pulumi.output_type
class GetPostgresServiceCaCertificatesResult:
    """
    A collection of values returned by getPostgresServiceCaCertificates.
    """
    def __init__(__self__, certificate=None, id=None, service_id=None):
        if certificate and not isinstance(certificate, str):
            raise TypeError("Expected argument 'certificate' to be a str")
        pulumi.set(__self__, "certificate", certificate)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if service_id and not isinstance(service_id, str):
            raise TypeError("Expected argument 'service_id' to be a str")
        pulumi.set(__self__, "service_id", service_id)

    @_builtins.property
    @pulumi.getter
    def certificate(self) -> _builtins.str:
        """
        PEM-encoded CA certificate chain.
        """
        return pulumi.get(self, "certificate")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="serviceId")
    def service_id(self) -> _builtins.str:
        """
        ID of the Postgres service whose CA certificate chain to fetch.
        """
        return pulumi.get(self, "service_id")


class AwaitableGetPostgresServiceCaCertificatesResult(GetPostgresServiceCaCertificatesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetPostgresServiceCaCertificatesResult(
            certificate=self.certificate,
            id=self.id,
            service_id=self.service_id)


def get_postgres_service_ca_certificates(service_id: Optional[_builtins.str] = None,
                                         opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetPostgresServiceCaCertificatesResult:
    """
    > **Note:** This data source is in alpha and its behavior may change in future provider versions.

    Fetches the PEM-encoded CA certificate chain for a
    [ClickHouse Cloud Managed Postgres](https://clickhouse.com/cloud/postgres)
    service. Use it to pin the CA when connecting with `sslmode=verify-full`.

    Input `service_id`; output `certificate` (the PEM chain).


    :param _builtins.str service_id: ID of the Postgres service whose CA certificate chain to fetch.
    """
    __args__ = dict()
    __args__['serviceId'] = service_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('clickhouse:index/getPostgresServiceCaCertificates:getPostgresServiceCaCertificates', __args__, opts=opts, typ=GetPostgresServiceCaCertificatesResult).value

    return AwaitableGetPostgresServiceCaCertificatesResult(
        certificate=pulumi.get(__ret__, 'certificate'),
        id=pulumi.get(__ret__, 'id'),
        service_id=pulumi.get(__ret__, 'service_id'))
def get_postgres_service_ca_certificates_output(service_id: pulumi.Input[Optional[_builtins.str]] = None,
                                                opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetPostgresServiceCaCertificatesResult]:
    """
    > **Note:** This data source is in alpha and its behavior may change in future provider versions.

    Fetches the PEM-encoded CA certificate chain for a
    [ClickHouse Cloud Managed Postgres](https://clickhouse.com/cloud/postgres)
    service. Use it to pin the CA when connecting with `sslmode=verify-full`.

    Input `service_id`; output `certificate` (the PEM chain).


    :param _builtins.str service_id: ID of the Postgres service whose CA certificate chain to fetch.
    """
    __args__ = dict()
    __args__['serviceId'] = service_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('clickhouse:index/getPostgresServiceCaCertificates:getPostgresServiceCaCertificates', __args__, opts=opts, typ=GetPostgresServiceCaCertificatesResult)
    return __ret__.apply(lambda __response__: GetPostgresServiceCaCertificatesResult(
        certificate=pulumi.get(__response__, 'certificate'),
        id=pulumi.get(__response__, 'id'),
        service_id=pulumi.get(__response__, 'service_id')))
