# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'ServiceBackupConfiguration',
    'ServiceEndpoints',
    'ServiceEndpointsHttps',
    'ServiceEndpointsMysql',
    'ServiceEndpointsNativesecure',
    'ServiceIpAccess',
    'ServicePrivateEndpointConfig',
    'ServiceQueryApiEndpoints',
    'ServiceTransparentDataEncryption',
]

@pulumi.output_type
class ServiceBackupConfiguration(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "backupPeriodInHours":
            suggest = "backup_period_in_hours"
        elif key == "backupRetentionPeriodInHours":
            suggest = "backup_retention_period_in_hours"
        elif key == "backupStartTime":
            suggest = "backup_start_time"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ServiceBackupConfiguration. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ServiceBackupConfiguration.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ServiceBackupConfiguration.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 backup_period_in_hours: Optional[_builtins.int] = None,
                 backup_retention_period_in_hours: Optional[_builtins.int] = None,
                 backup_start_time: Optional[_builtins.str] = None):
        """
        :param _builtins.int backup_period_in_hours: Interval in hours between each backup.
        :param _builtins.int backup_retention_period_in_hours: How long in hours to keep a backup before deleting it.
        :param _builtins.str backup_start_time: Time of the day in UTC that indicates the start time of a 2 hours window to be used for backup. If set, backup*period*in_hours must be null and backups are created once a day.
        """
        if backup_period_in_hours is not None:
            pulumi.set(__self__, "backup_period_in_hours", backup_period_in_hours)
        if backup_retention_period_in_hours is not None:
            pulumi.set(__self__, "backup_retention_period_in_hours", backup_retention_period_in_hours)
        if backup_start_time is not None:
            pulumi.set(__self__, "backup_start_time", backup_start_time)

    @_builtins.property
    @pulumi.getter(name="backupPeriodInHours")
    def backup_period_in_hours(self) -> Optional[_builtins.int]:
        """
        Interval in hours between each backup.
        """
        return pulumi.get(self, "backup_period_in_hours")

    @_builtins.property
    @pulumi.getter(name="backupRetentionPeriodInHours")
    def backup_retention_period_in_hours(self) -> Optional[_builtins.int]:
        """
        How long in hours to keep a backup before deleting it.
        """
        return pulumi.get(self, "backup_retention_period_in_hours")

    @_builtins.property
    @pulumi.getter(name="backupStartTime")
    def backup_start_time(self) -> Optional[_builtins.str]:
        """
        Time of the day in UTC that indicates the start time of a 2 hours window to be used for backup. If set, backup*period*in_hours must be null and backups are created once a day.
        """
        return pulumi.get(self, "backup_start_time")


@pulumi.output_type
class ServiceEndpoints(dict):
    def __init__(__self__, *,
                 https: Optional['outputs.ServiceEndpointsHttps'] = None,
                 mysql: Optional['outputs.ServiceEndpointsMysql'] = None,
                 nativesecure: Optional['outputs.ServiceEndpointsNativesecure'] = None):
        if https is not None:
            pulumi.set(__self__, "https", https)
        if mysql is not None:
            pulumi.set(__self__, "mysql", mysql)
        if nativesecure is not None:
            pulumi.set(__self__, "nativesecure", nativesecure)

    @_builtins.property
    @pulumi.getter
    def https(self) -> Optional['outputs.ServiceEndpointsHttps']:
        return pulumi.get(self, "https")

    @_builtins.property
    @pulumi.getter
    def mysql(self) -> Optional['outputs.ServiceEndpointsMysql']:
        return pulumi.get(self, "mysql")

    @_builtins.property
    @pulumi.getter
    def nativesecure(self) -> Optional['outputs.ServiceEndpointsNativesecure']:
        return pulumi.get(self, "nativesecure")


@pulumi.output_type
class ServiceEndpointsHttps(dict):
    def __init__(__self__, *,
                 host: Optional[_builtins.str] = None,
                 port: Optional[_builtins.int] = None):
        """
        :param _builtins.str host: Endpoint host.
        :param _builtins.int port: Endpoint port.
        """
        if host is not None:
            pulumi.set(__self__, "host", host)
        if port is not None:
            pulumi.set(__self__, "port", port)

    @_builtins.property
    @pulumi.getter
    def host(self) -> Optional[_builtins.str]:
        """
        Endpoint host.
        """
        return pulumi.get(self, "host")

    @_builtins.property
    @pulumi.getter
    def port(self) -> Optional[_builtins.int]:
        """
        Endpoint port.
        """
        return pulumi.get(self, "port")


@pulumi.output_type
class ServiceEndpointsMysql(dict):
    def __init__(__self__, *,
                 enabled: _builtins.bool,
                 host: Optional[_builtins.str] = None,
                 port: Optional[_builtins.int] = None):
        """
        :param _builtins.bool enabled: Wether to enable the mysql endpoint or not.
        :param _builtins.str host: Endpoint host.
        :param _builtins.int port: Endpoint port.
        """
        pulumi.set(__self__, "enabled", enabled)
        if host is not None:
            pulumi.set(__self__, "host", host)
        if port is not None:
            pulumi.set(__self__, "port", port)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        """
        Wether to enable the mysql endpoint or not.
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter
    def host(self) -> Optional[_builtins.str]:
        """
        Endpoint host.
        """
        return pulumi.get(self, "host")

    @_builtins.property
    @pulumi.getter
    def port(self) -> Optional[_builtins.int]:
        """
        Endpoint port.
        """
        return pulumi.get(self, "port")


@pulumi.output_type
class ServiceEndpointsNativesecure(dict):
    def __init__(__self__, *,
                 host: Optional[_builtins.str] = None,
                 port: Optional[_builtins.int] = None):
        """
        :param _builtins.str host: Endpoint host.
        :param _builtins.int port: Endpoint port.
        """
        if host is not None:
            pulumi.set(__self__, "host", host)
        if port is not None:
            pulumi.set(__self__, "port", port)

    @_builtins.property
    @pulumi.getter
    def host(self) -> Optional[_builtins.str]:
        """
        Endpoint host.
        """
        return pulumi.get(self, "host")

    @_builtins.property
    @pulumi.getter
    def port(self) -> Optional[_builtins.int]:
        """
        Endpoint port.
        """
        return pulumi.get(self, "port")


@pulumi.output_type
class ServiceIpAccess(dict):
    def __init__(__self__, *,
                 description: _builtins.str,
                 source: _builtins.str):
        """
        :param _builtins.str description: Description of the IP address.
        :param _builtins.str source: IP address allowed to access the service. In case you want to set the ip_access to anywhere you should set source to 0.0.0.0/0
        """
        pulumi.set(__self__, "description", description)
        pulumi.set(__self__, "source", source)

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        Description of the IP address.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def source(self) -> _builtins.str:
        """
        IP address allowed to access the service. In case you want to set the ip_access to anywhere you should set source to 0.0.0.0/0
        """
        return pulumi.get(self, "source")


@pulumi.output_type
class ServicePrivateEndpointConfig(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "endpointServiceId":
            suggest = "endpoint_service_id"
        elif key == "privateDnsHostname":
            suggest = "private_dns_hostname"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ServicePrivateEndpointConfig. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ServicePrivateEndpointConfig.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ServicePrivateEndpointConfig.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 endpoint_service_id: Optional[_builtins.str] = None,
                 private_dns_hostname: Optional[_builtins.str] = None):
        """
        :param _builtins.str endpoint_service_id: Unique identifier of the interface endpoint you created in your VPC with the AWS(Service Name) or GCP(Target Service) resource.
        :param _builtins.str private_dns_hostname: Private DNS Hostname of the VPC you created.
        """
        if endpoint_service_id is not None:
            pulumi.set(__self__, "endpoint_service_id", endpoint_service_id)
        if private_dns_hostname is not None:
            pulumi.set(__self__, "private_dns_hostname", private_dns_hostname)

    @_builtins.property
    @pulumi.getter(name="endpointServiceId")
    def endpoint_service_id(self) -> Optional[_builtins.str]:
        """
        Unique identifier of the interface endpoint you created in your VPC with the AWS(Service Name) or GCP(Target Service) resource.
        """
        return pulumi.get(self, "endpoint_service_id")

    @_builtins.property
    @pulumi.getter(name="privateDnsHostname")
    def private_dns_hostname(self) -> Optional[_builtins.str]:
        """
        Private DNS Hostname of the VPC you created.
        """
        return pulumi.get(self, "private_dns_hostname")


@pulumi.output_type
class ServiceQueryApiEndpoints(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "apiKeyIds":
            suggest = "api_key_ids"
        elif key == "allowedOrigins":
            suggest = "allowed_origins"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ServiceQueryApiEndpoints. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ServiceQueryApiEndpoints.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ServiceQueryApiEndpoints.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 api_key_ids: Sequence[_builtins.str],
                 roles: Sequence[_builtins.str],
                 allowed_origins: Optional[_builtins.str] = None):
        """
        :param Sequence[_builtins.str] api_key_ids: The UUIDs of the API Keys to grant access to the query API.
        :param Sequence[_builtins.str] roles: The Database role that will be used to run the query.
        :param _builtins.str allowed_origins: Comma separated list of domain names to be allowed cross-origin resource sharing (CORS) access to the query API. Leave this field empty to restrict access to backend servers only
        """
        pulumi.set(__self__, "api_key_ids", api_key_ids)
        pulumi.set(__self__, "roles", roles)
        if allowed_origins is not None:
            pulumi.set(__self__, "allowed_origins", allowed_origins)

    @_builtins.property
    @pulumi.getter(name="apiKeyIds")
    def api_key_ids(self) -> Sequence[_builtins.str]:
        """
        The UUIDs of the API Keys to grant access to the query API.
        """
        return pulumi.get(self, "api_key_ids")

    @_builtins.property
    @pulumi.getter
    def roles(self) -> Sequence[_builtins.str]:
        """
        The Database role that will be used to run the query.
        """
        return pulumi.get(self, "roles")

    @_builtins.property
    @pulumi.getter(name="allowedOrigins")
    def allowed_origins(self) -> Optional[_builtins.str]:
        """
        Comma separated list of domain names to be allowed cross-origin resource sharing (CORS) access to the query API. Leave this field empty to restrict access to backend servers only
        """
        return pulumi.get(self, "allowed_origins")


@pulumi.output_type
class ServiceTransparentDataEncryption(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "roleId":
            suggest = "role_id"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ServiceTransparentDataEncryption. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ServiceTransparentDataEncryption.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ServiceTransparentDataEncryption.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 enabled: Optional[_builtins.bool] = None,
                 role_id: Optional[_builtins.str] = None):
        """
        :param _builtins.bool enabled: If true, TDE is enabled for the service.
        :param _builtins.str role_id: ID of Role to be used for granting access to the Encryption Key. This is an ARN for AWS services and a Service Account Identifier for GCP.
        """
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if role_id is not None:
            pulumi.set(__self__, "role_id", role_id)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[_builtins.bool]:
        """
        If true, TDE is enabled for the service.
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="roleId")
    def role_id(self) -> Optional[_builtins.str]:
        """
        ID of Role to be used for granting access to the Encryption Key. This is an ARN for AWS services and a Service Account Identifier for GCP.
        """
        return pulumi.get(self, "role_id")


