# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ServiceArgs', 'Service']

@pulumi.input_type
class ServiceArgs:
    def __init__(__self__, *,
                 cloud_provider: pulumi.Input[_builtins.str],
                 ip_accesses: pulumi.Input[Sequence[pulumi.Input['ServiceIpAccessArgs']]],
                 region: pulumi.Input[_builtins.str],
                 backup_configuration: Optional[pulumi.Input['ServiceBackupConfigurationArgs']] = None,
                 backup_id: Optional[pulumi.Input[_builtins.str]] = None,
                 byoc_id: Optional[pulumi.Input[_builtins.str]] = None,
                 compliance_type: Optional[pulumi.Input[_builtins.str]] = None,
                 double_sha1_password_hash: Optional[pulumi.Input[_builtins.str]] = None,
                 enable_core_dumps: Optional[pulumi.Input[_builtins.bool]] = None,
                 encryption_assumed_role_identifier: Optional[pulumi.Input[_builtins.str]] = None,
                 encryption_key: Optional[pulumi.Input[_builtins.str]] = None,
                 endpoints: Optional[pulumi.Input['ServiceEndpointsArgs']] = None,
                 idle_scaling: Optional[pulumi.Input[_builtins.bool]] = None,
                 idle_timeout_minutes: Optional[pulumi.Input[_builtins.int]] = None,
                 max_replica_memory_gb: Optional[pulumi.Input[_builtins.int]] = None,
                 max_total_memory_gb: Optional[pulumi.Input[_builtins.int]] = None,
                 min_replica_memory_gb: Optional[pulumi.Input[_builtins.int]] = None,
                 min_total_memory_gb: Optional[pulumi.Input[_builtins.int]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 num_replicas: Optional[pulumi.Input[_builtins.int]] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 password_hash: Optional[pulumi.Input[_builtins.str]] = None,
                 password_wo: Optional[pulumi.Input[_builtins.str]] = None,
                 password_wo_version: Optional[pulumi.Input[_builtins.int]] = None,
                 query_api_endpoints: Optional[pulumi.Input['ServiceQueryApiEndpointsArgs']] = None,
                 readonly: Optional[pulumi.Input[_builtins.bool]] = None,
                 release_channel: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 tier: Optional[pulumi.Input[_builtins.str]] = None,
                 transparent_data_encryption: Optional[pulumi.Input['ServiceTransparentDataEncryptionArgs']] = None,
                 warehouse_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Service resource.

        :param pulumi.Input[_builtins.str] cloud_provider: Cloud provider ('aws', 'gcp', or 'azure') in which the service is deployed in.
        :param pulumi.Input[Sequence[pulumi.Input['ServiceIpAccessArgs']]] ip_accesses: List of IP addresses allowed to access the service.
        :param pulumi.Input[_builtins.str] region: Region within the cloud provider in which the service is deployed in.
        :param pulumi.Input['ServiceBackupConfigurationArgs'] backup_configuration: Configuration of service backup settings.
        :param pulumi.Input[_builtins.str] backup_id: ID of the backup to restore when creating new service. If specified, the service will be created as a restore operation
        :param pulumi.Input[_builtins.str] byoc_id: BYOC ID related to the cloud provider account you want to create this service into.
        :param pulumi.Input[_builtins.str] compliance_type: Compliance type of the service. Can be 'hipaa', 'pci'. Required for organizations that wish to deploy their services in the hipaa/pci compliant environment. NOTE: hipaa/pci compliance should be enabled for your ClickHouse organization before using this field.
        :param pulumi.Input[_builtins.str] double_sha1_password_hash: Double SHA1 hash of password for connecting with the MySQL protocol. Cannot be specified if `password` or `password_wo` is specified.
        :param pulumi.Input[_builtins.bool] enable_core_dumps: Enable core dumps for the service.
        :param pulumi.Input[_builtins.str] encryption_assumed_role_identifier: Custom role identifier ARN.
        :param pulumi.Input[_builtins.str] encryption_key: Custom encryption key ARN.
        :param pulumi.Input['ServiceEndpointsArgs'] endpoints: Allow to enable and configure additional endpoints (read protocols) to expose on the ClickHouse service.
        :param pulumi.Input[_builtins.bool] idle_scaling: When set to true the service is allowed to scale down to zero when idle.
        :param pulumi.Input[_builtins.int] idle_timeout_minutes: Set minimum idling timeout (in minutes). Must be greater than or equal to 5 minutes. Must be set if idle_scaling is enabled.
        :param pulumi.Input[_builtins.int] max_replica_memory_gb: Maximum memory of a single replica during auto-scaling in GiB.
        :param pulumi.Input[_builtins.int] max_total_memory_gb: Maximum total memory of all workers during auto-scaling in GiB.
        :param pulumi.Input[_builtins.int] min_replica_memory_gb: Minimum memory of a single replica during auto-scaling in GiB.
        :param pulumi.Input[_builtins.int] min_total_memory_gb: Minimum total memory of all workers during auto-scaling in GiB.
        :param pulumi.Input[_builtins.str] name: User defined identifier for the service.
        :param pulumi.Input[_builtins.int] num_replicas: Number of replicas for the service.
        :param pulumi.Input[_builtins.str] password: Password for the default user. One of either `password`, `password_wo`, or `password_hash` must be specified.
        :param pulumi.Input[_builtins.str] password_hash: SHA256 hash of password for the default user. One of either `password`, `password_wo`, or `password_hash` must be specified.
        :param pulumi.Input[_builtins.str] password_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               Password for the default user (write-only, not persisted to state). Use this instead of `password` to avoid storing the password hash in Terraform state.
        :param pulumi.Input[_builtins.int] password_wo_version: Version number for password*wo. Increment this to trigger a password update when using password*wo.
        :param pulumi.Input['ServiceQueryApiEndpointsArgs'] query_api_endpoints: Configuration of the query API endpoints feature.
        :param pulumi.Input[_builtins.bool] readonly: Indicates if this service should be read only. Only allowed for secondary services, those which share data with another service (i.e. when `warehouse_id` field is set).
        :param pulumi.Input[_builtins.str] release_channel: Release channel to use for this service. Can be 'default', 'fast' or 'slow'.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Tags associated with the service as key-value pairs.
        :param pulumi.Input[_builtins.str] tier: Tier of the service: 'development', 'production'. Required for organizations using the Legacy ClickHouse Cloud Tiers, must be omitted for organizations using the new ClickHouse Cloud Tiers.
        :param pulumi.Input['ServiceTransparentDataEncryptionArgs'] transparent_data_encryption: Configuration of the Transparent Data Encryption (TDE) feature. Requires an organization with the Enterprise plan.
        :param pulumi.Input[_builtins.str] warehouse_id: Set it to the 'warehouse_id' attribute of another service to share the data with it. The service must be in the same cloud and region.
        """
        pulumi.set(__self__, "cloud_provider", cloud_provider)
        pulumi.set(__self__, "ip_accesses", ip_accesses)
        pulumi.set(__self__, "region", region)
        if backup_configuration is not None:
            pulumi.set(__self__, "backup_configuration", backup_configuration)
        if backup_id is not None:
            pulumi.set(__self__, "backup_id", backup_id)
        if byoc_id is not None:
            pulumi.set(__self__, "byoc_id", byoc_id)
        if compliance_type is not None:
            pulumi.set(__self__, "compliance_type", compliance_type)
        if double_sha1_password_hash is not None:
            pulumi.set(__self__, "double_sha1_password_hash", double_sha1_password_hash)
        if enable_core_dumps is not None:
            pulumi.set(__self__, "enable_core_dumps", enable_core_dumps)
        if encryption_assumed_role_identifier is not None:
            pulumi.set(__self__, "encryption_assumed_role_identifier", encryption_assumed_role_identifier)
        if encryption_key is not None:
            pulumi.set(__self__, "encryption_key", encryption_key)
        if endpoints is not None:
            pulumi.set(__self__, "endpoints", endpoints)
        if idle_scaling is not None:
            pulumi.set(__self__, "idle_scaling", idle_scaling)
        if idle_timeout_minutes is not None:
            pulumi.set(__self__, "idle_timeout_minutes", idle_timeout_minutes)
        if max_replica_memory_gb is not None:
            pulumi.set(__self__, "max_replica_memory_gb", max_replica_memory_gb)
        if max_total_memory_gb is not None:
            warnings.warn("""Please use max_replica_memory_gb instead""", DeprecationWarning)
            pulumi.log.warn("""max_total_memory_gb is deprecated: Please use max_replica_memory_gb instead""")
        if max_total_memory_gb is not None:
            pulumi.set(__self__, "max_total_memory_gb", max_total_memory_gb)
        if min_replica_memory_gb is not None:
            pulumi.set(__self__, "min_replica_memory_gb", min_replica_memory_gb)
        if min_total_memory_gb is not None:
            warnings.warn("""Please use min_replica_memory_gb instead""", DeprecationWarning)
            pulumi.log.warn("""min_total_memory_gb is deprecated: Please use min_replica_memory_gb instead""")
        if min_total_memory_gb is not None:
            pulumi.set(__self__, "min_total_memory_gb", min_total_memory_gb)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if num_replicas is not None:
            pulumi.set(__self__, "num_replicas", num_replicas)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if password_hash is not None:
            pulumi.set(__self__, "password_hash", password_hash)
        if password_wo is not None:
            pulumi.set(__self__, "password_wo", password_wo)
        if password_wo_version is not None:
            pulumi.set(__self__, "password_wo_version", password_wo_version)
        if query_api_endpoints is not None:
            pulumi.set(__self__, "query_api_endpoints", query_api_endpoints)
        if readonly is not None:
            pulumi.set(__self__, "readonly", readonly)
        if release_channel is not None:
            pulumi.set(__self__, "release_channel", release_channel)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tier is not None:
            pulumi.set(__self__, "tier", tier)
        if transparent_data_encryption is not None:
            pulumi.set(__self__, "transparent_data_encryption", transparent_data_encryption)
        if warehouse_id is not None:
            pulumi.set(__self__, "warehouse_id", warehouse_id)

    @_builtins.property
    @pulumi.getter(name="cloudProvider")
    def cloud_provider(self) -> pulumi.Input[_builtins.str]:
        """
        Cloud provider ('aws', 'gcp', or 'azure') in which the service is deployed in.
        """
        return pulumi.get(self, "cloud_provider")

    @cloud_provider.setter
    def cloud_provider(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "cloud_provider", value)

    @_builtins.property
    @pulumi.getter(name="ipAccesses")
    def ip_accesses(self) -> pulumi.Input[Sequence[pulumi.Input['ServiceIpAccessArgs']]]:
        """
        List of IP addresses allowed to access the service.
        """
        return pulumi.get(self, "ip_accesses")

    @ip_accesses.setter
    def ip_accesses(self, value: pulumi.Input[Sequence[pulumi.Input['ServiceIpAccessArgs']]]):
        pulumi.set(self, "ip_accesses", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Input[_builtins.str]:
        """
        Region within the cloud provider in which the service is deployed in.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter(name="backupConfiguration")
    def backup_configuration(self) -> Optional[pulumi.Input['ServiceBackupConfigurationArgs']]:
        """
        Configuration of service backup settings.
        """
        return pulumi.get(self, "backup_configuration")

    @backup_configuration.setter
    def backup_configuration(self, value: Optional[pulumi.Input['ServiceBackupConfigurationArgs']]):
        pulumi.set(self, "backup_configuration", value)

    @_builtins.property
    @pulumi.getter(name="backupId")
    def backup_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        ID of the backup to restore when creating new service. If specified, the service will be created as a restore operation
        """
        return pulumi.get(self, "backup_id")

    @backup_id.setter
    def backup_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "backup_id", value)

    @_builtins.property
    @pulumi.getter(name="byocId")
    def byoc_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        BYOC ID related to the cloud provider account you want to create this service into.
        """
        return pulumi.get(self, "byoc_id")

    @byoc_id.setter
    def byoc_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "byoc_id", value)

    @_builtins.property
    @pulumi.getter(name="complianceType")
    def compliance_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Compliance type of the service. Can be 'hipaa', 'pci'. Required for organizations that wish to deploy their services in the hipaa/pci compliant environment. NOTE: hipaa/pci compliance should be enabled for your ClickHouse organization before using this field.
        """
        return pulumi.get(self, "compliance_type")

    @compliance_type.setter
    def compliance_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "compliance_type", value)

    @_builtins.property
    @pulumi.getter(name="doubleSha1PasswordHash")
    def double_sha1_password_hash(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Double SHA1 hash of password for connecting with the MySQL protocol. Cannot be specified if `password` or `password_wo` is specified.
        """
        return pulumi.get(self, "double_sha1_password_hash")

    @double_sha1_password_hash.setter
    def double_sha1_password_hash(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "double_sha1_password_hash", value)

    @_builtins.property
    @pulumi.getter(name="enableCoreDumps")
    def enable_core_dumps(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Enable core dumps for the service.
        """
        return pulumi.get(self, "enable_core_dumps")

    @enable_core_dumps.setter
    def enable_core_dumps(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enable_core_dumps", value)

    @_builtins.property
    @pulumi.getter(name="encryptionAssumedRoleIdentifier")
    def encryption_assumed_role_identifier(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Custom role identifier ARN.
        """
        return pulumi.get(self, "encryption_assumed_role_identifier")

    @encryption_assumed_role_identifier.setter
    def encryption_assumed_role_identifier(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "encryption_assumed_role_identifier", value)

    @_builtins.property
    @pulumi.getter(name="encryptionKey")
    def encryption_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Custom encryption key ARN.
        """
        return pulumi.get(self, "encryption_key")

    @encryption_key.setter
    def encryption_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "encryption_key", value)

    @_builtins.property
    @pulumi.getter
    def endpoints(self) -> Optional[pulumi.Input['ServiceEndpointsArgs']]:
        """
        Allow to enable and configure additional endpoints (read protocols) to expose on the ClickHouse service.
        """
        return pulumi.get(self, "endpoints")

    @endpoints.setter
    def endpoints(self, value: Optional[pulumi.Input['ServiceEndpointsArgs']]):
        pulumi.set(self, "endpoints", value)

    @_builtins.property
    @pulumi.getter(name="idleScaling")
    def idle_scaling(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        When set to true the service is allowed to scale down to zero when idle.
        """
        return pulumi.get(self, "idle_scaling")

    @idle_scaling.setter
    def idle_scaling(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "idle_scaling", value)

    @_builtins.property
    @pulumi.getter(name="idleTimeoutMinutes")
    def idle_timeout_minutes(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Set minimum idling timeout (in minutes). Must be greater than or equal to 5 minutes. Must be set if idle_scaling is enabled.
        """
        return pulumi.get(self, "idle_timeout_minutes")

    @idle_timeout_minutes.setter
    def idle_timeout_minutes(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "idle_timeout_minutes", value)

    @_builtins.property
    @pulumi.getter(name="maxReplicaMemoryGb")
    def max_replica_memory_gb(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Maximum memory of a single replica during auto-scaling in GiB.
        """
        return pulumi.get(self, "max_replica_memory_gb")

    @max_replica_memory_gb.setter
    def max_replica_memory_gb(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "max_replica_memory_gb", value)

    @_builtins.property
    @pulumi.getter(name="maxTotalMemoryGb")
    @_utilities.deprecated("""Please use max_replica_memory_gb instead""")
    def max_total_memory_gb(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Maximum total memory of all workers during auto-scaling in GiB.
        """
        return pulumi.get(self, "max_total_memory_gb")

    @max_total_memory_gb.setter
    def max_total_memory_gb(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "max_total_memory_gb", value)

    @_builtins.property
    @pulumi.getter(name="minReplicaMemoryGb")
    def min_replica_memory_gb(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Minimum memory of a single replica during auto-scaling in GiB.
        """
        return pulumi.get(self, "min_replica_memory_gb")

    @min_replica_memory_gb.setter
    def min_replica_memory_gb(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "min_replica_memory_gb", value)

    @_builtins.property
    @pulumi.getter(name="minTotalMemoryGb")
    @_utilities.deprecated("""Please use min_replica_memory_gb instead""")
    def min_total_memory_gb(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Minimum total memory of all workers during auto-scaling in GiB.
        """
        return pulumi.get(self, "min_total_memory_gb")

    @min_total_memory_gb.setter
    def min_total_memory_gb(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "min_total_memory_gb", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        User defined identifier for the service.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="numReplicas")
    def num_replicas(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Number of replicas for the service.
        """
        return pulumi.get(self, "num_replicas")

    @num_replicas.setter
    def num_replicas(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "num_replicas", value)

    @_builtins.property
    @pulumi.getter
    def password(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Password for the default user. One of either `password`, `password_wo`, or `password_hash` must be specified.
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password", value)

    @_builtins.property
    @pulumi.getter(name="passwordHash")
    def password_hash(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        SHA256 hash of password for the default user. One of either `password`, `password_wo`, or `password_hash` must be specified.
        """
        return pulumi.get(self, "password_hash")

    @password_hash.setter
    def password_hash(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password_hash", value)

    @_builtins.property
    @pulumi.getter(name="passwordWo")
    def password_wo(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        Password for the default user (write-only, not persisted to state). Use this instead of `password` to avoid storing the password hash in Terraform state.
        """
        return pulumi.get(self, "password_wo")

    @password_wo.setter
    def password_wo(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password_wo", value)

    @_builtins.property
    @pulumi.getter(name="passwordWoVersion")
    def password_wo_version(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Version number for password*wo. Increment this to trigger a password update when using password*wo.
        """
        return pulumi.get(self, "password_wo_version")

    @password_wo_version.setter
    def password_wo_version(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "password_wo_version", value)

    @_builtins.property
    @pulumi.getter(name="queryApiEndpoints")
    def query_api_endpoints(self) -> Optional[pulumi.Input['ServiceQueryApiEndpointsArgs']]:
        """
        Configuration of the query API endpoints feature.
        """
        return pulumi.get(self, "query_api_endpoints")

    @query_api_endpoints.setter
    def query_api_endpoints(self, value: Optional[pulumi.Input['ServiceQueryApiEndpointsArgs']]):
        pulumi.set(self, "query_api_endpoints", value)

    @_builtins.property
    @pulumi.getter
    def readonly(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Indicates if this service should be read only. Only allowed for secondary services, those which share data with another service (i.e. when `warehouse_id` field is set).
        """
        return pulumi.get(self, "readonly")

    @readonly.setter
    def readonly(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "readonly", value)

    @_builtins.property
    @pulumi.getter(name="releaseChannel")
    def release_channel(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Release channel to use for this service. Can be 'default', 'fast' or 'slow'.
        """
        return pulumi.get(self, "release_channel")

    @release_channel.setter
    def release_channel(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "release_channel", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Tags associated with the service as key-value pairs.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter
    def tier(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Tier of the service: 'development', 'production'. Required for organizations using the Legacy ClickHouse Cloud Tiers, must be omitted for organizations using the new ClickHouse Cloud Tiers.
        """
        return pulumi.get(self, "tier")

    @tier.setter
    def tier(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tier", value)

    @_builtins.property
    @pulumi.getter(name="transparentDataEncryption")
    def transparent_data_encryption(self) -> Optional[pulumi.Input['ServiceTransparentDataEncryptionArgs']]:
        """
        Configuration of the Transparent Data Encryption (TDE) feature. Requires an organization with the Enterprise plan.
        """
        return pulumi.get(self, "transparent_data_encryption")

    @transparent_data_encryption.setter
    def transparent_data_encryption(self, value: Optional[pulumi.Input['ServiceTransparentDataEncryptionArgs']]):
        pulumi.set(self, "transparent_data_encryption", value)

    @_builtins.property
    @pulumi.getter(name="warehouseId")
    def warehouse_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Set it to the 'warehouse_id' attribute of another service to share the data with it. The service must be in the same cloud and region.
        """
        return pulumi.get(self, "warehouse_id")

    @warehouse_id.setter
    def warehouse_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "warehouse_id", value)


@pulumi.input_type
class _ServiceState:
    def __init__(__self__, *,
                 backup_configuration: Optional[pulumi.Input['ServiceBackupConfigurationArgs']] = None,
                 backup_id: Optional[pulumi.Input[_builtins.str]] = None,
                 byoc_id: Optional[pulumi.Input[_builtins.str]] = None,
                 cloud_provider: Optional[pulumi.Input[_builtins.str]] = None,
                 compliance_type: Optional[pulumi.Input[_builtins.str]] = None,
                 double_sha1_password_hash: Optional[pulumi.Input[_builtins.str]] = None,
                 enable_core_dumps: Optional[pulumi.Input[_builtins.bool]] = None,
                 encryption_assumed_role_identifier: Optional[pulumi.Input[_builtins.str]] = None,
                 encryption_key: Optional[pulumi.Input[_builtins.str]] = None,
                 endpoints: Optional[pulumi.Input['ServiceEndpointsArgs']] = None,
                 iam_role: Optional[pulumi.Input[_builtins.str]] = None,
                 idle_scaling: Optional[pulumi.Input[_builtins.bool]] = None,
                 idle_timeout_minutes: Optional[pulumi.Input[_builtins.int]] = None,
                 ip_accesses: Optional[pulumi.Input[Sequence[pulumi.Input['ServiceIpAccessArgs']]]] = None,
                 is_primary: Optional[pulumi.Input[_builtins.bool]] = None,
                 max_replica_memory_gb: Optional[pulumi.Input[_builtins.int]] = None,
                 max_total_memory_gb: Optional[pulumi.Input[_builtins.int]] = None,
                 min_replica_memory_gb: Optional[pulumi.Input[_builtins.int]] = None,
                 min_total_memory_gb: Optional[pulumi.Input[_builtins.int]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 num_replicas: Optional[pulumi.Input[_builtins.int]] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 password_hash: Optional[pulumi.Input[_builtins.str]] = None,
                 password_wo: Optional[pulumi.Input[_builtins.str]] = None,
                 password_wo_version: Optional[pulumi.Input[_builtins.int]] = None,
                 private_endpoint_config: Optional[pulumi.Input['ServicePrivateEndpointConfigArgs']] = None,
                 query_api_endpoints: Optional[pulumi.Input['ServiceQueryApiEndpointsArgs']] = None,
                 readonly: Optional[pulumi.Input[_builtins.bool]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 release_channel: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 tier: Optional[pulumi.Input[_builtins.str]] = None,
                 transparent_data_encryption: Optional[pulumi.Input['ServiceTransparentDataEncryptionArgs']] = None,
                 warehouse_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Service resources.

        :param pulumi.Input['ServiceBackupConfigurationArgs'] backup_configuration: Configuration of service backup settings.
        :param pulumi.Input[_builtins.str] backup_id: ID of the backup to restore when creating new service. If specified, the service will be created as a restore operation
        :param pulumi.Input[_builtins.str] byoc_id: BYOC ID related to the cloud provider account you want to create this service into.
        :param pulumi.Input[_builtins.str] cloud_provider: Cloud provider ('aws', 'gcp', or 'azure') in which the service is deployed in.
        :param pulumi.Input[_builtins.str] compliance_type: Compliance type of the service. Can be 'hipaa', 'pci'. Required for organizations that wish to deploy their services in the hipaa/pci compliant environment. NOTE: hipaa/pci compliance should be enabled for your ClickHouse organization before using this field.
        :param pulumi.Input[_builtins.str] double_sha1_password_hash: Double SHA1 hash of password for connecting with the MySQL protocol. Cannot be specified if `password` or `password_wo` is specified.
        :param pulumi.Input[_builtins.bool] enable_core_dumps: Enable core dumps for the service.
        :param pulumi.Input[_builtins.str] encryption_assumed_role_identifier: Custom role identifier ARN.
        :param pulumi.Input[_builtins.str] encryption_key: Custom encryption key ARN.
        :param pulumi.Input['ServiceEndpointsArgs'] endpoints: Allow to enable and configure additional endpoints (read protocols) to expose on the ClickHouse service.
        :param pulumi.Input[_builtins.str] iam_role: IAM role used for accessing objects in s3.
        :param pulumi.Input[_builtins.bool] idle_scaling: When set to true the service is allowed to scale down to zero when idle.
        :param pulumi.Input[_builtins.int] idle_timeout_minutes: Set minimum idling timeout (in minutes). Must be greater than or equal to 5 minutes. Must be set if idle_scaling is enabled.
        :param pulumi.Input[Sequence[pulumi.Input['ServiceIpAccessArgs']]] ip_accesses: List of IP addresses allowed to access the service.
        :param pulumi.Input[_builtins.bool] is_primary: If true, it indicates this is a primary service using its own data. If false it means this service is a secondary service, thus using data from a warehouse.
        :param pulumi.Input[_builtins.int] max_replica_memory_gb: Maximum memory of a single replica during auto-scaling in GiB.
        :param pulumi.Input[_builtins.int] max_total_memory_gb: Maximum total memory of all workers during auto-scaling in GiB.
        :param pulumi.Input[_builtins.int] min_replica_memory_gb: Minimum memory of a single replica during auto-scaling in GiB.
        :param pulumi.Input[_builtins.int] min_total_memory_gb: Minimum total memory of all workers during auto-scaling in GiB.
        :param pulumi.Input[_builtins.str] name: User defined identifier for the service.
        :param pulumi.Input[_builtins.int] num_replicas: Number of replicas for the service.
        :param pulumi.Input[_builtins.str] password: Password for the default user. One of either `password`, `password_wo`, or `password_hash` must be specified.
        :param pulumi.Input[_builtins.str] password_hash: SHA256 hash of password for the default user. One of either `password`, `password_wo`, or `password_hash` must be specified.
        :param pulumi.Input[_builtins.str] password_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               Password for the default user (write-only, not persisted to state). Use this instead of `password` to avoid storing the password hash in Terraform state.
        :param pulumi.Input[_builtins.int] password_wo_version: Version number for password*wo. Increment this to trigger a password update when using password*wo.
        :param pulumi.Input['ServicePrivateEndpointConfigArgs'] private_endpoint_config: Service config for private endpoints
        :param pulumi.Input['ServiceQueryApiEndpointsArgs'] query_api_endpoints: Configuration of the query API endpoints feature.
        :param pulumi.Input[_builtins.bool] readonly: Indicates if this service should be read only. Only allowed for secondary services, those which share data with another service (i.e. when `warehouse_id` field is set).
        :param pulumi.Input[_builtins.str] region: Region within the cloud provider in which the service is deployed in.
        :param pulumi.Input[_builtins.str] release_channel: Release channel to use for this service. Can be 'default', 'fast' or 'slow'.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Tags associated with the service as key-value pairs.
        :param pulumi.Input[_builtins.str] tier: Tier of the service: 'development', 'production'. Required for organizations using the Legacy ClickHouse Cloud Tiers, must be omitted for organizations using the new ClickHouse Cloud Tiers.
        :param pulumi.Input['ServiceTransparentDataEncryptionArgs'] transparent_data_encryption: Configuration of the Transparent Data Encryption (TDE) feature. Requires an organization with the Enterprise plan.
        :param pulumi.Input[_builtins.str] warehouse_id: Set it to the 'warehouse_id' attribute of another service to share the data with it. The service must be in the same cloud and region.
        """
        if backup_configuration is not None:
            pulumi.set(__self__, "backup_configuration", backup_configuration)
        if backup_id is not None:
            pulumi.set(__self__, "backup_id", backup_id)
        if byoc_id is not None:
            pulumi.set(__self__, "byoc_id", byoc_id)
        if cloud_provider is not None:
            pulumi.set(__self__, "cloud_provider", cloud_provider)
        if compliance_type is not None:
            pulumi.set(__self__, "compliance_type", compliance_type)
        if double_sha1_password_hash is not None:
            pulumi.set(__self__, "double_sha1_password_hash", double_sha1_password_hash)
        if enable_core_dumps is not None:
            pulumi.set(__self__, "enable_core_dumps", enable_core_dumps)
        if encryption_assumed_role_identifier is not None:
            pulumi.set(__self__, "encryption_assumed_role_identifier", encryption_assumed_role_identifier)
        if encryption_key is not None:
            pulumi.set(__self__, "encryption_key", encryption_key)
        if endpoints is not None:
            pulumi.set(__self__, "endpoints", endpoints)
        if iam_role is not None:
            pulumi.set(__self__, "iam_role", iam_role)
        if idle_scaling is not None:
            pulumi.set(__self__, "idle_scaling", idle_scaling)
        if idle_timeout_minutes is not None:
            pulumi.set(__self__, "idle_timeout_minutes", idle_timeout_minutes)
        if ip_accesses is not None:
            pulumi.set(__self__, "ip_accesses", ip_accesses)
        if is_primary is not None:
            pulumi.set(__self__, "is_primary", is_primary)
        if max_replica_memory_gb is not None:
            pulumi.set(__self__, "max_replica_memory_gb", max_replica_memory_gb)
        if max_total_memory_gb is not None:
            warnings.warn("""Please use max_replica_memory_gb instead""", DeprecationWarning)
            pulumi.log.warn("""max_total_memory_gb is deprecated: Please use max_replica_memory_gb instead""")
        if max_total_memory_gb is not None:
            pulumi.set(__self__, "max_total_memory_gb", max_total_memory_gb)
        if min_replica_memory_gb is not None:
            pulumi.set(__self__, "min_replica_memory_gb", min_replica_memory_gb)
        if min_total_memory_gb is not None:
            warnings.warn("""Please use min_replica_memory_gb instead""", DeprecationWarning)
            pulumi.log.warn("""min_total_memory_gb is deprecated: Please use min_replica_memory_gb instead""")
        if min_total_memory_gb is not None:
            pulumi.set(__self__, "min_total_memory_gb", min_total_memory_gb)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if num_replicas is not None:
            pulumi.set(__self__, "num_replicas", num_replicas)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if password_hash is not None:
            pulumi.set(__self__, "password_hash", password_hash)
        if password_wo is not None:
            pulumi.set(__self__, "password_wo", password_wo)
        if password_wo_version is not None:
            pulumi.set(__self__, "password_wo_version", password_wo_version)
        if private_endpoint_config is not None:
            pulumi.set(__self__, "private_endpoint_config", private_endpoint_config)
        if query_api_endpoints is not None:
            pulumi.set(__self__, "query_api_endpoints", query_api_endpoints)
        if readonly is not None:
            pulumi.set(__self__, "readonly", readonly)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if release_channel is not None:
            pulumi.set(__self__, "release_channel", release_channel)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if tier is not None:
            pulumi.set(__self__, "tier", tier)
        if transparent_data_encryption is not None:
            pulumi.set(__self__, "transparent_data_encryption", transparent_data_encryption)
        if warehouse_id is not None:
            pulumi.set(__self__, "warehouse_id", warehouse_id)

    @_builtins.property
    @pulumi.getter(name="backupConfiguration")
    def backup_configuration(self) -> Optional[pulumi.Input['ServiceBackupConfigurationArgs']]:
        """
        Configuration of service backup settings.
        """
        return pulumi.get(self, "backup_configuration")

    @backup_configuration.setter
    def backup_configuration(self, value: Optional[pulumi.Input['ServiceBackupConfigurationArgs']]):
        pulumi.set(self, "backup_configuration", value)

    @_builtins.property
    @pulumi.getter(name="backupId")
    def backup_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        ID of the backup to restore when creating new service. If specified, the service will be created as a restore operation
        """
        return pulumi.get(self, "backup_id")

    @backup_id.setter
    def backup_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "backup_id", value)

    @_builtins.property
    @pulumi.getter(name="byocId")
    def byoc_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        BYOC ID related to the cloud provider account you want to create this service into.
        """
        return pulumi.get(self, "byoc_id")

    @byoc_id.setter
    def byoc_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "byoc_id", value)

    @_builtins.property
    @pulumi.getter(name="cloudProvider")
    def cloud_provider(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Cloud provider ('aws', 'gcp', or 'azure') in which the service is deployed in.
        """
        return pulumi.get(self, "cloud_provider")

    @cloud_provider.setter
    def cloud_provider(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cloud_provider", value)

    @_builtins.property
    @pulumi.getter(name="complianceType")
    def compliance_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Compliance type of the service. Can be 'hipaa', 'pci'. Required for organizations that wish to deploy their services in the hipaa/pci compliant environment. NOTE: hipaa/pci compliance should be enabled for your ClickHouse organization before using this field.
        """
        return pulumi.get(self, "compliance_type")

    @compliance_type.setter
    def compliance_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "compliance_type", value)

    @_builtins.property
    @pulumi.getter(name="doubleSha1PasswordHash")
    def double_sha1_password_hash(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Double SHA1 hash of password for connecting with the MySQL protocol. Cannot be specified if `password` or `password_wo` is specified.
        """
        return pulumi.get(self, "double_sha1_password_hash")

    @double_sha1_password_hash.setter
    def double_sha1_password_hash(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "double_sha1_password_hash", value)

    @_builtins.property
    @pulumi.getter(name="enableCoreDumps")
    def enable_core_dumps(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Enable core dumps for the service.
        """
        return pulumi.get(self, "enable_core_dumps")

    @enable_core_dumps.setter
    def enable_core_dumps(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enable_core_dumps", value)

    @_builtins.property
    @pulumi.getter(name="encryptionAssumedRoleIdentifier")
    def encryption_assumed_role_identifier(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Custom role identifier ARN.
        """
        return pulumi.get(self, "encryption_assumed_role_identifier")

    @encryption_assumed_role_identifier.setter
    def encryption_assumed_role_identifier(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "encryption_assumed_role_identifier", value)

    @_builtins.property
    @pulumi.getter(name="encryptionKey")
    def encryption_key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Custom encryption key ARN.
        """
        return pulumi.get(self, "encryption_key")

    @encryption_key.setter
    def encryption_key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "encryption_key", value)

    @_builtins.property
    @pulumi.getter
    def endpoints(self) -> Optional[pulumi.Input['ServiceEndpointsArgs']]:
        """
        Allow to enable and configure additional endpoints (read protocols) to expose on the ClickHouse service.
        """
        return pulumi.get(self, "endpoints")

    @endpoints.setter
    def endpoints(self, value: Optional[pulumi.Input['ServiceEndpointsArgs']]):
        pulumi.set(self, "endpoints", value)

    @_builtins.property
    @pulumi.getter(name="iamRole")
    def iam_role(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        IAM role used for accessing objects in s3.
        """
        return pulumi.get(self, "iam_role")

    @iam_role.setter
    def iam_role(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "iam_role", value)

    @_builtins.property
    @pulumi.getter(name="idleScaling")
    def idle_scaling(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        When set to true the service is allowed to scale down to zero when idle.
        """
        return pulumi.get(self, "idle_scaling")

    @idle_scaling.setter
    def idle_scaling(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "idle_scaling", value)

    @_builtins.property
    @pulumi.getter(name="idleTimeoutMinutes")
    def idle_timeout_minutes(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Set minimum idling timeout (in minutes). Must be greater than or equal to 5 minutes. Must be set if idle_scaling is enabled.
        """
        return pulumi.get(self, "idle_timeout_minutes")

    @idle_timeout_minutes.setter
    def idle_timeout_minutes(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "idle_timeout_minutes", value)

    @_builtins.property
    @pulumi.getter(name="ipAccesses")
    def ip_accesses(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['ServiceIpAccessArgs']]]]:
        """
        List of IP addresses allowed to access the service.
        """
        return pulumi.get(self, "ip_accesses")

    @ip_accesses.setter
    def ip_accesses(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['ServiceIpAccessArgs']]]]):
        pulumi.set(self, "ip_accesses", value)

    @_builtins.property
    @pulumi.getter(name="isPrimary")
    def is_primary(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        If true, it indicates this is a primary service using its own data. If false it means this service is a secondary service, thus using data from a warehouse.
        """
        return pulumi.get(self, "is_primary")

    @is_primary.setter
    def is_primary(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "is_primary", value)

    @_builtins.property
    @pulumi.getter(name="maxReplicaMemoryGb")
    def max_replica_memory_gb(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Maximum memory of a single replica during auto-scaling in GiB.
        """
        return pulumi.get(self, "max_replica_memory_gb")

    @max_replica_memory_gb.setter
    def max_replica_memory_gb(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "max_replica_memory_gb", value)

    @_builtins.property
    @pulumi.getter(name="maxTotalMemoryGb")
    @_utilities.deprecated("""Please use max_replica_memory_gb instead""")
    def max_total_memory_gb(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Maximum total memory of all workers during auto-scaling in GiB.
        """
        return pulumi.get(self, "max_total_memory_gb")

    @max_total_memory_gb.setter
    def max_total_memory_gb(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "max_total_memory_gb", value)

    @_builtins.property
    @pulumi.getter(name="minReplicaMemoryGb")
    def min_replica_memory_gb(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Minimum memory of a single replica during auto-scaling in GiB.
        """
        return pulumi.get(self, "min_replica_memory_gb")

    @min_replica_memory_gb.setter
    def min_replica_memory_gb(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "min_replica_memory_gb", value)

    @_builtins.property
    @pulumi.getter(name="minTotalMemoryGb")
    @_utilities.deprecated("""Please use min_replica_memory_gb instead""")
    def min_total_memory_gb(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Minimum total memory of all workers during auto-scaling in GiB.
        """
        return pulumi.get(self, "min_total_memory_gb")

    @min_total_memory_gb.setter
    def min_total_memory_gb(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "min_total_memory_gb", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        User defined identifier for the service.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="numReplicas")
    def num_replicas(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Number of replicas for the service.
        """
        return pulumi.get(self, "num_replicas")

    @num_replicas.setter
    def num_replicas(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "num_replicas", value)

    @_builtins.property
    @pulumi.getter
    def password(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Password for the default user. One of either `password`, `password_wo`, or `password_hash` must be specified.
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password", value)

    @_builtins.property
    @pulumi.getter(name="passwordHash")
    def password_hash(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        SHA256 hash of password for the default user. One of either `password`, `password_wo`, or `password_hash` must be specified.
        """
        return pulumi.get(self, "password_hash")

    @password_hash.setter
    def password_hash(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password_hash", value)

    @_builtins.property
    @pulumi.getter(name="passwordWo")
    def password_wo(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        Password for the default user (write-only, not persisted to state). Use this instead of `password` to avoid storing the password hash in Terraform state.
        """
        return pulumi.get(self, "password_wo")

    @password_wo.setter
    def password_wo(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "password_wo", value)

    @_builtins.property
    @pulumi.getter(name="passwordWoVersion")
    def password_wo_version(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Version number for password*wo. Increment this to trigger a password update when using password*wo.
        """
        return pulumi.get(self, "password_wo_version")

    @password_wo_version.setter
    def password_wo_version(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "password_wo_version", value)

    @_builtins.property
    @pulumi.getter(name="privateEndpointConfig")
    def private_endpoint_config(self) -> Optional[pulumi.Input['ServicePrivateEndpointConfigArgs']]:
        """
        Service config for private endpoints
        """
        return pulumi.get(self, "private_endpoint_config")

    @private_endpoint_config.setter
    def private_endpoint_config(self, value: Optional[pulumi.Input['ServicePrivateEndpointConfigArgs']]):
        pulumi.set(self, "private_endpoint_config", value)

    @_builtins.property
    @pulumi.getter(name="queryApiEndpoints")
    def query_api_endpoints(self) -> Optional[pulumi.Input['ServiceQueryApiEndpointsArgs']]:
        """
        Configuration of the query API endpoints feature.
        """
        return pulumi.get(self, "query_api_endpoints")

    @query_api_endpoints.setter
    def query_api_endpoints(self, value: Optional[pulumi.Input['ServiceQueryApiEndpointsArgs']]):
        pulumi.set(self, "query_api_endpoints", value)

    @_builtins.property
    @pulumi.getter
    def readonly(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Indicates if this service should be read only. Only allowed for secondary services, those which share data with another service (i.e. when `warehouse_id` field is set).
        """
        return pulumi.get(self, "readonly")

    @readonly.setter
    def readonly(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "readonly", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Region within the cloud provider in which the service is deployed in.
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter(name="releaseChannel")
    def release_channel(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Release channel to use for this service. Can be 'default', 'fast' or 'slow'.
        """
        return pulumi.get(self, "release_channel")

    @release_channel.setter
    def release_channel(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "release_channel", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Tags associated with the service as key-value pairs.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter
    def tier(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Tier of the service: 'development', 'production'. Required for organizations using the Legacy ClickHouse Cloud Tiers, must be omitted for organizations using the new ClickHouse Cloud Tiers.
        """
        return pulumi.get(self, "tier")

    @tier.setter
    def tier(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tier", value)

    @_builtins.property
    @pulumi.getter(name="transparentDataEncryption")
    def transparent_data_encryption(self) -> Optional[pulumi.Input['ServiceTransparentDataEncryptionArgs']]:
        """
        Configuration of the Transparent Data Encryption (TDE) feature. Requires an organization with the Enterprise plan.
        """
        return pulumi.get(self, "transparent_data_encryption")

    @transparent_data_encryption.setter
    def transparent_data_encryption(self, value: Optional[pulumi.Input['ServiceTransparentDataEncryptionArgs']]):
        pulumi.set(self, "transparent_data_encryption", value)

    @_builtins.property
    @pulumi.getter(name="warehouseId")
    def warehouse_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Set it to the 'warehouse_id' attribute of another service to share the data with it. The service must be in the same cloud and region.
        """
        return pulumi.get(self, "warehouse_id")

    @warehouse_id.setter
    def warehouse_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "warehouse_id", value)


@pulumi.type_token("clickhouse:index/service:Service")
class Service(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 backup_configuration: Optional[pulumi.Input[Union['ServiceBackupConfigurationArgs', 'ServiceBackupConfigurationArgsDict']]] = None,
                 backup_id: Optional[pulumi.Input[_builtins.str]] = None,
                 byoc_id: Optional[pulumi.Input[_builtins.str]] = None,
                 cloud_provider: Optional[pulumi.Input[_builtins.str]] = None,
                 compliance_type: Optional[pulumi.Input[_builtins.str]] = None,
                 double_sha1_password_hash: Optional[pulumi.Input[_builtins.str]] = None,
                 enable_core_dumps: Optional[pulumi.Input[_builtins.bool]] = None,
                 encryption_assumed_role_identifier: Optional[pulumi.Input[_builtins.str]] = None,
                 encryption_key: Optional[pulumi.Input[_builtins.str]] = None,
                 endpoints: Optional[pulumi.Input[Union['ServiceEndpointsArgs', 'ServiceEndpointsArgsDict']]] = None,
                 idle_scaling: Optional[pulumi.Input[_builtins.bool]] = None,
                 idle_timeout_minutes: Optional[pulumi.Input[_builtins.int]] = None,
                 ip_accesses: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ServiceIpAccessArgs', 'ServiceIpAccessArgsDict']]]]] = None,
                 max_replica_memory_gb: Optional[pulumi.Input[_builtins.int]] = None,
                 max_total_memory_gb: Optional[pulumi.Input[_builtins.int]] = None,
                 min_replica_memory_gb: Optional[pulumi.Input[_builtins.int]] = None,
                 min_total_memory_gb: Optional[pulumi.Input[_builtins.int]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 num_replicas: Optional[pulumi.Input[_builtins.int]] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 password_hash: Optional[pulumi.Input[_builtins.str]] = None,
                 password_wo: Optional[pulumi.Input[_builtins.str]] = None,
                 password_wo_version: Optional[pulumi.Input[_builtins.int]] = None,
                 query_api_endpoints: Optional[pulumi.Input[Union['ServiceQueryApiEndpointsArgs', 'ServiceQueryApiEndpointsArgsDict']]] = None,
                 readonly: Optional[pulumi.Input[_builtins.bool]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 release_channel: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 tier: Optional[pulumi.Input[_builtins.str]] = None,
                 transparent_data_encryption: Optional[pulumi.Input[Union['ServiceTransparentDataEncryptionArgs', 'ServiceTransparentDataEncryptionArgsDict']]] = None,
                 warehouse_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        You can use the *clickhouse_service* resource to deploy ClickHouse cloud instances on supported cloud providers.

        Known limitations:

        - If you create a service with `warehouse_id` set and then remove `warehouse_id` attribute completely, the provider won't detect the change. If you want to make a secondary service become primary, remove the `warehouse_id` and taint it before applying.
        - If you create a service with `readonly` flag set to true and then remove `readonly` flag completely, the provider won't detect the change. If you want to make a secondary service read write, explicitly set the `readonly` flag to false.

        ## Example Usage

        ```python
        import pulumi
        import pulumiverse_clickhouse as clickhouse

        service = clickhouse.Service("service",
            name="My Service",
            cloud_provider="aws",
            region="us-east-1",
            idle_scaling=True,
            ip_accesses=[{
                "source": "192.168.2.63",
                "description": "Test IP",
            }],
            tags={
                "Environment": "Staging",
            },
            min_total_memory_gb=24,
            max_total_memory_gb=360,
            idle_timeout_minutes=5,
            password_hash="n4bQgYhMfWWaL+qgxVrQFaO/TxsrC4Is0V1sFbDwCgg=")
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        Services can be imported by specifying the UUID.

        ```sh
        $ pulumi import clickhouse:index/service:Service example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['ServiceBackupConfigurationArgs', 'ServiceBackupConfigurationArgsDict']] backup_configuration: Configuration of service backup settings.
        :param pulumi.Input[_builtins.str] backup_id: ID of the backup to restore when creating new service. If specified, the service will be created as a restore operation
        :param pulumi.Input[_builtins.str] byoc_id: BYOC ID related to the cloud provider account you want to create this service into.
        :param pulumi.Input[_builtins.str] cloud_provider: Cloud provider ('aws', 'gcp', or 'azure') in which the service is deployed in.
        :param pulumi.Input[_builtins.str] compliance_type: Compliance type of the service. Can be 'hipaa', 'pci'. Required for organizations that wish to deploy their services in the hipaa/pci compliant environment. NOTE: hipaa/pci compliance should be enabled for your ClickHouse organization before using this field.
        :param pulumi.Input[_builtins.str] double_sha1_password_hash: Double SHA1 hash of password for connecting with the MySQL protocol. Cannot be specified if `password` or `password_wo` is specified.
        :param pulumi.Input[_builtins.bool] enable_core_dumps: Enable core dumps for the service.
        :param pulumi.Input[_builtins.str] encryption_assumed_role_identifier: Custom role identifier ARN.
        :param pulumi.Input[_builtins.str] encryption_key: Custom encryption key ARN.
        :param pulumi.Input[Union['ServiceEndpointsArgs', 'ServiceEndpointsArgsDict']] endpoints: Allow to enable and configure additional endpoints (read protocols) to expose on the ClickHouse service.
        :param pulumi.Input[_builtins.bool] idle_scaling: When set to true the service is allowed to scale down to zero when idle.
        :param pulumi.Input[_builtins.int] idle_timeout_minutes: Set minimum idling timeout (in minutes). Must be greater than or equal to 5 minutes. Must be set if idle_scaling is enabled.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ServiceIpAccessArgs', 'ServiceIpAccessArgsDict']]]] ip_accesses: List of IP addresses allowed to access the service.
        :param pulumi.Input[_builtins.int] max_replica_memory_gb: Maximum memory of a single replica during auto-scaling in GiB.
        :param pulumi.Input[_builtins.int] max_total_memory_gb: Maximum total memory of all workers during auto-scaling in GiB.
        :param pulumi.Input[_builtins.int] min_replica_memory_gb: Minimum memory of a single replica during auto-scaling in GiB.
        :param pulumi.Input[_builtins.int] min_total_memory_gb: Minimum total memory of all workers during auto-scaling in GiB.
        :param pulumi.Input[_builtins.str] name: User defined identifier for the service.
        :param pulumi.Input[_builtins.int] num_replicas: Number of replicas for the service.
        :param pulumi.Input[_builtins.str] password: Password for the default user. One of either `password`, `password_wo`, or `password_hash` must be specified.
        :param pulumi.Input[_builtins.str] password_hash: SHA256 hash of password for the default user. One of either `password`, `password_wo`, or `password_hash` must be specified.
        :param pulumi.Input[_builtins.str] password_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               Password for the default user (write-only, not persisted to state). Use this instead of `password` to avoid storing the password hash in Terraform state.
        :param pulumi.Input[_builtins.int] password_wo_version: Version number for password*wo. Increment this to trigger a password update when using password*wo.
        :param pulumi.Input[Union['ServiceQueryApiEndpointsArgs', 'ServiceQueryApiEndpointsArgsDict']] query_api_endpoints: Configuration of the query API endpoints feature.
        :param pulumi.Input[_builtins.bool] readonly: Indicates if this service should be read only. Only allowed for secondary services, those which share data with another service (i.e. when `warehouse_id` field is set).
        :param pulumi.Input[_builtins.str] region: Region within the cloud provider in which the service is deployed in.
        :param pulumi.Input[_builtins.str] release_channel: Release channel to use for this service. Can be 'default', 'fast' or 'slow'.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Tags associated with the service as key-value pairs.
        :param pulumi.Input[_builtins.str] tier: Tier of the service: 'development', 'production'. Required for organizations using the Legacy ClickHouse Cloud Tiers, must be omitted for organizations using the new ClickHouse Cloud Tiers.
        :param pulumi.Input[Union['ServiceTransparentDataEncryptionArgs', 'ServiceTransparentDataEncryptionArgsDict']] transparent_data_encryption: Configuration of the Transparent Data Encryption (TDE) feature. Requires an organization with the Enterprise plan.
        :param pulumi.Input[_builtins.str] warehouse_id: Set it to the 'warehouse_id' attribute of another service to share the data with it. The service must be in the same cloud and region.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ServiceArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        You can use the *clickhouse_service* resource to deploy ClickHouse cloud instances on supported cloud providers.

        Known limitations:

        - If you create a service with `warehouse_id` set and then remove `warehouse_id` attribute completely, the provider won't detect the change. If you want to make a secondary service become primary, remove the `warehouse_id` and taint it before applying.
        - If you create a service with `readonly` flag set to true and then remove `readonly` flag completely, the provider won't detect the change. If you want to make a secondary service read write, explicitly set the `readonly` flag to false.

        ## Example Usage

        ```python
        import pulumi
        import pulumiverse_clickhouse as clickhouse

        service = clickhouse.Service("service",
            name="My Service",
            cloud_provider="aws",
            region="us-east-1",
            idle_scaling=True,
            ip_accesses=[{
                "source": "192.168.2.63",
                "description": "Test IP",
            }],
            tags={
                "Environment": "Staging",
            },
            min_total_memory_gb=24,
            max_total_memory_gb=360,
            idle_timeout_minutes=5,
            password_hash="n4bQgYhMfWWaL+qgxVrQFaO/TxsrC4Is0V1sFbDwCgg=")
        ```

        ## Import

        The `pulumi import` command can be used, for example:

        Services can be imported by specifying the UUID.

        ```sh
        $ pulumi import clickhouse:index/service:Service example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        ```


        :param str resource_name: The name of the resource.
        :param ServiceArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ServiceArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 backup_configuration: Optional[pulumi.Input[Union['ServiceBackupConfigurationArgs', 'ServiceBackupConfigurationArgsDict']]] = None,
                 backup_id: Optional[pulumi.Input[_builtins.str]] = None,
                 byoc_id: Optional[pulumi.Input[_builtins.str]] = None,
                 cloud_provider: Optional[pulumi.Input[_builtins.str]] = None,
                 compliance_type: Optional[pulumi.Input[_builtins.str]] = None,
                 double_sha1_password_hash: Optional[pulumi.Input[_builtins.str]] = None,
                 enable_core_dumps: Optional[pulumi.Input[_builtins.bool]] = None,
                 encryption_assumed_role_identifier: Optional[pulumi.Input[_builtins.str]] = None,
                 encryption_key: Optional[pulumi.Input[_builtins.str]] = None,
                 endpoints: Optional[pulumi.Input[Union['ServiceEndpointsArgs', 'ServiceEndpointsArgsDict']]] = None,
                 idle_scaling: Optional[pulumi.Input[_builtins.bool]] = None,
                 idle_timeout_minutes: Optional[pulumi.Input[_builtins.int]] = None,
                 ip_accesses: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ServiceIpAccessArgs', 'ServiceIpAccessArgsDict']]]]] = None,
                 max_replica_memory_gb: Optional[pulumi.Input[_builtins.int]] = None,
                 max_total_memory_gb: Optional[pulumi.Input[_builtins.int]] = None,
                 min_replica_memory_gb: Optional[pulumi.Input[_builtins.int]] = None,
                 min_total_memory_gb: Optional[pulumi.Input[_builtins.int]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 num_replicas: Optional[pulumi.Input[_builtins.int]] = None,
                 password: Optional[pulumi.Input[_builtins.str]] = None,
                 password_hash: Optional[pulumi.Input[_builtins.str]] = None,
                 password_wo: Optional[pulumi.Input[_builtins.str]] = None,
                 password_wo_version: Optional[pulumi.Input[_builtins.int]] = None,
                 query_api_endpoints: Optional[pulumi.Input[Union['ServiceQueryApiEndpointsArgs', 'ServiceQueryApiEndpointsArgsDict']]] = None,
                 readonly: Optional[pulumi.Input[_builtins.bool]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 release_channel: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 tier: Optional[pulumi.Input[_builtins.str]] = None,
                 transparent_data_encryption: Optional[pulumi.Input[Union['ServiceTransparentDataEncryptionArgs', 'ServiceTransparentDataEncryptionArgsDict']]] = None,
                 warehouse_id: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ServiceArgs.__new__(ServiceArgs)

            __props__.__dict__["backup_configuration"] = backup_configuration
            __props__.__dict__["backup_id"] = backup_id
            __props__.__dict__["byoc_id"] = byoc_id
            if cloud_provider is None and not opts.urn:
                raise TypeError("Missing required property 'cloud_provider'")
            __props__.__dict__["cloud_provider"] = cloud_provider
            __props__.__dict__["compliance_type"] = compliance_type
            __props__.__dict__["double_sha1_password_hash"] = None if double_sha1_password_hash is None else pulumi.Output.secret(double_sha1_password_hash)
            __props__.__dict__["enable_core_dumps"] = enable_core_dumps
            __props__.__dict__["encryption_assumed_role_identifier"] = encryption_assumed_role_identifier
            __props__.__dict__["encryption_key"] = encryption_key
            __props__.__dict__["endpoints"] = endpoints
            __props__.__dict__["idle_scaling"] = idle_scaling
            __props__.__dict__["idle_timeout_minutes"] = idle_timeout_minutes
            if ip_accesses is None and not opts.urn:
                raise TypeError("Missing required property 'ip_accesses'")
            __props__.__dict__["ip_accesses"] = ip_accesses
            __props__.__dict__["max_replica_memory_gb"] = max_replica_memory_gb
            __props__.__dict__["max_total_memory_gb"] = max_total_memory_gb
            __props__.__dict__["min_replica_memory_gb"] = min_replica_memory_gb
            __props__.__dict__["min_total_memory_gb"] = min_total_memory_gb
            __props__.__dict__["name"] = name
            __props__.__dict__["num_replicas"] = num_replicas
            __props__.__dict__["password"] = None if password is None else pulumi.Output.secret(password)
            __props__.__dict__["password_hash"] = None if password_hash is None else pulumi.Output.secret(password_hash)
            __props__.__dict__["password_wo"] = None if password_wo is None else pulumi.Output.secret(password_wo)
            __props__.__dict__["password_wo_version"] = password_wo_version
            __props__.__dict__["query_api_endpoints"] = query_api_endpoints
            __props__.__dict__["readonly"] = readonly
            if region is None and not opts.urn:
                raise TypeError("Missing required property 'region'")
            __props__.__dict__["region"] = region
            __props__.__dict__["release_channel"] = release_channel
            __props__.__dict__["tags"] = tags
            __props__.__dict__["tier"] = tier
            __props__.__dict__["transparent_data_encryption"] = transparent_data_encryption
            __props__.__dict__["warehouse_id"] = warehouse_id
            __props__.__dict__["iam_role"] = None
            __props__.__dict__["is_primary"] = None
            __props__.__dict__["private_endpoint_config"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["doubleSha1PasswordHash", "password", "passwordHash", "passwordWo"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Service, __self__).__init__(
            'clickhouse:index/service:Service',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            backup_configuration: Optional[pulumi.Input[Union['ServiceBackupConfigurationArgs', 'ServiceBackupConfigurationArgsDict']]] = None,
            backup_id: Optional[pulumi.Input[_builtins.str]] = None,
            byoc_id: Optional[pulumi.Input[_builtins.str]] = None,
            cloud_provider: Optional[pulumi.Input[_builtins.str]] = None,
            compliance_type: Optional[pulumi.Input[_builtins.str]] = None,
            double_sha1_password_hash: Optional[pulumi.Input[_builtins.str]] = None,
            enable_core_dumps: Optional[pulumi.Input[_builtins.bool]] = None,
            encryption_assumed_role_identifier: Optional[pulumi.Input[_builtins.str]] = None,
            encryption_key: Optional[pulumi.Input[_builtins.str]] = None,
            endpoints: Optional[pulumi.Input[Union['ServiceEndpointsArgs', 'ServiceEndpointsArgsDict']]] = None,
            iam_role: Optional[pulumi.Input[_builtins.str]] = None,
            idle_scaling: Optional[pulumi.Input[_builtins.bool]] = None,
            idle_timeout_minutes: Optional[pulumi.Input[_builtins.int]] = None,
            ip_accesses: Optional[pulumi.Input[Sequence[pulumi.Input[Union['ServiceIpAccessArgs', 'ServiceIpAccessArgsDict']]]]] = None,
            is_primary: Optional[pulumi.Input[_builtins.bool]] = None,
            max_replica_memory_gb: Optional[pulumi.Input[_builtins.int]] = None,
            max_total_memory_gb: Optional[pulumi.Input[_builtins.int]] = None,
            min_replica_memory_gb: Optional[pulumi.Input[_builtins.int]] = None,
            min_total_memory_gb: Optional[pulumi.Input[_builtins.int]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            num_replicas: Optional[pulumi.Input[_builtins.int]] = None,
            password: Optional[pulumi.Input[_builtins.str]] = None,
            password_hash: Optional[pulumi.Input[_builtins.str]] = None,
            password_wo: Optional[pulumi.Input[_builtins.str]] = None,
            password_wo_version: Optional[pulumi.Input[_builtins.int]] = None,
            private_endpoint_config: Optional[pulumi.Input[Union['ServicePrivateEndpointConfigArgs', 'ServicePrivateEndpointConfigArgsDict']]] = None,
            query_api_endpoints: Optional[pulumi.Input[Union['ServiceQueryApiEndpointsArgs', 'ServiceQueryApiEndpointsArgsDict']]] = None,
            readonly: Optional[pulumi.Input[_builtins.bool]] = None,
            region: Optional[pulumi.Input[_builtins.str]] = None,
            release_channel: Optional[pulumi.Input[_builtins.str]] = None,
            tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            tier: Optional[pulumi.Input[_builtins.str]] = None,
            transparent_data_encryption: Optional[pulumi.Input[Union['ServiceTransparentDataEncryptionArgs', 'ServiceTransparentDataEncryptionArgsDict']]] = None,
            warehouse_id: Optional[pulumi.Input[_builtins.str]] = None) -> 'Service':
        """
        Get an existing Service resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['ServiceBackupConfigurationArgs', 'ServiceBackupConfigurationArgsDict']] backup_configuration: Configuration of service backup settings.
        :param pulumi.Input[_builtins.str] backup_id: ID of the backup to restore when creating new service. If specified, the service will be created as a restore operation
        :param pulumi.Input[_builtins.str] byoc_id: BYOC ID related to the cloud provider account you want to create this service into.
        :param pulumi.Input[_builtins.str] cloud_provider: Cloud provider ('aws', 'gcp', or 'azure') in which the service is deployed in.
        :param pulumi.Input[_builtins.str] compliance_type: Compliance type of the service. Can be 'hipaa', 'pci'. Required for organizations that wish to deploy their services in the hipaa/pci compliant environment. NOTE: hipaa/pci compliance should be enabled for your ClickHouse organization before using this field.
        :param pulumi.Input[_builtins.str] double_sha1_password_hash: Double SHA1 hash of password for connecting with the MySQL protocol. Cannot be specified if `password` or `password_wo` is specified.
        :param pulumi.Input[_builtins.bool] enable_core_dumps: Enable core dumps for the service.
        :param pulumi.Input[_builtins.str] encryption_assumed_role_identifier: Custom role identifier ARN.
        :param pulumi.Input[_builtins.str] encryption_key: Custom encryption key ARN.
        :param pulumi.Input[Union['ServiceEndpointsArgs', 'ServiceEndpointsArgsDict']] endpoints: Allow to enable and configure additional endpoints (read protocols) to expose on the ClickHouse service.
        :param pulumi.Input[_builtins.str] iam_role: IAM role used for accessing objects in s3.
        :param pulumi.Input[_builtins.bool] idle_scaling: When set to true the service is allowed to scale down to zero when idle.
        :param pulumi.Input[_builtins.int] idle_timeout_minutes: Set minimum idling timeout (in minutes). Must be greater than or equal to 5 minutes. Must be set if idle_scaling is enabled.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ServiceIpAccessArgs', 'ServiceIpAccessArgsDict']]]] ip_accesses: List of IP addresses allowed to access the service.
        :param pulumi.Input[_builtins.bool] is_primary: If true, it indicates this is a primary service using its own data. If false it means this service is a secondary service, thus using data from a warehouse.
        :param pulumi.Input[_builtins.int] max_replica_memory_gb: Maximum memory of a single replica during auto-scaling in GiB.
        :param pulumi.Input[_builtins.int] max_total_memory_gb: Maximum total memory of all workers during auto-scaling in GiB.
        :param pulumi.Input[_builtins.int] min_replica_memory_gb: Minimum memory of a single replica during auto-scaling in GiB.
        :param pulumi.Input[_builtins.int] min_total_memory_gb: Minimum total memory of all workers during auto-scaling in GiB.
        :param pulumi.Input[_builtins.str] name: User defined identifier for the service.
        :param pulumi.Input[_builtins.int] num_replicas: Number of replicas for the service.
        :param pulumi.Input[_builtins.str] password: Password for the default user. One of either `password`, `password_wo`, or `password_hash` must be specified.
        :param pulumi.Input[_builtins.str] password_hash: SHA256 hash of password for the default user. One of either `password`, `password_wo`, or `password_hash` must be specified.
        :param pulumi.Input[_builtins.str] password_wo: **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
               Password for the default user (write-only, not persisted to state). Use this instead of `password` to avoid storing the password hash in Terraform state.
        :param pulumi.Input[_builtins.int] password_wo_version: Version number for password*wo. Increment this to trigger a password update when using password*wo.
        :param pulumi.Input[Union['ServicePrivateEndpointConfigArgs', 'ServicePrivateEndpointConfigArgsDict']] private_endpoint_config: Service config for private endpoints
        :param pulumi.Input[Union['ServiceQueryApiEndpointsArgs', 'ServiceQueryApiEndpointsArgsDict']] query_api_endpoints: Configuration of the query API endpoints feature.
        :param pulumi.Input[_builtins.bool] readonly: Indicates if this service should be read only. Only allowed for secondary services, those which share data with another service (i.e. when `warehouse_id` field is set).
        :param pulumi.Input[_builtins.str] region: Region within the cloud provider in which the service is deployed in.
        :param pulumi.Input[_builtins.str] release_channel: Release channel to use for this service. Can be 'default', 'fast' or 'slow'.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Tags associated with the service as key-value pairs.
        :param pulumi.Input[_builtins.str] tier: Tier of the service: 'development', 'production'. Required for organizations using the Legacy ClickHouse Cloud Tiers, must be omitted for organizations using the new ClickHouse Cloud Tiers.
        :param pulumi.Input[Union['ServiceTransparentDataEncryptionArgs', 'ServiceTransparentDataEncryptionArgsDict']] transparent_data_encryption: Configuration of the Transparent Data Encryption (TDE) feature. Requires an organization with the Enterprise plan.
        :param pulumi.Input[_builtins.str] warehouse_id: Set it to the 'warehouse_id' attribute of another service to share the data with it. The service must be in the same cloud and region.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ServiceState.__new__(_ServiceState)

        __props__.__dict__["backup_configuration"] = backup_configuration
        __props__.__dict__["backup_id"] = backup_id
        __props__.__dict__["byoc_id"] = byoc_id
        __props__.__dict__["cloud_provider"] = cloud_provider
        __props__.__dict__["compliance_type"] = compliance_type
        __props__.__dict__["double_sha1_password_hash"] = double_sha1_password_hash
        __props__.__dict__["enable_core_dumps"] = enable_core_dumps
        __props__.__dict__["encryption_assumed_role_identifier"] = encryption_assumed_role_identifier
        __props__.__dict__["encryption_key"] = encryption_key
        __props__.__dict__["endpoints"] = endpoints
        __props__.__dict__["iam_role"] = iam_role
        __props__.__dict__["idle_scaling"] = idle_scaling
        __props__.__dict__["idle_timeout_minutes"] = idle_timeout_minutes
        __props__.__dict__["ip_accesses"] = ip_accesses
        __props__.__dict__["is_primary"] = is_primary
        __props__.__dict__["max_replica_memory_gb"] = max_replica_memory_gb
        __props__.__dict__["max_total_memory_gb"] = max_total_memory_gb
        __props__.__dict__["min_replica_memory_gb"] = min_replica_memory_gb
        __props__.__dict__["min_total_memory_gb"] = min_total_memory_gb
        __props__.__dict__["name"] = name
        __props__.__dict__["num_replicas"] = num_replicas
        __props__.__dict__["password"] = password
        __props__.__dict__["password_hash"] = password_hash
        __props__.__dict__["password_wo"] = password_wo
        __props__.__dict__["password_wo_version"] = password_wo_version
        __props__.__dict__["private_endpoint_config"] = private_endpoint_config
        __props__.__dict__["query_api_endpoints"] = query_api_endpoints
        __props__.__dict__["readonly"] = readonly
        __props__.__dict__["region"] = region
        __props__.__dict__["release_channel"] = release_channel
        __props__.__dict__["tags"] = tags
        __props__.__dict__["tier"] = tier
        __props__.__dict__["transparent_data_encryption"] = transparent_data_encryption
        __props__.__dict__["warehouse_id"] = warehouse_id
        return Service(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="backupConfiguration")
    def backup_configuration(self) -> pulumi.Output['outputs.ServiceBackupConfiguration']:
        """
        Configuration of service backup settings.
        """
        return pulumi.get(self, "backup_configuration")

    @_builtins.property
    @pulumi.getter(name="backupId")
    def backup_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        ID of the backup to restore when creating new service. If specified, the service will be created as a restore operation
        """
        return pulumi.get(self, "backup_id")

    @_builtins.property
    @pulumi.getter(name="byocId")
    def byoc_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        BYOC ID related to the cloud provider account you want to create this service into.
        """
        return pulumi.get(self, "byoc_id")

    @_builtins.property
    @pulumi.getter(name="cloudProvider")
    def cloud_provider(self) -> pulumi.Output[_builtins.str]:
        """
        Cloud provider ('aws', 'gcp', or 'azure') in which the service is deployed in.
        """
        return pulumi.get(self, "cloud_provider")

    @_builtins.property
    @pulumi.getter(name="complianceType")
    def compliance_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Compliance type of the service. Can be 'hipaa', 'pci'. Required for organizations that wish to deploy their services in the hipaa/pci compliant environment. NOTE: hipaa/pci compliance should be enabled for your ClickHouse organization before using this field.
        """
        return pulumi.get(self, "compliance_type")

    @_builtins.property
    @pulumi.getter(name="doubleSha1PasswordHash")
    def double_sha1_password_hash(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Double SHA1 hash of password for connecting with the MySQL protocol. Cannot be specified if `password` or `password_wo` is specified.
        """
        return pulumi.get(self, "double_sha1_password_hash")

    @_builtins.property
    @pulumi.getter(name="enableCoreDumps")
    def enable_core_dumps(self) -> pulumi.Output[_builtins.bool]:
        """
        Enable core dumps for the service.
        """
        return pulumi.get(self, "enable_core_dumps")

    @_builtins.property
    @pulumi.getter(name="encryptionAssumedRoleIdentifier")
    def encryption_assumed_role_identifier(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Custom role identifier ARN.
        """
        return pulumi.get(self, "encryption_assumed_role_identifier")

    @_builtins.property
    @pulumi.getter(name="encryptionKey")
    def encryption_key(self) -> pulumi.Output[_builtins.str]:
        """
        Custom encryption key ARN.
        """
        return pulumi.get(self, "encryption_key")

    @_builtins.property
    @pulumi.getter
    def endpoints(self) -> pulumi.Output['outputs.ServiceEndpoints']:
        """
        Allow to enable and configure additional endpoints (read protocols) to expose on the ClickHouse service.
        """
        return pulumi.get(self, "endpoints")

    @_builtins.property
    @pulumi.getter(name="iamRole")
    def iam_role(self) -> pulumi.Output[_builtins.str]:
        """
        IAM role used for accessing objects in s3.
        """
        return pulumi.get(self, "iam_role")

    @_builtins.property
    @pulumi.getter(name="idleScaling")
    def idle_scaling(self) -> pulumi.Output[_builtins.bool]:
        """
        When set to true the service is allowed to scale down to zero when idle.
        """
        return pulumi.get(self, "idle_scaling")

    @_builtins.property
    @pulumi.getter(name="idleTimeoutMinutes")
    def idle_timeout_minutes(self) -> pulumi.Output[_builtins.int]:
        """
        Set minimum idling timeout (in minutes). Must be greater than or equal to 5 minutes. Must be set if idle_scaling is enabled.
        """
        return pulumi.get(self, "idle_timeout_minutes")

    @_builtins.property
    @pulumi.getter(name="ipAccesses")
    def ip_accesses(self) -> pulumi.Output[Sequence['outputs.ServiceIpAccess']]:
        """
        List of IP addresses allowed to access the service.
        """
        return pulumi.get(self, "ip_accesses")

    @_builtins.property
    @pulumi.getter(name="isPrimary")
    def is_primary(self) -> pulumi.Output[_builtins.bool]:
        """
        If true, it indicates this is a primary service using its own data. If false it means this service is a secondary service, thus using data from a warehouse.
        """
        return pulumi.get(self, "is_primary")

    @_builtins.property
    @pulumi.getter(name="maxReplicaMemoryGb")
    def max_replica_memory_gb(self) -> pulumi.Output[_builtins.int]:
        """
        Maximum memory of a single replica during auto-scaling in GiB.
        """
        return pulumi.get(self, "max_replica_memory_gb")

    @_builtins.property
    @pulumi.getter(name="maxTotalMemoryGb")
    @_utilities.deprecated("""Please use max_replica_memory_gb instead""")
    def max_total_memory_gb(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Maximum total memory of all workers during auto-scaling in GiB.
        """
        return pulumi.get(self, "max_total_memory_gb")

    @_builtins.property
    @pulumi.getter(name="minReplicaMemoryGb")
    def min_replica_memory_gb(self) -> pulumi.Output[_builtins.int]:
        """
        Minimum memory of a single replica during auto-scaling in GiB.
        """
        return pulumi.get(self, "min_replica_memory_gb")

    @_builtins.property
    @pulumi.getter(name="minTotalMemoryGb")
    @_utilities.deprecated("""Please use min_replica_memory_gb instead""")
    def min_total_memory_gb(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Minimum total memory of all workers during auto-scaling in GiB.
        """
        return pulumi.get(self, "min_total_memory_gb")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        User defined identifier for the service.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="numReplicas")
    def num_replicas(self) -> pulumi.Output[_builtins.int]:
        """
        Number of replicas for the service.
        """
        return pulumi.get(self, "num_replicas")

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Password for the default user. One of either `password`, `password_wo`, or `password_hash` must be specified.
        """
        return pulumi.get(self, "password")

    @_builtins.property
    @pulumi.getter(name="passwordHash")
    def password_hash(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        SHA256 hash of password for the default user. One of either `password`, `password_wo`, or `password_hash` must be specified.
        """
        return pulumi.get(self, "password_hash")

    @_builtins.property
    @pulumi.getter(name="passwordWo")
    def password_wo(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        Password for the default user (write-only, not persisted to state). Use this instead of `password` to avoid storing the password hash in Terraform state.
        """
        return pulumi.get(self, "password_wo")

    @_builtins.property
    @pulumi.getter(name="passwordWoVersion")
    def password_wo_version(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Version number for password*wo. Increment this to trigger a password update when using password*wo.
        """
        return pulumi.get(self, "password_wo_version")

    @_builtins.property
    @pulumi.getter(name="privateEndpointConfig")
    def private_endpoint_config(self) -> pulumi.Output['outputs.ServicePrivateEndpointConfig']:
        """
        Service config for private endpoints
        """
        return pulumi.get(self, "private_endpoint_config")

    @_builtins.property
    @pulumi.getter(name="queryApiEndpoints")
    def query_api_endpoints(self) -> pulumi.Output[Optional['outputs.ServiceQueryApiEndpoints']]:
        """
        Configuration of the query API endpoints feature.
        """
        return pulumi.get(self, "query_api_endpoints")

    @_builtins.property
    @pulumi.getter
    def readonly(self) -> pulumi.Output[_builtins.bool]:
        """
        Indicates if this service should be read only. Only allowed for secondary services, those which share data with another service (i.e. when `warehouse_id` field is set).
        """
        return pulumi.get(self, "readonly")

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Output[_builtins.str]:
        """
        Region within the cloud provider in which the service is deployed in.
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="releaseChannel")
    def release_channel(self) -> pulumi.Output[_builtins.str]:
        """
        Release channel to use for this service. Can be 'default', 'fast' or 'slow'.
        """
        return pulumi.get(self, "release_channel")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Tags associated with the service as key-value pairs.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter
    def tier(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Tier of the service: 'development', 'production'. Required for organizations using the Legacy ClickHouse Cloud Tiers, must be omitted for organizations using the new ClickHouse Cloud Tiers.
        """
        return pulumi.get(self, "tier")

    @_builtins.property
    @pulumi.getter(name="transparentDataEncryption")
    def transparent_data_encryption(self) -> pulumi.Output['outputs.ServiceTransparentDataEncryption']:
        """
        Configuration of the Transparent Data Encryption (TDE) feature. Requires an organization with the Enterprise plan.
        """
        return pulumi.get(self, "transparent_data_encryption")

    @_builtins.property
    @pulumi.getter(name="warehouseId")
    def warehouse_id(self) -> pulumi.Output[_builtins.str]:
        """
        Set it to the 'warehouse_id' attribute of another service to share the data with it. The service must be in the same cloud and region.
        """
        return pulumi.get(self, "warehouse_id")

