# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'GetConfigResult',
    'AwaitableGetConfigResult',
    'get_config',
    'get_config_output',
]

@pulumi.output_type
class GetConfigResult:
    """
    A collection of values returned by getConfig.
    """
    def __init__(__self__, cloud_provider=None, endpoint_service_id=None, id=None, region=None):
        if cloud_provider and not isinstance(cloud_provider, str):
            raise TypeError("Expected argument 'cloud_provider' to be a str")
        pulumi.set(__self__, "cloud_provider", cloud_provider)
        if endpoint_service_id and not isinstance(endpoint_service_id, str):
            raise TypeError("Expected argument 'endpoint_service_id' to be a str")
        pulumi.set(__self__, "endpoint_service_id", endpoint_service_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        pulumi.set(__self__, "region", region)

    @_builtins.property
    @pulumi.getter(name="cloudProvider")
    def cloud_provider(self) -> _builtins.str:
        """
        The cloud provider for the private endpoint. Valid values are 'aws', 'gcp', or 'azure'.
        """
        return pulumi.get(self, "cloud_provider")

    @_builtins.property
    @pulumi.getter(name="endpointServiceId")
    def endpoint_service_id(self) -> _builtins.str:
        """
        The ID of the private endpoint that is used to securely connect to ClickHouse. This is a read-only attribute.
        """
        return pulumi.get(self, "endpoint_service_id")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def region(self) -> _builtins.str:
        """
        The region for the private endpoint. Valid values are specific to the cloud provider i.e. us-east-2
        """
        return pulumi.get(self, "region")


class AwaitableGetConfigResult(GetConfigResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetConfigResult(
            cloud_provider=self.cloud_provider,
            endpoint_service_id=self.endpoint_service_id,
            id=self.id,
            region=self.region)


def get_config(cloud_provider: Optional[_builtins.str] = None,
               region: Optional[_builtins.str] = None,
               opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetConfigResult:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str cloud_provider: The cloud provider for the private endpoint. Valid values are 'aws', 'gcp', or 'azure'.
    :param _builtins.str region: The region for the private endpoint. Valid values are specific to the cloud provider i.e. us-east-2
    """
    __args__ = dict()
    __args__['cloudProvider'] = cloud_provider
    __args__['region'] = region
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('clickhouse:PrivateEndpoint/getConfig:getConfig', __args__, opts=opts, typ=GetConfigResult).value

    return AwaitableGetConfigResult(
        cloud_provider=pulumi.get(__ret__, 'cloud_provider'),
        endpoint_service_id=pulumi.get(__ret__, 'endpoint_service_id'),
        id=pulumi.get(__ret__, 'id'),
        region=pulumi.get(__ret__, 'region'))
def get_config_output(cloud_provider: Optional[pulumi.Input[_builtins.str]] = None,
                      region: Optional[pulumi.Input[_builtins.str]] = None,
                      opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetConfigResult]:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str cloud_provider: The cloud provider for the private endpoint. Valid values are 'aws', 'gcp', or 'azure'.
    :param _builtins.str region: The region for the private endpoint. Valid values are specific to the cloud provider i.e. us-east-2
    """
    __args__ = dict()
    __args__['cloudProvider'] = cloud_provider
    __args__['region'] = region
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('clickhouse:PrivateEndpoint/getConfig:getConfig', __args__, opts=opts, typ=GetConfigResult)
    return __ret__.apply(lambda __response__: GetConfigResult(
        cloud_provider=pulumi.get(__response__, 'cloud_provider'),
        endpoint_service_id=pulumi.get(__response__, 'endpoint_service_id'),
        id=pulumi.get(__response__, 'id'),
        region=pulumi.get(__response__, 'region')))
