// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ServiceEndpoint {
    /**
     * Endpoint host.
     */
    host?: pulumi.Input<string>;
    /**
     * Endpoint port.
     */
    port?: pulumi.Input<number>;
    /**
     * Endpoint protocol: https or nativesecure
     */
    protocol?: pulumi.Input<string>;
}

export interface ServiceIpAccess {
    /**
     * Description of the IP address.
     */
    description?: pulumi.Input<string>;
    /**
     * IP address allowed to access the service. In case you want to set the ipAccess to anywhere you should set source to 0.0.0.0/0
     */
    source: pulumi.Input<string>;
}

export interface ServicePrivateEndpointConfig {
    /**
     * Unique identifier of the interface endpoint you created in your VPC with the AWS(Service Name) or GCP(Target Service) resource
     */
    endpointServiceId?: pulumi.Input<string>;
    /**
     * Private DNS Hostname of the VPC you created
     */
    privateDnsHostname?: pulumi.Input<string>;
}
