// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package clickhouse

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-clickhouse/sdk/go/clickhouse/internal"
)

var _ = internal.GetEnvOrDefault

type ServiceBackupConfiguration struct {
	// Interval in hours between each backup.
	BackupPeriodInHours *int `pulumi:"backupPeriodInHours"`
	// How long in hours to keep a backup before deleting it.
	BackupRetentionPeriodInHours *int `pulumi:"backupRetentionPeriodInHours"`
	// Time of the day in UTC that indicates the start time of a 2 hours window to be used for backup. If set, backup*period*in_hours must be null and backups are created once a day.
	BackupStartTime *string `pulumi:"backupStartTime"`
}

// ServiceBackupConfigurationInput is an input type that accepts ServiceBackupConfigurationArgs and ServiceBackupConfigurationOutput values.
// You can construct a concrete instance of `ServiceBackupConfigurationInput` via:
//
//	ServiceBackupConfigurationArgs{...}
type ServiceBackupConfigurationInput interface {
	pulumi.Input

	ToServiceBackupConfigurationOutput() ServiceBackupConfigurationOutput
	ToServiceBackupConfigurationOutputWithContext(context.Context) ServiceBackupConfigurationOutput
}

type ServiceBackupConfigurationArgs struct {
	// Interval in hours between each backup.
	BackupPeriodInHours pulumi.IntPtrInput `pulumi:"backupPeriodInHours"`
	// How long in hours to keep a backup before deleting it.
	BackupRetentionPeriodInHours pulumi.IntPtrInput `pulumi:"backupRetentionPeriodInHours"`
	// Time of the day in UTC that indicates the start time of a 2 hours window to be used for backup. If set, backup*period*in_hours must be null and backups are created once a day.
	BackupStartTime pulumi.StringPtrInput `pulumi:"backupStartTime"`
}

func (ServiceBackupConfigurationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceBackupConfiguration)(nil)).Elem()
}

func (i ServiceBackupConfigurationArgs) ToServiceBackupConfigurationOutput() ServiceBackupConfigurationOutput {
	return i.ToServiceBackupConfigurationOutputWithContext(context.Background())
}

func (i ServiceBackupConfigurationArgs) ToServiceBackupConfigurationOutputWithContext(ctx context.Context) ServiceBackupConfigurationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceBackupConfigurationOutput)
}

func (i ServiceBackupConfigurationArgs) ToServiceBackupConfigurationPtrOutput() ServiceBackupConfigurationPtrOutput {
	return i.ToServiceBackupConfigurationPtrOutputWithContext(context.Background())
}

func (i ServiceBackupConfigurationArgs) ToServiceBackupConfigurationPtrOutputWithContext(ctx context.Context) ServiceBackupConfigurationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceBackupConfigurationOutput).ToServiceBackupConfigurationPtrOutputWithContext(ctx)
}

// ServiceBackupConfigurationPtrInput is an input type that accepts ServiceBackupConfigurationArgs, ServiceBackupConfigurationPtr and ServiceBackupConfigurationPtrOutput values.
// You can construct a concrete instance of `ServiceBackupConfigurationPtrInput` via:
//
//	        ServiceBackupConfigurationArgs{...}
//
//	or:
//
//	        nil
type ServiceBackupConfigurationPtrInput interface {
	pulumi.Input

	ToServiceBackupConfigurationPtrOutput() ServiceBackupConfigurationPtrOutput
	ToServiceBackupConfigurationPtrOutputWithContext(context.Context) ServiceBackupConfigurationPtrOutput
}

type serviceBackupConfigurationPtrType ServiceBackupConfigurationArgs

func ServiceBackupConfigurationPtr(v *ServiceBackupConfigurationArgs) ServiceBackupConfigurationPtrInput {
	return (*serviceBackupConfigurationPtrType)(v)
}

func (*serviceBackupConfigurationPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceBackupConfiguration)(nil)).Elem()
}

func (i *serviceBackupConfigurationPtrType) ToServiceBackupConfigurationPtrOutput() ServiceBackupConfigurationPtrOutput {
	return i.ToServiceBackupConfigurationPtrOutputWithContext(context.Background())
}

func (i *serviceBackupConfigurationPtrType) ToServiceBackupConfigurationPtrOutputWithContext(ctx context.Context) ServiceBackupConfigurationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceBackupConfigurationPtrOutput)
}

type ServiceBackupConfigurationOutput struct{ *pulumi.OutputState }

func (ServiceBackupConfigurationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceBackupConfiguration)(nil)).Elem()
}

func (o ServiceBackupConfigurationOutput) ToServiceBackupConfigurationOutput() ServiceBackupConfigurationOutput {
	return o
}

func (o ServiceBackupConfigurationOutput) ToServiceBackupConfigurationOutputWithContext(ctx context.Context) ServiceBackupConfigurationOutput {
	return o
}

func (o ServiceBackupConfigurationOutput) ToServiceBackupConfigurationPtrOutput() ServiceBackupConfigurationPtrOutput {
	return o.ToServiceBackupConfigurationPtrOutputWithContext(context.Background())
}

func (o ServiceBackupConfigurationOutput) ToServiceBackupConfigurationPtrOutputWithContext(ctx context.Context) ServiceBackupConfigurationPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ServiceBackupConfiguration) *ServiceBackupConfiguration {
		return &v
	}).(ServiceBackupConfigurationPtrOutput)
}

// Interval in hours between each backup.
func (o ServiceBackupConfigurationOutput) BackupPeriodInHours() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ServiceBackupConfiguration) *int { return v.BackupPeriodInHours }).(pulumi.IntPtrOutput)
}

// How long in hours to keep a backup before deleting it.
func (o ServiceBackupConfigurationOutput) BackupRetentionPeriodInHours() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ServiceBackupConfiguration) *int { return v.BackupRetentionPeriodInHours }).(pulumi.IntPtrOutput)
}

// Time of the day in UTC that indicates the start time of a 2 hours window to be used for backup. If set, backup*period*in_hours must be null and backups are created once a day.
func (o ServiceBackupConfigurationOutput) BackupStartTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ServiceBackupConfiguration) *string { return v.BackupStartTime }).(pulumi.StringPtrOutput)
}

type ServiceBackupConfigurationPtrOutput struct{ *pulumi.OutputState }

func (ServiceBackupConfigurationPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceBackupConfiguration)(nil)).Elem()
}

func (o ServiceBackupConfigurationPtrOutput) ToServiceBackupConfigurationPtrOutput() ServiceBackupConfigurationPtrOutput {
	return o
}

func (o ServiceBackupConfigurationPtrOutput) ToServiceBackupConfigurationPtrOutputWithContext(ctx context.Context) ServiceBackupConfigurationPtrOutput {
	return o
}

func (o ServiceBackupConfigurationPtrOutput) Elem() ServiceBackupConfigurationOutput {
	return o.ApplyT(func(v *ServiceBackupConfiguration) ServiceBackupConfiguration {
		if v != nil {
			return *v
		}
		var ret ServiceBackupConfiguration
		return ret
	}).(ServiceBackupConfigurationOutput)
}

// Interval in hours between each backup.
func (o ServiceBackupConfigurationPtrOutput) BackupPeriodInHours() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ServiceBackupConfiguration) *int {
		if v == nil {
			return nil
		}
		return v.BackupPeriodInHours
	}).(pulumi.IntPtrOutput)
}

// How long in hours to keep a backup before deleting it.
func (o ServiceBackupConfigurationPtrOutput) BackupRetentionPeriodInHours() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ServiceBackupConfiguration) *int {
		if v == nil {
			return nil
		}
		return v.BackupRetentionPeriodInHours
	}).(pulumi.IntPtrOutput)
}

// Time of the day in UTC that indicates the start time of a 2 hours window to be used for backup. If set, backup*period*in_hours must be null and backups are created once a day.
func (o ServiceBackupConfigurationPtrOutput) BackupStartTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServiceBackupConfiguration) *string {
		if v == nil {
			return nil
		}
		return v.BackupStartTime
	}).(pulumi.StringPtrOutput)
}

type ServiceEndpoints struct {
	Https        *ServiceEndpointsHttps        `pulumi:"https"`
	Mysql        *ServiceEndpointsMysql        `pulumi:"mysql"`
	Nativesecure *ServiceEndpointsNativesecure `pulumi:"nativesecure"`
}

// ServiceEndpointsInput is an input type that accepts ServiceEndpointsArgs and ServiceEndpointsOutput values.
// You can construct a concrete instance of `ServiceEndpointsInput` via:
//
//	ServiceEndpointsArgs{...}
type ServiceEndpointsInput interface {
	pulumi.Input

	ToServiceEndpointsOutput() ServiceEndpointsOutput
	ToServiceEndpointsOutputWithContext(context.Context) ServiceEndpointsOutput
}

type ServiceEndpointsArgs struct {
	Https        ServiceEndpointsHttpsPtrInput        `pulumi:"https"`
	Mysql        ServiceEndpointsMysqlPtrInput        `pulumi:"mysql"`
	Nativesecure ServiceEndpointsNativesecurePtrInput `pulumi:"nativesecure"`
}

func (ServiceEndpointsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceEndpoints)(nil)).Elem()
}

func (i ServiceEndpointsArgs) ToServiceEndpointsOutput() ServiceEndpointsOutput {
	return i.ToServiceEndpointsOutputWithContext(context.Background())
}

func (i ServiceEndpointsArgs) ToServiceEndpointsOutputWithContext(ctx context.Context) ServiceEndpointsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceEndpointsOutput)
}

func (i ServiceEndpointsArgs) ToServiceEndpointsPtrOutput() ServiceEndpointsPtrOutput {
	return i.ToServiceEndpointsPtrOutputWithContext(context.Background())
}

func (i ServiceEndpointsArgs) ToServiceEndpointsPtrOutputWithContext(ctx context.Context) ServiceEndpointsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceEndpointsOutput).ToServiceEndpointsPtrOutputWithContext(ctx)
}

// ServiceEndpointsPtrInput is an input type that accepts ServiceEndpointsArgs, ServiceEndpointsPtr and ServiceEndpointsPtrOutput values.
// You can construct a concrete instance of `ServiceEndpointsPtrInput` via:
//
//	        ServiceEndpointsArgs{...}
//
//	or:
//
//	        nil
type ServiceEndpointsPtrInput interface {
	pulumi.Input

	ToServiceEndpointsPtrOutput() ServiceEndpointsPtrOutput
	ToServiceEndpointsPtrOutputWithContext(context.Context) ServiceEndpointsPtrOutput
}

type serviceEndpointsPtrType ServiceEndpointsArgs

func ServiceEndpointsPtr(v *ServiceEndpointsArgs) ServiceEndpointsPtrInput {
	return (*serviceEndpointsPtrType)(v)
}

func (*serviceEndpointsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceEndpoints)(nil)).Elem()
}

func (i *serviceEndpointsPtrType) ToServiceEndpointsPtrOutput() ServiceEndpointsPtrOutput {
	return i.ToServiceEndpointsPtrOutputWithContext(context.Background())
}

func (i *serviceEndpointsPtrType) ToServiceEndpointsPtrOutputWithContext(ctx context.Context) ServiceEndpointsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceEndpointsPtrOutput)
}

type ServiceEndpointsOutput struct{ *pulumi.OutputState }

func (ServiceEndpointsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceEndpoints)(nil)).Elem()
}

func (o ServiceEndpointsOutput) ToServiceEndpointsOutput() ServiceEndpointsOutput {
	return o
}

func (o ServiceEndpointsOutput) ToServiceEndpointsOutputWithContext(ctx context.Context) ServiceEndpointsOutput {
	return o
}

func (o ServiceEndpointsOutput) ToServiceEndpointsPtrOutput() ServiceEndpointsPtrOutput {
	return o.ToServiceEndpointsPtrOutputWithContext(context.Background())
}

func (o ServiceEndpointsOutput) ToServiceEndpointsPtrOutputWithContext(ctx context.Context) ServiceEndpointsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ServiceEndpoints) *ServiceEndpoints {
		return &v
	}).(ServiceEndpointsPtrOutput)
}

func (o ServiceEndpointsOutput) Https() ServiceEndpointsHttpsPtrOutput {
	return o.ApplyT(func(v ServiceEndpoints) *ServiceEndpointsHttps { return v.Https }).(ServiceEndpointsHttpsPtrOutput)
}

func (o ServiceEndpointsOutput) Mysql() ServiceEndpointsMysqlPtrOutput {
	return o.ApplyT(func(v ServiceEndpoints) *ServiceEndpointsMysql { return v.Mysql }).(ServiceEndpointsMysqlPtrOutput)
}

func (o ServiceEndpointsOutput) Nativesecure() ServiceEndpointsNativesecurePtrOutput {
	return o.ApplyT(func(v ServiceEndpoints) *ServiceEndpointsNativesecure { return v.Nativesecure }).(ServiceEndpointsNativesecurePtrOutput)
}

type ServiceEndpointsPtrOutput struct{ *pulumi.OutputState }

func (ServiceEndpointsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceEndpoints)(nil)).Elem()
}

func (o ServiceEndpointsPtrOutput) ToServiceEndpointsPtrOutput() ServiceEndpointsPtrOutput {
	return o
}

func (o ServiceEndpointsPtrOutput) ToServiceEndpointsPtrOutputWithContext(ctx context.Context) ServiceEndpointsPtrOutput {
	return o
}

func (o ServiceEndpointsPtrOutput) Elem() ServiceEndpointsOutput {
	return o.ApplyT(func(v *ServiceEndpoints) ServiceEndpoints {
		if v != nil {
			return *v
		}
		var ret ServiceEndpoints
		return ret
	}).(ServiceEndpointsOutput)
}

func (o ServiceEndpointsPtrOutput) Https() ServiceEndpointsHttpsPtrOutput {
	return o.ApplyT(func(v *ServiceEndpoints) *ServiceEndpointsHttps {
		if v == nil {
			return nil
		}
		return v.Https
	}).(ServiceEndpointsHttpsPtrOutput)
}

func (o ServiceEndpointsPtrOutput) Mysql() ServiceEndpointsMysqlPtrOutput {
	return o.ApplyT(func(v *ServiceEndpoints) *ServiceEndpointsMysql {
		if v == nil {
			return nil
		}
		return v.Mysql
	}).(ServiceEndpointsMysqlPtrOutput)
}

func (o ServiceEndpointsPtrOutput) Nativesecure() ServiceEndpointsNativesecurePtrOutput {
	return o.ApplyT(func(v *ServiceEndpoints) *ServiceEndpointsNativesecure {
		if v == nil {
			return nil
		}
		return v.Nativesecure
	}).(ServiceEndpointsNativesecurePtrOutput)
}

type ServiceEndpointsHttps struct {
	// Endpoint host.
	Host *string `pulumi:"host"`
	// Endpoint port.
	Port *int `pulumi:"port"`
}

// ServiceEndpointsHttpsInput is an input type that accepts ServiceEndpointsHttpsArgs and ServiceEndpointsHttpsOutput values.
// You can construct a concrete instance of `ServiceEndpointsHttpsInput` via:
//
//	ServiceEndpointsHttpsArgs{...}
type ServiceEndpointsHttpsInput interface {
	pulumi.Input

	ToServiceEndpointsHttpsOutput() ServiceEndpointsHttpsOutput
	ToServiceEndpointsHttpsOutputWithContext(context.Context) ServiceEndpointsHttpsOutput
}

type ServiceEndpointsHttpsArgs struct {
	// Endpoint host.
	Host pulumi.StringPtrInput `pulumi:"host"`
	// Endpoint port.
	Port pulumi.IntPtrInput `pulumi:"port"`
}

func (ServiceEndpointsHttpsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceEndpointsHttps)(nil)).Elem()
}

func (i ServiceEndpointsHttpsArgs) ToServiceEndpointsHttpsOutput() ServiceEndpointsHttpsOutput {
	return i.ToServiceEndpointsHttpsOutputWithContext(context.Background())
}

func (i ServiceEndpointsHttpsArgs) ToServiceEndpointsHttpsOutputWithContext(ctx context.Context) ServiceEndpointsHttpsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceEndpointsHttpsOutput)
}

func (i ServiceEndpointsHttpsArgs) ToServiceEndpointsHttpsPtrOutput() ServiceEndpointsHttpsPtrOutput {
	return i.ToServiceEndpointsHttpsPtrOutputWithContext(context.Background())
}

func (i ServiceEndpointsHttpsArgs) ToServiceEndpointsHttpsPtrOutputWithContext(ctx context.Context) ServiceEndpointsHttpsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceEndpointsHttpsOutput).ToServiceEndpointsHttpsPtrOutputWithContext(ctx)
}

// ServiceEndpointsHttpsPtrInput is an input type that accepts ServiceEndpointsHttpsArgs, ServiceEndpointsHttpsPtr and ServiceEndpointsHttpsPtrOutput values.
// You can construct a concrete instance of `ServiceEndpointsHttpsPtrInput` via:
//
//	        ServiceEndpointsHttpsArgs{...}
//
//	or:
//
//	        nil
type ServiceEndpointsHttpsPtrInput interface {
	pulumi.Input

	ToServiceEndpointsHttpsPtrOutput() ServiceEndpointsHttpsPtrOutput
	ToServiceEndpointsHttpsPtrOutputWithContext(context.Context) ServiceEndpointsHttpsPtrOutput
}

type serviceEndpointsHttpsPtrType ServiceEndpointsHttpsArgs

func ServiceEndpointsHttpsPtr(v *ServiceEndpointsHttpsArgs) ServiceEndpointsHttpsPtrInput {
	return (*serviceEndpointsHttpsPtrType)(v)
}

func (*serviceEndpointsHttpsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceEndpointsHttps)(nil)).Elem()
}

func (i *serviceEndpointsHttpsPtrType) ToServiceEndpointsHttpsPtrOutput() ServiceEndpointsHttpsPtrOutput {
	return i.ToServiceEndpointsHttpsPtrOutputWithContext(context.Background())
}

func (i *serviceEndpointsHttpsPtrType) ToServiceEndpointsHttpsPtrOutputWithContext(ctx context.Context) ServiceEndpointsHttpsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceEndpointsHttpsPtrOutput)
}

type ServiceEndpointsHttpsOutput struct{ *pulumi.OutputState }

func (ServiceEndpointsHttpsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceEndpointsHttps)(nil)).Elem()
}

func (o ServiceEndpointsHttpsOutput) ToServiceEndpointsHttpsOutput() ServiceEndpointsHttpsOutput {
	return o
}

func (o ServiceEndpointsHttpsOutput) ToServiceEndpointsHttpsOutputWithContext(ctx context.Context) ServiceEndpointsHttpsOutput {
	return o
}

func (o ServiceEndpointsHttpsOutput) ToServiceEndpointsHttpsPtrOutput() ServiceEndpointsHttpsPtrOutput {
	return o.ToServiceEndpointsHttpsPtrOutputWithContext(context.Background())
}

func (o ServiceEndpointsHttpsOutput) ToServiceEndpointsHttpsPtrOutputWithContext(ctx context.Context) ServiceEndpointsHttpsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ServiceEndpointsHttps) *ServiceEndpointsHttps {
		return &v
	}).(ServiceEndpointsHttpsPtrOutput)
}

// Endpoint host.
func (o ServiceEndpointsHttpsOutput) Host() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ServiceEndpointsHttps) *string { return v.Host }).(pulumi.StringPtrOutput)
}

// Endpoint port.
func (o ServiceEndpointsHttpsOutput) Port() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ServiceEndpointsHttps) *int { return v.Port }).(pulumi.IntPtrOutput)
}

type ServiceEndpointsHttpsPtrOutput struct{ *pulumi.OutputState }

func (ServiceEndpointsHttpsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceEndpointsHttps)(nil)).Elem()
}

func (o ServiceEndpointsHttpsPtrOutput) ToServiceEndpointsHttpsPtrOutput() ServiceEndpointsHttpsPtrOutput {
	return o
}

func (o ServiceEndpointsHttpsPtrOutput) ToServiceEndpointsHttpsPtrOutputWithContext(ctx context.Context) ServiceEndpointsHttpsPtrOutput {
	return o
}

func (o ServiceEndpointsHttpsPtrOutput) Elem() ServiceEndpointsHttpsOutput {
	return o.ApplyT(func(v *ServiceEndpointsHttps) ServiceEndpointsHttps {
		if v != nil {
			return *v
		}
		var ret ServiceEndpointsHttps
		return ret
	}).(ServiceEndpointsHttpsOutput)
}

// Endpoint host.
func (o ServiceEndpointsHttpsPtrOutput) Host() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServiceEndpointsHttps) *string {
		if v == nil {
			return nil
		}
		return v.Host
	}).(pulumi.StringPtrOutput)
}

// Endpoint port.
func (o ServiceEndpointsHttpsPtrOutput) Port() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ServiceEndpointsHttps) *int {
		if v == nil {
			return nil
		}
		return v.Port
	}).(pulumi.IntPtrOutput)
}

type ServiceEndpointsMysql struct {
	// Wether to enable the mysql endpoint or not.
	Enabled bool `pulumi:"enabled"`
	// Endpoint host.
	Host *string `pulumi:"host"`
	// Endpoint port.
	Port *int `pulumi:"port"`
}

// ServiceEndpointsMysqlInput is an input type that accepts ServiceEndpointsMysqlArgs and ServiceEndpointsMysqlOutput values.
// You can construct a concrete instance of `ServiceEndpointsMysqlInput` via:
//
//	ServiceEndpointsMysqlArgs{...}
type ServiceEndpointsMysqlInput interface {
	pulumi.Input

	ToServiceEndpointsMysqlOutput() ServiceEndpointsMysqlOutput
	ToServiceEndpointsMysqlOutputWithContext(context.Context) ServiceEndpointsMysqlOutput
}

type ServiceEndpointsMysqlArgs struct {
	// Wether to enable the mysql endpoint or not.
	Enabled pulumi.BoolInput `pulumi:"enabled"`
	// Endpoint host.
	Host pulumi.StringPtrInput `pulumi:"host"`
	// Endpoint port.
	Port pulumi.IntPtrInput `pulumi:"port"`
}

func (ServiceEndpointsMysqlArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceEndpointsMysql)(nil)).Elem()
}

func (i ServiceEndpointsMysqlArgs) ToServiceEndpointsMysqlOutput() ServiceEndpointsMysqlOutput {
	return i.ToServiceEndpointsMysqlOutputWithContext(context.Background())
}

func (i ServiceEndpointsMysqlArgs) ToServiceEndpointsMysqlOutputWithContext(ctx context.Context) ServiceEndpointsMysqlOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceEndpointsMysqlOutput)
}

func (i ServiceEndpointsMysqlArgs) ToServiceEndpointsMysqlPtrOutput() ServiceEndpointsMysqlPtrOutput {
	return i.ToServiceEndpointsMysqlPtrOutputWithContext(context.Background())
}

func (i ServiceEndpointsMysqlArgs) ToServiceEndpointsMysqlPtrOutputWithContext(ctx context.Context) ServiceEndpointsMysqlPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceEndpointsMysqlOutput).ToServiceEndpointsMysqlPtrOutputWithContext(ctx)
}

// ServiceEndpointsMysqlPtrInput is an input type that accepts ServiceEndpointsMysqlArgs, ServiceEndpointsMysqlPtr and ServiceEndpointsMysqlPtrOutput values.
// You can construct a concrete instance of `ServiceEndpointsMysqlPtrInput` via:
//
//	        ServiceEndpointsMysqlArgs{...}
//
//	or:
//
//	        nil
type ServiceEndpointsMysqlPtrInput interface {
	pulumi.Input

	ToServiceEndpointsMysqlPtrOutput() ServiceEndpointsMysqlPtrOutput
	ToServiceEndpointsMysqlPtrOutputWithContext(context.Context) ServiceEndpointsMysqlPtrOutput
}

type serviceEndpointsMysqlPtrType ServiceEndpointsMysqlArgs

func ServiceEndpointsMysqlPtr(v *ServiceEndpointsMysqlArgs) ServiceEndpointsMysqlPtrInput {
	return (*serviceEndpointsMysqlPtrType)(v)
}

func (*serviceEndpointsMysqlPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceEndpointsMysql)(nil)).Elem()
}

func (i *serviceEndpointsMysqlPtrType) ToServiceEndpointsMysqlPtrOutput() ServiceEndpointsMysqlPtrOutput {
	return i.ToServiceEndpointsMysqlPtrOutputWithContext(context.Background())
}

func (i *serviceEndpointsMysqlPtrType) ToServiceEndpointsMysqlPtrOutputWithContext(ctx context.Context) ServiceEndpointsMysqlPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceEndpointsMysqlPtrOutput)
}

type ServiceEndpointsMysqlOutput struct{ *pulumi.OutputState }

func (ServiceEndpointsMysqlOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceEndpointsMysql)(nil)).Elem()
}

func (o ServiceEndpointsMysqlOutput) ToServiceEndpointsMysqlOutput() ServiceEndpointsMysqlOutput {
	return o
}

func (o ServiceEndpointsMysqlOutput) ToServiceEndpointsMysqlOutputWithContext(ctx context.Context) ServiceEndpointsMysqlOutput {
	return o
}

func (o ServiceEndpointsMysqlOutput) ToServiceEndpointsMysqlPtrOutput() ServiceEndpointsMysqlPtrOutput {
	return o.ToServiceEndpointsMysqlPtrOutputWithContext(context.Background())
}

func (o ServiceEndpointsMysqlOutput) ToServiceEndpointsMysqlPtrOutputWithContext(ctx context.Context) ServiceEndpointsMysqlPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ServiceEndpointsMysql) *ServiceEndpointsMysql {
		return &v
	}).(ServiceEndpointsMysqlPtrOutput)
}

// Wether to enable the mysql endpoint or not.
func (o ServiceEndpointsMysqlOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v ServiceEndpointsMysql) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// Endpoint host.
func (o ServiceEndpointsMysqlOutput) Host() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ServiceEndpointsMysql) *string { return v.Host }).(pulumi.StringPtrOutput)
}

// Endpoint port.
func (o ServiceEndpointsMysqlOutput) Port() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ServiceEndpointsMysql) *int { return v.Port }).(pulumi.IntPtrOutput)
}

type ServiceEndpointsMysqlPtrOutput struct{ *pulumi.OutputState }

func (ServiceEndpointsMysqlPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceEndpointsMysql)(nil)).Elem()
}

func (o ServiceEndpointsMysqlPtrOutput) ToServiceEndpointsMysqlPtrOutput() ServiceEndpointsMysqlPtrOutput {
	return o
}

func (o ServiceEndpointsMysqlPtrOutput) ToServiceEndpointsMysqlPtrOutputWithContext(ctx context.Context) ServiceEndpointsMysqlPtrOutput {
	return o
}

func (o ServiceEndpointsMysqlPtrOutput) Elem() ServiceEndpointsMysqlOutput {
	return o.ApplyT(func(v *ServiceEndpointsMysql) ServiceEndpointsMysql {
		if v != nil {
			return *v
		}
		var ret ServiceEndpointsMysql
		return ret
	}).(ServiceEndpointsMysqlOutput)
}

// Wether to enable the mysql endpoint or not.
func (o ServiceEndpointsMysqlPtrOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ServiceEndpointsMysql) *bool {
		if v == nil {
			return nil
		}
		return &v.Enabled
	}).(pulumi.BoolPtrOutput)
}

// Endpoint host.
func (o ServiceEndpointsMysqlPtrOutput) Host() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServiceEndpointsMysql) *string {
		if v == nil {
			return nil
		}
		return v.Host
	}).(pulumi.StringPtrOutput)
}

// Endpoint port.
func (o ServiceEndpointsMysqlPtrOutput) Port() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ServiceEndpointsMysql) *int {
		if v == nil {
			return nil
		}
		return v.Port
	}).(pulumi.IntPtrOutput)
}

type ServiceEndpointsNativesecure struct {
	// Endpoint host.
	Host *string `pulumi:"host"`
	// Endpoint port.
	Port *int `pulumi:"port"`
}

// ServiceEndpointsNativesecureInput is an input type that accepts ServiceEndpointsNativesecureArgs and ServiceEndpointsNativesecureOutput values.
// You can construct a concrete instance of `ServiceEndpointsNativesecureInput` via:
//
//	ServiceEndpointsNativesecureArgs{...}
type ServiceEndpointsNativesecureInput interface {
	pulumi.Input

	ToServiceEndpointsNativesecureOutput() ServiceEndpointsNativesecureOutput
	ToServiceEndpointsNativesecureOutputWithContext(context.Context) ServiceEndpointsNativesecureOutput
}

type ServiceEndpointsNativesecureArgs struct {
	// Endpoint host.
	Host pulumi.StringPtrInput `pulumi:"host"`
	// Endpoint port.
	Port pulumi.IntPtrInput `pulumi:"port"`
}

func (ServiceEndpointsNativesecureArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceEndpointsNativesecure)(nil)).Elem()
}

func (i ServiceEndpointsNativesecureArgs) ToServiceEndpointsNativesecureOutput() ServiceEndpointsNativesecureOutput {
	return i.ToServiceEndpointsNativesecureOutputWithContext(context.Background())
}

func (i ServiceEndpointsNativesecureArgs) ToServiceEndpointsNativesecureOutputWithContext(ctx context.Context) ServiceEndpointsNativesecureOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceEndpointsNativesecureOutput)
}

func (i ServiceEndpointsNativesecureArgs) ToServiceEndpointsNativesecurePtrOutput() ServiceEndpointsNativesecurePtrOutput {
	return i.ToServiceEndpointsNativesecurePtrOutputWithContext(context.Background())
}

func (i ServiceEndpointsNativesecureArgs) ToServiceEndpointsNativesecurePtrOutputWithContext(ctx context.Context) ServiceEndpointsNativesecurePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceEndpointsNativesecureOutput).ToServiceEndpointsNativesecurePtrOutputWithContext(ctx)
}

// ServiceEndpointsNativesecurePtrInput is an input type that accepts ServiceEndpointsNativesecureArgs, ServiceEndpointsNativesecurePtr and ServiceEndpointsNativesecurePtrOutput values.
// You can construct a concrete instance of `ServiceEndpointsNativesecurePtrInput` via:
//
//	        ServiceEndpointsNativesecureArgs{...}
//
//	or:
//
//	        nil
type ServiceEndpointsNativesecurePtrInput interface {
	pulumi.Input

	ToServiceEndpointsNativesecurePtrOutput() ServiceEndpointsNativesecurePtrOutput
	ToServiceEndpointsNativesecurePtrOutputWithContext(context.Context) ServiceEndpointsNativesecurePtrOutput
}

type serviceEndpointsNativesecurePtrType ServiceEndpointsNativesecureArgs

func ServiceEndpointsNativesecurePtr(v *ServiceEndpointsNativesecureArgs) ServiceEndpointsNativesecurePtrInput {
	return (*serviceEndpointsNativesecurePtrType)(v)
}

func (*serviceEndpointsNativesecurePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceEndpointsNativesecure)(nil)).Elem()
}

func (i *serviceEndpointsNativesecurePtrType) ToServiceEndpointsNativesecurePtrOutput() ServiceEndpointsNativesecurePtrOutput {
	return i.ToServiceEndpointsNativesecurePtrOutputWithContext(context.Background())
}

func (i *serviceEndpointsNativesecurePtrType) ToServiceEndpointsNativesecurePtrOutputWithContext(ctx context.Context) ServiceEndpointsNativesecurePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceEndpointsNativesecurePtrOutput)
}

type ServiceEndpointsNativesecureOutput struct{ *pulumi.OutputState }

func (ServiceEndpointsNativesecureOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceEndpointsNativesecure)(nil)).Elem()
}

func (o ServiceEndpointsNativesecureOutput) ToServiceEndpointsNativesecureOutput() ServiceEndpointsNativesecureOutput {
	return o
}

func (o ServiceEndpointsNativesecureOutput) ToServiceEndpointsNativesecureOutputWithContext(ctx context.Context) ServiceEndpointsNativesecureOutput {
	return o
}

func (o ServiceEndpointsNativesecureOutput) ToServiceEndpointsNativesecurePtrOutput() ServiceEndpointsNativesecurePtrOutput {
	return o.ToServiceEndpointsNativesecurePtrOutputWithContext(context.Background())
}

func (o ServiceEndpointsNativesecureOutput) ToServiceEndpointsNativesecurePtrOutputWithContext(ctx context.Context) ServiceEndpointsNativesecurePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ServiceEndpointsNativesecure) *ServiceEndpointsNativesecure {
		return &v
	}).(ServiceEndpointsNativesecurePtrOutput)
}

// Endpoint host.
func (o ServiceEndpointsNativesecureOutput) Host() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ServiceEndpointsNativesecure) *string { return v.Host }).(pulumi.StringPtrOutput)
}

// Endpoint port.
func (o ServiceEndpointsNativesecureOutput) Port() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ServiceEndpointsNativesecure) *int { return v.Port }).(pulumi.IntPtrOutput)
}

type ServiceEndpointsNativesecurePtrOutput struct{ *pulumi.OutputState }

func (ServiceEndpointsNativesecurePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceEndpointsNativesecure)(nil)).Elem()
}

func (o ServiceEndpointsNativesecurePtrOutput) ToServiceEndpointsNativesecurePtrOutput() ServiceEndpointsNativesecurePtrOutput {
	return o
}

func (o ServiceEndpointsNativesecurePtrOutput) ToServiceEndpointsNativesecurePtrOutputWithContext(ctx context.Context) ServiceEndpointsNativesecurePtrOutput {
	return o
}

func (o ServiceEndpointsNativesecurePtrOutput) Elem() ServiceEndpointsNativesecureOutput {
	return o.ApplyT(func(v *ServiceEndpointsNativesecure) ServiceEndpointsNativesecure {
		if v != nil {
			return *v
		}
		var ret ServiceEndpointsNativesecure
		return ret
	}).(ServiceEndpointsNativesecureOutput)
}

// Endpoint host.
func (o ServiceEndpointsNativesecurePtrOutput) Host() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServiceEndpointsNativesecure) *string {
		if v == nil {
			return nil
		}
		return v.Host
	}).(pulumi.StringPtrOutput)
}

// Endpoint port.
func (o ServiceEndpointsNativesecurePtrOutput) Port() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ServiceEndpointsNativesecure) *int {
		if v == nil {
			return nil
		}
		return v.Port
	}).(pulumi.IntPtrOutput)
}

type ServiceIpAccess struct {
	// Description of the IP address.
	Description string `pulumi:"description"`
	// IP address allowed to access the service. In case you want to set the ipAccess to anywhere you should set source to 0.0.0.0/0
	Source string `pulumi:"source"`
}

// ServiceIpAccessInput is an input type that accepts ServiceIpAccessArgs and ServiceIpAccessOutput values.
// You can construct a concrete instance of `ServiceIpAccessInput` via:
//
//	ServiceIpAccessArgs{...}
type ServiceIpAccessInput interface {
	pulumi.Input

	ToServiceIpAccessOutput() ServiceIpAccessOutput
	ToServiceIpAccessOutputWithContext(context.Context) ServiceIpAccessOutput
}

type ServiceIpAccessArgs struct {
	// Description of the IP address.
	Description pulumi.StringInput `pulumi:"description"`
	// IP address allowed to access the service. In case you want to set the ipAccess to anywhere you should set source to 0.0.0.0/0
	Source pulumi.StringInput `pulumi:"source"`
}

func (ServiceIpAccessArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceIpAccess)(nil)).Elem()
}

func (i ServiceIpAccessArgs) ToServiceIpAccessOutput() ServiceIpAccessOutput {
	return i.ToServiceIpAccessOutputWithContext(context.Background())
}

func (i ServiceIpAccessArgs) ToServiceIpAccessOutputWithContext(ctx context.Context) ServiceIpAccessOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceIpAccessOutput)
}

// ServiceIpAccessArrayInput is an input type that accepts ServiceIpAccessArray and ServiceIpAccessArrayOutput values.
// You can construct a concrete instance of `ServiceIpAccessArrayInput` via:
//
//	ServiceIpAccessArray{ ServiceIpAccessArgs{...} }
type ServiceIpAccessArrayInput interface {
	pulumi.Input

	ToServiceIpAccessArrayOutput() ServiceIpAccessArrayOutput
	ToServiceIpAccessArrayOutputWithContext(context.Context) ServiceIpAccessArrayOutput
}

type ServiceIpAccessArray []ServiceIpAccessInput

func (ServiceIpAccessArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ServiceIpAccess)(nil)).Elem()
}

func (i ServiceIpAccessArray) ToServiceIpAccessArrayOutput() ServiceIpAccessArrayOutput {
	return i.ToServiceIpAccessArrayOutputWithContext(context.Background())
}

func (i ServiceIpAccessArray) ToServiceIpAccessArrayOutputWithContext(ctx context.Context) ServiceIpAccessArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceIpAccessArrayOutput)
}

type ServiceIpAccessOutput struct{ *pulumi.OutputState }

func (ServiceIpAccessOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceIpAccess)(nil)).Elem()
}

func (o ServiceIpAccessOutput) ToServiceIpAccessOutput() ServiceIpAccessOutput {
	return o
}

func (o ServiceIpAccessOutput) ToServiceIpAccessOutputWithContext(ctx context.Context) ServiceIpAccessOutput {
	return o
}

// Description of the IP address.
func (o ServiceIpAccessOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v ServiceIpAccess) string { return v.Description }).(pulumi.StringOutput)
}

// IP address allowed to access the service. In case you want to set the ipAccess to anywhere you should set source to 0.0.0.0/0
func (o ServiceIpAccessOutput) Source() pulumi.StringOutput {
	return o.ApplyT(func(v ServiceIpAccess) string { return v.Source }).(pulumi.StringOutput)
}

type ServiceIpAccessArrayOutput struct{ *pulumi.OutputState }

func (ServiceIpAccessArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ServiceIpAccess)(nil)).Elem()
}

func (o ServiceIpAccessArrayOutput) ToServiceIpAccessArrayOutput() ServiceIpAccessArrayOutput {
	return o
}

func (o ServiceIpAccessArrayOutput) ToServiceIpAccessArrayOutputWithContext(ctx context.Context) ServiceIpAccessArrayOutput {
	return o
}

func (o ServiceIpAccessArrayOutput) Index(i pulumi.IntInput) ServiceIpAccessOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) ServiceIpAccess {
		return vs[0].([]ServiceIpAccess)[vs[1].(int)]
	}).(ServiceIpAccessOutput)
}

type ServicePrivateEndpointConfig struct {
	// Unique identifier of the interface endpoint you created in your VPC with the AWS(Service Name) or GCP(Target Service) resource.
	EndpointServiceId *string `pulumi:"endpointServiceId"`
	// Private DNS Hostname of the VPC you created.
	PrivateDnsHostname *string `pulumi:"privateDnsHostname"`
}

// ServicePrivateEndpointConfigInput is an input type that accepts ServicePrivateEndpointConfigArgs and ServicePrivateEndpointConfigOutput values.
// You can construct a concrete instance of `ServicePrivateEndpointConfigInput` via:
//
//	ServicePrivateEndpointConfigArgs{...}
type ServicePrivateEndpointConfigInput interface {
	pulumi.Input

	ToServicePrivateEndpointConfigOutput() ServicePrivateEndpointConfigOutput
	ToServicePrivateEndpointConfigOutputWithContext(context.Context) ServicePrivateEndpointConfigOutput
}

type ServicePrivateEndpointConfigArgs struct {
	// Unique identifier of the interface endpoint you created in your VPC with the AWS(Service Name) or GCP(Target Service) resource.
	EndpointServiceId pulumi.StringPtrInput `pulumi:"endpointServiceId"`
	// Private DNS Hostname of the VPC you created.
	PrivateDnsHostname pulumi.StringPtrInput `pulumi:"privateDnsHostname"`
}

func (ServicePrivateEndpointConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ServicePrivateEndpointConfig)(nil)).Elem()
}

func (i ServicePrivateEndpointConfigArgs) ToServicePrivateEndpointConfigOutput() ServicePrivateEndpointConfigOutput {
	return i.ToServicePrivateEndpointConfigOutputWithContext(context.Background())
}

func (i ServicePrivateEndpointConfigArgs) ToServicePrivateEndpointConfigOutputWithContext(ctx context.Context) ServicePrivateEndpointConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServicePrivateEndpointConfigOutput)
}

func (i ServicePrivateEndpointConfigArgs) ToServicePrivateEndpointConfigPtrOutput() ServicePrivateEndpointConfigPtrOutput {
	return i.ToServicePrivateEndpointConfigPtrOutputWithContext(context.Background())
}

func (i ServicePrivateEndpointConfigArgs) ToServicePrivateEndpointConfigPtrOutputWithContext(ctx context.Context) ServicePrivateEndpointConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServicePrivateEndpointConfigOutput).ToServicePrivateEndpointConfigPtrOutputWithContext(ctx)
}

// ServicePrivateEndpointConfigPtrInput is an input type that accepts ServicePrivateEndpointConfigArgs, ServicePrivateEndpointConfigPtr and ServicePrivateEndpointConfigPtrOutput values.
// You can construct a concrete instance of `ServicePrivateEndpointConfigPtrInput` via:
//
//	        ServicePrivateEndpointConfigArgs{...}
//
//	or:
//
//	        nil
type ServicePrivateEndpointConfigPtrInput interface {
	pulumi.Input

	ToServicePrivateEndpointConfigPtrOutput() ServicePrivateEndpointConfigPtrOutput
	ToServicePrivateEndpointConfigPtrOutputWithContext(context.Context) ServicePrivateEndpointConfigPtrOutput
}

type servicePrivateEndpointConfigPtrType ServicePrivateEndpointConfigArgs

func ServicePrivateEndpointConfigPtr(v *ServicePrivateEndpointConfigArgs) ServicePrivateEndpointConfigPtrInput {
	return (*servicePrivateEndpointConfigPtrType)(v)
}

func (*servicePrivateEndpointConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ServicePrivateEndpointConfig)(nil)).Elem()
}

func (i *servicePrivateEndpointConfigPtrType) ToServicePrivateEndpointConfigPtrOutput() ServicePrivateEndpointConfigPtrOutput {
	return i.ToServicePrivateEndpointConfigPtrOutputWithContext(context.Background())
}

func (i *servicePrivateEndpointConfigPtrType) ToServicePrivateEndpointConfigPtrOutputWithContext(ctx context.Context) ServicePrivateEndpointConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServicePrivateEndpointConfigPtrOutput)
}

type ServicePrivateEndpointConfigOutput struct{ *pulumi.OutputState }

func (ServicePrivateEndpointConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ServicePrivateEndpointConfig)(nil)).Elem()
}

func (o ServicePrivateEndpointConfigOutput) ToServicePrivateEndpointConfigOutput() ServicePrivateEndpointConfigOutput {
	return o
}

func (o ServicePrivateEndpointConfigOutput) ToServicePrivateEndpointConfigOutputWithContext(ctx context.Context) ServicePrivateEndpointConfigOutput {
	return o
}

func (o ServicePrivateEndpointConfigOutput) ToServicePrivateEndpointConfigPtrOutput() ServicePrivateEndpointConfigPtrOutput {
	return o.ToServicePrivateEndpointConfigPtrOutputWithContext(context.Background())
}

func (o ServicePrivateEndpointConfigOutput) ToServicePrivateEndpointConfigPtrOutputWithContext(ctx context.Context) ServicePrivateEndpointConfigPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ServicePrivateEndpointConfig) *ServicePrivateEndpointConfig {
		return &v
	}).(ServicePrivateEndpointConfigPtrOutput)
}

// Unique identifier of the interface endpoint you created in your VPC with the AWS(Service Name) or GCP(Target Service) resource.
func (o ServicePrivateEndpointConfigOutput) EndpointServiceId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ServicePrivateEndpointConfig) *string { return v.EndpointServiceId }).(pulumi.StringPtrOutput)
}

// Private DNS Hostname of the VPC you created.
func (o ServicePrivateEndpointConfigOutput) PrivateDnsHostname() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ServicePrivateEndpointConfig) *string { return v.PrivateDnsHostname }).(pulumi.StringPtrOutput)
}

type ServicePrivateEndpointConfigPtrOutput struct{ *pulumi.OutputState }

func (ServicePrivateEndpointConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServicePrivateEndpointConfig)(nil)).Elem()
}

func (o ServicePrivateEndpointConfigPtrOutput) ToServicePrivateEndpointConfigPtrOutput() ServicePrivateEndpointConfigPtrOutput {
	return o
}

func (o ServicePrivateEndpointConfigPtrOutput) ToServicePrivateEndpointConfigPtrOutputWithContext(ctx context.Context) ServicePrivateEndpointConfigPtrOutput {
	return o
}

func (o ServicePrivateEndpointConfigPtrOutput) Elem() ServicePrivateEndpointConfigOutput {
	return o.ApplyT(func(v *ServicePrivateEndpointConfig) ServicePrivateEndpointConfig {
		if v != nil {
			return *v
		}
		var ret ServicePrivateEndpointConfig
		return ret
	}).(ServicePrivateEndpointConfigOutput)
}

// Unique identifier of the interface endpoint you created in your VPC with the AWS(Service Name) or GCP(Target Service) resource.
func (o ServicePrivateEndpointConfigPtrOutput) EndpointServiceId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServicePrivateEndpointConfig) *string {
		if v == nil {
			return nil
		}
		return v.EndpointServiceId
	}).(pulumi.StringPtrOutput)
}

// Private DNS Hostname of the VPC you created.
func (o ServicePrivateEndpointConfigPtrOutput) PrivateDnsHostname() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServicePrivateEndpointConfig) *string {
		if v == nil {
			return nil
		}
		return v.PrivateDnsHostname
	}).(pulumi.StringPtrOutput)
}

type ServiceQueryApiEndpoints struct {
	// Comma separated list of domain names to be allowed cross-origin resource sharing (CORS) access to the query API. Leave this field empty to restrict access to backend servers only
	AllowedOrigins *string `pulumi:"allowedOrigins"`
	// The UUIDs of the API Keys to grant access to the query API.
	ApiKeyIds []string `pulumi:"apiKeyIds"`
	// The Database role that will be used to run the query.
	Roles []string `pulumi:"roles"`
}

// ServiceQueryApiEndpointsInput is an input type that accepts ServiceQueryApiEndpointsArgs and ServiceQueryApiEndpointsOutput values.
// You can construct a concrete instance of `ServiceQueryApiEndpointsInput` via:
//
//	ServiceQueryApiEndpointsArgs{...}
type ServiceQueryApiEndpointsInput interface {
	pulumi.Input

	ToServiceQueryApiEndpointsOutput() ServiceQueryApiEndpointsOutput
	ToServiceQueryApiEndpointsOutputWithContext(context.Context) ServiceQueryApiEndpointsOutput
}

type ServiceQueryApiEndpointsArgs struct {
	// Comma separated list of domain names to be allowed cross-origin resource sharing (CORS) access to the query API. Leave this field empty to restrict access to backend servers only
	AllowedOrigins pulumi.StringPtrInput `pulumi:"allowedOrigins"`
	// The UUIDs of the API Keys to grant access to the query API.
	ApiKeyIds pulumi.StringArrayInput `pulumi:"apiKeyIds"`
	// The Database role that will be used to run the query.
	Roles pulumi.StringArrayInput `pulumi:"roles"`
}

func (ServiceQueryApiEndpointsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceQueryApiEndpoints)(nil)).Elem()
}

func (i ServiceQueryApiEndpointsArgs) ToServiceQueryApiEndpointsOutput() ServiceQueryApiEndpointsOutput {
	return i.ToServiceQueryApiEndpointsOutputWithContext(context.Background())
}

func (i ServiceQueryApiEndpointsArgs) ToServiceQueryApiEndpointsOutputWithContext(ctx context.Context) ServiceQueryApiEndpointsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceQueryApiEndpointsOutput)
}

func (i ServiceQueryApiEndpointsArgs) ToServiceQueryApiEndpointsPtrOutput() ServiceQueryApiEndpointsPtrOutput {
	return i.ToServiceQueryApiEndpointsPtrOutputWithContext(context.Background())
}

func (i ServiceQueryApiEndpointsArgs) ToServiceQueryApiEndpointsPtrOutputWithContext(ctx context.Context) ServiceQueryApiEndpointsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceQueryApiEndpointsOutput).ToServiceQueryApiEndpointsPtrOutputWithContext(ctx)
}

// ServiceQueryApiEndpointsPtrInput is an input type that accepts ServiceQueryApiEndpointsArgs, ServiceQueryApiEndpointsPtr and ServiceQueryApiEndpointsPtrOutput values.
// You can construct a concrete instance of `ServiceQueryApiEndpointsPtrInput` via:
//
//	        ServiceQueryApiEndpointsArgs{...}
//
//	or:
//
//	        nil
type ServiceQueryApiEndpointsPtrInput interface {
	pulumi.Input

	ToServiceQueryApiEndpointsPtrOutput() ServiceQueryApiEndpointsPtrOutput
	ToServiceQueryApiEndpointsPtrOutputWithContext(context.Context) ServiceQueryApiEndpointsPtrOutput
}

type serviceQueryApiEndpointsPtrType ServiceQueryApiEndpointsArgs

func ServiceQueryApiEndpointsPtr(v *ServiceQueryApiEndpointsArgs) ServiceQueryApiEndpointsPtrInput {
	return (*serviceQueryApiEndpointsPtrType)(v)
}

func (*serviceQueryApiEndpointsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceQueryApiEndpoints)(nil)).Elem()
}

func (i *serviceQueryApiEndpointsPtrType) ToServiceQueryApiEndpointsPtrOutput() ServiceQueryApiEndpointsPtrOutput {
	return i.ToServiceQueryApiEndpointsPtrOutputWithContext(context.Background())
}

func (i *serviceQueryApiEndpointsPtrType) ToServiceQueryApiEndpointsPtrOutputWithContext(ctx context.Context) ServiceQueryApiEndpointsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceQueryApiEndpointsPtrOutput)
}

type ServiceQueryApiEndpointsOutput struct{ *pulumi.OutputState }

func (ServiceQueryApiEndpointsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceQueryApiEndpoints)(nil)).Elem()
}

func (o ServiceQueryApiEndpointsOutput) ToServiceQueryApiEndpointsOutput() ServiceQueryApiEndpointsOutput {
	return o
}

func (o ServiceQueryApiEndpointsOutput) ToServiceQueryApiEndpointsOutputWithContext(ctx context.Context) ServiceQueryApiEndpointsOutput {
	return o
}

func (o ServiceQueryApiEndpointsOutput) ToServiceQueryApiEndpointsPtrOutput() ServiceQueryApiEndpointsPtrOutput {
	return o.ToServiceQueryApiEndpointsPtrOutputWithContext(context.Background())
}

func (o ServiceQueryApiEndpointsOutput) ToServiceQueryApiEndpointsPtrOutputWithContext(ctx context.Context) ServiceQueryApiEndpointsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ServiceQueryApiEndpoints) *ServiceQueryApiEndpoints {
		return &v
	}).(ServiceQueryApiEndpointsPtrOutput)
}

// Comma separated list of domain names to be allowed cross-origin resource sharing (CORS) access to the query API. Leave this field empty to restrict access to backend servers only
func (o ServiceQueryApiEndpointsOutput) AllowedOrigins() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ServiceQueryApiEndpoints) *string { return v.AllowedOrigins }).(pulumi.StringPtrOutput)
}

// The UUIDs of the API Keys to grant access to the query API.
func (o ServiceQueryApiEndpointsOutput) ApiKeyIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ServiceQueryApiEndpoints) []string { return v.ApiKeyIds }).(pulumi.StringArrayOutput)
}

// The Database role that will be used to run the query.
func (o ServiceQueryApiEndpointsOutput) Roles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ServiceQueryApiEndpoints) []string { return v.Roles }).(pulumi.StringArrayOutput)
}

type ServiceQueryApiEndpointsPtrOutput struct{ *pulumi.OutputState }

func (ServiceQueryApiEndpointsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceQueryApiEndpoints)(nil)).Elem()
}

func (o ServiceQueryApiEndpointsPtrOutput) ToServiceQueryApiEndpointsPtrOutput() ServiceQueryApiEndpointsPtrOutput {
	return o
}

func (o ServiceQueryApiEndpointsPtrOutput) ToServiceQueryApiEndpointsPtrOutputWithContext(ctx context.Context) ServiceQueryApiEndpointsPtrOutput {
	return o
}

func (o ServiceQueryApiEndpointsPtrOutput) Elem() ServiceQueryApiEndpointsOutput {
	return o.ApplyT(func(v *ServiceQueryApiEndpoints) ServiceQueryApiEndpoints {
		if v != nil {
			return *v
		}
		var ret ServiceQueryApiEndpoints
		return ret
	}).(ServiceQueryApiEndpointsOutput)
}

// Comma separated list of domain names to be allowed cross-origin resource sharing (CORS) access to the query API. Leave this field empty to restrict access to backend servers only
func (o ServiceQueryApiEndpointsPtrOutput) AllowedOrigins() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServiceQueryApiEndpoints) *string {
		if v == nil {
			return nil
		}
		return v.AllowedOrigins
	}).(pulumi.StringPtrOutput)
}

// The UUIDs of the API Keys to grant access to the query API.
func (o ServiceQueryApiEndpointsPtrOutput) ApiKeyIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ServiceQueryApiEndpoints) []string {
		if v == nil {
			return nil
		}
		return v.ApiKeyIds
	}).(pulumi.StringArrayOutput)
}

// The Database role that will be used to run the query.
func (o ServiceQueryApiEndpointsPtrOutput) Roles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ServiceQueryApiEndpoints) []string {
		if v == nil {
			return nil
		}
		return v.Roles
	}).(pulumi.StringArrayOutput)
}

type ServiceTransparentDataEncryption struct {
	// If true, TDE is enabled for the service.
	Enabled *bool `pulumi:"enabled"`
	// ID of Role to be used for granting access to the Encryption Key. This is an ARN for AWS services and a Service Account Identifier for GCP.
	RoleId *string `pulumi:"roleId"`
}

// ServiceTransparentDataEncryptionInput is an input type that accepts ServiceTransparentDataEncryptionArgs and ServiceTransparentDataEncryptionOutput values.
// You can construct a concrete instance of `ServiceTransparentDataEncryptionInput` via:
//
//	ServiceTransparentDataEncryptionArgs{...}
type ServiceTransparentDataEncryptionInput interface {
	pulumi.Input

	ToServiceTransparentDataEncryptionOutput() ServiceTransparentDataEncryptionOutput
	ToServiceTransparentDataEncryptionOutputWithContext(context.Context) ServiceTransparentDataEncryptionOutput
}

type ServiceTransparentDataEncryptionArgs struct {
	// If true, TDE is enabled for the service.
	Enabled pulumi.BoolPtrInput `pulumi:"enabled"`
	// ID of Role to be used for granting access to the Encryption Key. This is an ARN for AWS services and a Service Account Identifier for GCP.
	RoleId pulumi.StringPtrInput `pulumi:"roleId"`
}

func (ServiceTransparentDataEncryptionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceTransparentDataEncryption)(nil)).Elem()
}

func (i ServiceTransparentDataEncryptionArgs) ToServiceTransparentDataEncryptionOutput() ServiceTransparentDataEncryptionOutput {
	return i.ToServiceTransparentDataEncryptionOutputWithContext(context.Background())
}

func (i ServiceTransparentDataEncryptionArgs) ToServiceTransparentDataEncryptionOutputWithContext(ctx context.Context) ServiceTransparentDataEncryptionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceTransparentDataEncryptionOutput)
}

func (i ServiceTransparentDataEncryptionArgs) ToServiceTransparentDataEncryptionPtrOutput() ServiceTransparentDataEncryptionPtrOutput {
	return i.ToServiceTransparentDataEncryptionPtrOutputWithContext(context.Background())
}

func (i ServiceTransparentDataEncryptionArgs) ToServiceTransparentDataEncryptionPtrOutputWithContext(ctx context.Context) ServiceTransparentDataEncryptionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceTransparentDataEncryptionOutput).ToServiceTransparentDataEncryptionPtrOutputWithContext(ctx)
}

// ServiceTransparentDataEncryptionPtrInput is an input type that accepts ServiceTransparentDataEncryptionArgs, ServiceTransparentDataEncryptionPtr and ServiceTransparentDataEncryptionPtrOutput values.
// You can construct a concrete instance of `ServiceTransparentDataEncryptionPtrInput` via:
//
//	        ServiceTransparentDataEncryptionArgs{...}
//
//	or:
//
//	        nil
type ServiceTransparentDataEncryptionPtrInput interface {
	pulumi.Input

	ToServiceTransparentDataEncryptionPtrOutput() ServiceTransparentDataEncryptionPtrOutput
	ToServiceTransparentDataEncryptionPtrOutputWithContext(context.Context) ServiceTransparentDataEncryptionPtrOutput
}

type serviceTransparentDataEncryptionPtrType ServiceTransparentDataEncryptionArgs

func ServiceTransparentDataEncryptionPtr(v *ServiceTransparentDataEncryptionArgs) ServiceTransparentDataEncryptionPtrInput {
	return (*serviceTransparentDataEncryptionPtrType)(v)
}

func (*serviceTransparentDataEncryptionPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceTransparentDataEncryption)(nil)).Elem()
}

func (i *serviceTransparentDataEncryptionPtrType) ToServiceTransparentDataEncryptionPtrOutput() ServiceTransparentDataEncryptionPtrOutput {
	return i.ToServiceTransparentDataEncryptionPtrOutputWithContext(context.Background())
}

func (i *serviceTransparentDataEncryptionPtrType) ToServiceTransparentDataEncryptionPtrOutputWithContext(ctx context.Context) ServiceTransparentDataEncryptionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceTransparentDataEncryptionPtrOutput)
}

type ServiceTransparentDataEncryptionOutput struct{ *pulumi.OutputState }

func (ServiceTransparentDataEncryptionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ServiceTransparentDataEncryption)(nil)).Elem()
}

func (o ServiceTransparentDataEncryptionOutput) ToServiceTransparentDataEncryptionOutput() ServiceTransparentDataEncryptionOutput {
	return o
}

func (o ServiceTransparentDataEncryptionOutput) ToServiceTransparentDataEncryptionOutputWithContext(ctx context.Context) ServiceTransparentDataEncryptionOutput {
	return o
}

func (o ServiceTransparentDataEncryptionOutput) ToServiceTransparentDataEncryptionPtrOutput() ServiceTransparentDataEncryptionPtrOutput {
	return o.ToServiceTransparentDataEncryptionPtrOutputWithContext(context.Background())
}

func (o ServiceTransparentDataEncryptionOutput) ToServiceTransparentDataEncryptionPtrOutputWithContext(ctx context.Context) ServiceTransparentDataEncryptionPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ServiceTransparentDataEncryption) *ServiceTransparentDataEncryption {
		return &v
	}).(ServiceTransparentDataEncryptionPtrOutput)
}

// If true, TDE is enabled for the service.
func (o ServiceTransparentDataEncryptionOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ServiceTransparentDataEncryption) *bool { return v.Enabled }).(pulumi.BoolPtrOutput)
}

// ID of Role to be used for granting access to the Encryption Key. This is an ARN for AWS services and a Service Account Identifier for GCP.
func (o ServiceTransparentDataEncryptionOutput) RoleId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ServiceTransparentDataEncryption) *string { return v.RoleId }).(pulumi.StringPtrOutput)
}

type ServiceTransparentDataEncryptionPtrOutput struct{ *pulumi.OutputState }

func (ServiceTransparentDataEncryptionPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceTransparentDataEncryption)(nil)).Elem()
}

func (o ServiceTransparentDataEncryptionPtrOutput) ToServiceTransparentDataEncryptionPtrOutput() ServiceTransparentDataEncryptionPtrOutput {
	return o
}

func (o ServiceTransparentDataEncryptionPtrOutput) ToServiceTransparentDataEncryptionPtrOutputWithContext(ctx context.Context) ServiceTransparentDataEncryptionPtrOutput {
	return o
}

func (o ServiceTransparentDataEncryptionPtrOutput) Elem() ServiceTransparentDataEncryptionOutput {
	return o.ApplyT(func(v *ServiceTransparentDataEncryption) ServiceTransparentDataEncryption {
		if v != nil {
			return *v
		}
		var ret ServiceTransparentDataEncryption
		return ret
	}).(ServiceTransparentDataEncryptionOutput)
}

// If true, TDE is enabled for the service.
func (o ServiceTransparentDataEncryptionPtrOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ServiceTransparentDataEncryption) *bool {
		if v == nil {
			return nil
		}
		return v.Enabled
	}).(pulumi.BoolPtrOutput)
}

// ID of Role to be used for granting access to the Encryption Key. This is an ARN for AWS services and a Service Account Identifier for GCP.
func (o ServiceTransparentDataEncryptionPtrOutput) RoleId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServiceTransparentDataEncryption) *string {
		if v == nil {
			return nil
		}
		return v.RoleId
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceBackupConfigurationInput)(nil)).Elem(), ServiceBackupConfigurationArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceBackupConfigurationPtrInput)(nil)).Elem(), ServiceBackupConfigurationArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceEndpointsInput)(nil)).Elem(), ServiceEndpointsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceEndpointsPtrInput)(nil)).Elem(), ServiceEndpointsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceEndpointsHttpsInput)(nil)).Elem(), ServiceEndpointsHttpsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceEndpointsHttpsPtrInput)(nil)).Elem(), ServiceEndpointsHttpsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceEndpointsMysqlInput)(nil)).Elem(), ServiceEndpointsMysqlArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceEndpointsMysqlPtrInput)(nil)).Elem(), ServiceEndpointsMysqlArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceEndpointsNativesecureInput)(nil)).Elem(), ServiceEndpointsNativesecureArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceEndpointsNativesecurePtrInput)(nil)).Elem(), ServiceEndpointsNativesecureArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceIpAccessInput)(nil)).Elem(), ServiceIpAccessArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceIpAccessArrayInput)(nil)).Elem(), ServiceIpAccessArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServicePrivateEndpointConfigInput)(nil)).Elem(), ServicePrivateEndpointConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServicePrivateEndpointConfigPtrInput)(nil)).Elem(), ServicePrivateEndpointConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceQueryApiEndpointsInput)(nil)).Elem(), ServiceQueryApiEndpointsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceQueryApiEndpointsPtrInput)(nil)).Elem(), ServiceQueryApiEndpointsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceTransparentDataEncryptionInput)(nil)).Elem(), ServiceTransparentDataEncryptionArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceTransparentDataEncryptionPtrInput)(nil)).Elem(), ServiceTransparentDataEncryptionArgs{})
	pulumi.RegisterOutputType(ServiceBackupConfigurationOutput{})
	pulumi.RegisterOutputType(ServiceBackupConfigurationPtrOutput{})
	pulumi.RegisterOutputType(ServiceEndpointsOutput{})
	pulumi.RegisterOutputType(ServiceEndpointsPtrOutput{})
	pulumi.RegisterOutputType(ServiceEndpointsHttpsOutput{})
	pulumi.RegisterOutputType(ServiceEndpointsHttpsPtrOutput{})
	pulumi.RegisterOutputType(ServiceEndpointsMysqlOutput{})
	pulumi.RegisterOutputType(ServiceEndpointsMysqlPtrOutput{})
	pulumi.RegisterOutputType(ServiceEndpointsNativesecureOutput{})
	pulumi.RegisterOutputType(ServiceEndpointsNativesecurePtrOutput{})
	pulumi.RegisterOutputType(ServiceIpAccessOutput{})
	pulumi.RegisterOutputType(ServiceIpAccessArrayOutput{})
	pulumi.RegisterOutputType(ServicePrivateEndpointConfigOutput{})
	pulumi.RegisterOutputType(ServicePrivateEndpointConfigPtrOutput{})
	pulumi.RegisterOutputType(ServiceQueryApiEndpointsOutput{})
	pulumi.RegisterOutputType(ServiceQueryApiEndpointsPtrOutput{})
	pulumi.RegisterOutputType(ServiceTransparentDataEncryptionOutput{})
	pulumi.RegisterOutputType(ServiceTransparentDataEncryptionPtrOutput{})
}
