// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Inputs
{

    public sealed class ClickpipeSourceObjectStorageGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Access key
        /// </summary>
        [Input("accessKey")]
        public Input<Inputs.ClickpipeSourceObjectStorageAccessKeyGetArgs>? AccessKey { get; set; }

        /// <summary>
        /// CONNECTION*STRING is for Azure Blob Storage. IAM*ROLE and IAM*USER are for AWS S3. IAM*USER and SERVICE_ACCOUNT are for GCS. If not provided, no authentication is used
        /// </summary>
        [Input("authentication")]
        public Input<string>? Authentication { get; set; }

        /// <summary>
        /// Container name for Azure Blob Storage. Required when type is azureblobstorage. Example: `Mycontainer`
        /// </summary>
        [Input("azureContainerName")]
        public Input<string>? AzureContainerName { get; set; }

        /// <summary>
        /// Compression algorithm used for the files.. (`None`, `Auto`, `Gzip`, `Brotli`, `Br`, `Xz`, `LZMA`, `Zstd`)
        /// </summary>
        [Input("compression")]
        public Input<string>? Compression { get; set; }

        [Input("connectionString")]
        private Input<string>? _connectionString;

        /// <summary>
        /// Connection string for Azure Blob Storage authentication. Required when authentication is CONNECTION_STRING. Example: `DefaultEndpointsProtocol=https;AccountName=myaccount;AccountKey=mykey;EndpointSuffix=core.windows.net`
        /// </summary>
        public Input<string>? ConnectionString
        {
            get => _connectionString;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _connectionString = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The delimiter for the S3 source. Default is `,`.
        /// </summary>
        [Input("delimiter")]
        public Input<string>? Delimiter { get; set; }

        /// <summary>
        /// The format of the S3 objects. (`JSONEachRow`, `CSV`, `CSVWithNames`, `Parquet`, `Avro`)
        /// </summary>
        [Input("format", required: true)]
        public Input<string> Format { get; set; } = null!;

        /// <summary>
        /// The IAM role for the S3 source. Use with `IAM_ROLE` authentication. It can be used with AWS ClickHouse service only. Read more at https://clickhouse.com/docs/en/integrations/clickpipes/object-storage#authentication
        /// </summary>
        [Input("iamRole")]
        public Input<string>? IamRole { get; set; }

        /// <summary>
        /// If set to true, the pipe will continuously read new files from the source. If set to false, the pipe will read the files only once. New files have to be uploaded lexically order.
        /// </summary>
        [Input("isContinuous")]
        public Input<bool>? IsContinuous { get; set; }

        /// <summary>
        /// Path to the file(s) within the Azure container. Used for Azure Blob Storage sources. You can specify multiple files using bash-like wildcards. For more information, see the documentation on using wildcards in path: https://clickhouse.com/docs/en/integrations/clickpipes/object-storage#limitations. Example: `data/logs/*.json`
        /// </summary>
        [Input("path")]
        public Input<string>? Path { get; set; }

        /// <summary>
        /// Queue URL for event-based continuous ingestion. When provided, files are ingested based on event notifications rather than lexicographical order. Only applicable when `IsContinuous` is `True` and authentication is provided. For S3: SQS URL in the format `https://sqs.{region}.amazonaws.com/{account-id}/{queue-name}`. For GCS: Pub/Sub subscription in the format `projects/{project}/subscriptions/{subscription}`.
        /// </summary>
        [Input("queueUrl")]
        public Input<string>? QueueUrl { get; set; }

        [Input("serviceAccountKey")]
        private Input<string>? _serviceAccountKey;

        /// <summary>
        /// Base64-encoded GCP service account JSON key for GCS authentication. Required when authentication is `SERVICE_ACCOUNT`.
        /// </summary>
        public Input<string>? ServiceAccountKey
        {
            get => _serviceAccountKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _serviceAccountKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// If set to true, skips the initial load and only ingests files delivered by queue notifications. Only applicable when `QueueUrl` is provided.
        /// </summary>
        [Input("skipInitialLoad")]
        public Input<bool>? SkipInitialLoad { get; set; }

        /// <summary>
        /// Start continuous ingestion after this object key. Cannot be provided when `SkipInitialLoad` is true.
        /// </summary>
        [Input("startAfter")]
        public Input<string>? StartAfter { get; set; }

        /// <summary>
        /// The type of the S3-compatible source (`S3`, `Gcs`, `Azureblobstorage`). Default is `S3`.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// The URL of the S3/GCS bucket. Required for S3 and GCS types. Not used for Azure Blob Storage (use path and azure*container*name instead). You can specify multiple files using bash-like wildcards. For more information, see the documentation on using wildcards in path: https://clickhouse.com/docs/en/integrations/clickpipes/object-storage#limitations
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public ClickpipeSourceObjectStorageGetArgs()
        {
        }
        public static new ClickpipeSourceObjectStorageGetArgs Empty => new ClickpipeSourceObjectStorageGetArgs();
    }
}
