// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Inputs
{

    public sealed class ClickpipeSourceMongodbArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// PEM encoded CA certificate to validate the MongoDB server certificate.
        /// </summary>
        [Input("caCertificate")]
        public Input<string>? CaCertificate { get; set; }

        [Input("credentials")]
        private Input<Inputs.ClickpipeSourceMongodbCredentialsArgs>? _credentials;

        /// <summary>
        /// The credentials for the MongoDB instance (username and password). Optional if credentials are embedded in the URI.
        /// </summary>
        public Input<Inputs.ClickpipeSourceMongodbCredentialsArgs>? Credentials
        {
            get => _credentials;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _credentials = Output.Tuple<Input<Inputs.ClickpipeSourceMongodbCredentialsArgs>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Disable TLS for the MongoDB connection. Defaults to false (TLS enabled).
        /// </summary>
        [Input("disableTls")]
        public Input<bool>? DisableTls { get; set; }

        /// <summary>
        /// MongoDB read preference for replica set reads. (`Primary`, `primaryPreferred`, `Secondary`, `secondaryPreferred`, `Nearest`)
        /// </summary>
        [Input("readPreference", required: true)]
        public Input<string> ReadPreference { get; set; } = null!;

        /// <summary>
        /// Settings for the MongoDB CDC pipe.
        /// </summary>
        [Input("settings", required: true)]
        public Input<Inputs.ClickpipeSourceMongodbSettingsArgs> Settings { get; set; } = null!;

        [Input("tableMappings", required: true)]
        private InputList<Inputs.ClickpipeSourceMongodbTableMappingArgs>? _tableMappings;

        /// <summary>
        /// Collection mappings from MongoDB source to ClickHouse destination.
        /// </summary>
        public InputList<Inputs.ClickpipeSourceMongodbTableMappingArgs> TableMappings
        {
            get => _tableMappings ?? (_tableMappings = new InputList<Inputs.ClickpipeSourceMongodbTableMappingArgs>());
            set => _tableMappings = value;
        }

        /// <summary>
        /// TLS/SSL host for secure connections.
        /// </summary>
        [Input("tlsHost")]
        public Input<string>? TlsHost { get; set; }

        /// <summary>
        /// MongoDB connection URI. Supports both standard URIs (mongodb://...) and SRV URIs (mongodb+srv://...).
        /// </summary>
        [Input("uri", required: true)]
        public Input<string> Uri { get; set; } = null!;

        public ClickpipeSourceMongodbArgs()
        {
        }
        public static new ClickpipeSourceMongodbArgs Empty => new ClickpipeSourceMongodbArgs();
    }
}
