// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Inputs
{

    public sealed class ClickpipesReversePrivateEndpointCustomPrivateDnsMappingGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Custom private DNS name managed by ClickHouse Cloud.
        /// </summary>
        [Input("privateDnsName", required: true)]
        public Input<string> PrivateDnsName { get; set; } = null!;

        public ClickpipesReversePrivateEndpointCustomPrivateDnsMappingGetArgs()
        {
        }
        public static new ClickpipesReversePrivateEndpointCustomPrivateDnsMappingGetArgs Empty => new ClickpipesReversePrivateEndpointCustomPrivateDnsMappingGetArgs();
    }
}
