// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Inputs
{

    public sealed class ClickpipeSourceKinesisGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The access key for the Kinesis source. Use with `IAM_USER` authentication. Can be rotated in place via an update.
        /// </summary>
        [Input("accessKey")]
        public Input<Inputs.ClickpipeSourceKinesisAccessKeyGetArgs>? AccessKey { get; set; }

        /// <summary>
        /// The authentication method for the Kinesis source. (`IAM_ROLE`, `IAM_USER`).
        /// </summary>
        [Input("authentication", required: true)]
        public Input<string> Authentication { get; set; } = null!;

        /// <summary>
        /// The format of the Kinesis source. (`JSONEachRow`, `Avro`, `AvroConfluent`)
        /// </summary>
        [Input("format", required: true)]
        public Input<string> Format { get; set; } = null!;

        /// <summary>
        /// The IAM role for the Kinesis source. Use with `IAM_ROLE` authentication. It can be used with AWS ClickHouse service only. Read more at https://clickhouse.com/docs/en/integrations/clickpipes/kinesis.
        /// </summary>
        [Input("iamRole")]
        public Input<string>? IamRole { get; set; }

        /// <summary>
        /// The iterator type for the Kinesis source. (`TRIM_HORIZON`, `LATEST`, `AT_TIMESTAMP`)
        /// </summary>
        [Input("iteratorType", required: true)]
        public Input<string> IteratorType { get; set; } = null!;

        /// <summary>
        /// The AWS region of the Kinesis stream.
        /// </summary>
        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        /// <summary>
        /// The name of the Kinesis stream.
        /// </summary>
        [Input("streamName", required: true)]
        public Input<string> StreamName { get; set; } = null!;

        /// <summary>
        /// The timestamp for the Kinesis source. Use with `AT_TIMESTAMP` iterator type. (format `2021-01-01T00:00`)
        /// </summary>
        [Input("timestamp")]
        public Input<string>? Timestamp { get; set; }

        /// <summary>
        /// Whether to use enhanced fan-out consumer.
        /// </summary>
        [Input("useEnhancedFanOut")]
        public Input<bool>? UseEnhancedFanOut { get; set; }

        public ClickpipeSourceKinesisGetArgs()
        {
        }
        public static new ClickpipeSourceKinesisGetArgs Empty => new ClickpipeSourceKinesisGetArgs();
    }
}
