// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Inputs
{

    public sealed class ClickpipeSourceBigquerySettingsGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Allow nullable columns in the destination table.
        /// </summary>
        [Input("allowNullableColumns")]
        public Input<bool>? AllowNullableColumns { get; set; }

        /// <summary>
        /// Number of parallel workers during initial load.
        /// </summary>
        [Input("initialLoadParallelism")]
        public Input<int>? InitialLoadParallelism { get; set; }

        /// <summary>
        /// Replication mode for the BigQuery pipe. (`Snapshot`)
        /// </summary>
        [Input("replicationMode", required: true)]
        public Input<string> ReplicationMode { get; set; } = null!;

        /// <summary>
        /// Number of rows to snapshot per partition.
        /// </summary>
        [Input("snapshotNumRowsPerPartition")]
        public Input<int>? SnapshotNumRowsPerPartition { get; set; }

        /// <summary>
        /// Number of parallel tables to snapshot.
        /// </summary>
        [Input("snapshotNumberOfParallelTables")]
        public Input<int>? SnapshotNumberOfParallelTables { get; set; }

        public ClickpipeSourceBigquerySettingsGetArgs()
        {
        }
        public static new ClickpipeSourceBigquerySettingsGetArgs Empty => new ClickpipeSourceBigquerySettingsGetArgs();
    }
}
