// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Inputs
{

    public sealed class ClickpipeDestinationTableDefinitionGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The engine of the ClickHouse table.
        /// </summary>
        [Input("engine", required: true)]
        public Input<Inputs.ClickpipeDestinationTableDefinitionEngineGetArgs> Engine { get; set; } = null!;

        /// <summary>
        /// The column to partition the table by.
        /// </summary>
        [Input("partitionBy")]
        public Input<string>? PartitionBy { get; set; }

        /// <summary>
        /// The primary key of the table.
        /// </summary>
        [Input("primaryKey")]
        public Input<string>? PrimaryKey { get; set; }

        [Input("sortingKeys")]
        private InputList<string>? _sortingKeys;

        /// <summary>
        /// The list of columns for the sorting key.
        /// </summary>
        public InputList<string> SortingKeys
        {
            get => _sortingKeys ?? (_sortingKeys = new InputList<string>());
            set => _sortingKeys = value;
        }

        public ClickpipeDestinationTableDefinitionGetArgs()
        {
        }
        public static new ClickpipeDestinationTableDefinitionGetArgs Empty => new ClickpipeDestinationTableDefinitionGetArgs();
    }
}
