// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Inputs
{

    public sealed class ClickpipeSourceKafkaSchemaRegistryGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The authentication method for the Schema Registry. Only supported is `PLAIN`.
        /// </summary>
        [Input("authentication", required: true)]
        public Input<string> Authentication { get; set; } = null!;

        [Input("credentials", required: true)]
        private Input<Inputs.ClickpipeSourceKafkaSchemaRegistryCredentialsGetArgs>? _credentials;

        /// <summary>
        /// The credentials for the Schema Registry.
        /// </summary>
        public Input<Inputs.ClickpipeSourceKafkaSchemaRegistryCredentialsGetArgs>? Credentials
        {
            get => _credentials;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _credentials = Output.Tuple<Input<Inputs.ClickpipeSourceKafkaSchemaRegistryCredentialsGetArgs>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The URL of the schema registry.
        /// </summary>
        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public ClickpipeSourceKafkaSchemaRegistryGetArgs()
        {
        }
        public static new ClickpipeSourceKafkaSchemaRegistryGetArgs Empty => new ClickpipeSourceKafkaSchemaRegistryGetArgs();
    }
}
