// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Inputs
{

    public sealed class ClickpipeSourcePostgresCredentialsArgs : global::Pulumi.ResourceArgs
    {
        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// The password for the Postgres instance. Use `PasswordWo` instead to keep the value out of state.
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("passwordWo")]
        private Input<string>? _passwordWo;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Write-only password for the Postgres instance. Not persisted to state. Pair with `PasswordWoVersion` to trigger updates.
        /// </summary>
        public Input<string>? PasswordWo
        {
            get => _passwordWo;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _passwordWo = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Version trigger for `PasswordWo`. Increment to push a new password to the API.
        /// </summary>
        [Input("passwordWoVersion")]
        public Input<int>? PasswordWoVersion { get; set; }

        [Input("username", required: true)]
        private Input<string>? _username;

        /// <summary>
        /// The username for the Postgres instance.
        /// </summary>
        public Input<string>? Username
        {
            get => _username;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _username = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public ClickpipeSourcePostgresCredentialsArgs()
        {
        }
        public static new ClickpipeSourcePostgresCredentialsArgs Empty => new ClickpipeSourcePostgresCredentialsArgs();
    }
}
