// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Clickhouse.Inputs
{

    public sealed class ServiceEndpointsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("https")]
        public Input<Inputs.ServiceEndpointsHttpsGetArgs>? Https { get; set; }

        [Input("mysql")]
        public Input<Inputs.ServiceEndpointsMysqlGetArgs>? Mysql { get; set; }

        [Input("nativesecure")]
        public Input<Inputs.ServiceEndpointsNativesecureGetArgs>? Nativesecure { get; set; }

        public ServiceEndpointsGetArgs()
        {
        }
        public static new ServiceEndpointsGetArgs Empty => new ServiceEndpointsGetArgs();
    }
}
