// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * You can use the *clickhouse_clickpipe* resource to create and manage ClickPipes data ingestion pipelines in ClickHouse Cloud.
 *
 * Supported source types: Kafka (Confluent, MSK, Azure Event Hubs, Redpanda, WarpStream), Object Storage (S3, GCS, Azure Blob), Kinesis, Postgres CDC, MySQL CDC, BigQuery, and MongoDB CDC.
 *
 * Known limitations:
 *
 * - ClickPipe does not support table updates for managed tables. If you need to update the table schema, you will have to do that externally.
 * - Changing the source type of an existing ClickPipe will force replacement (destroy and recreate).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as clickhouse from "@pulumiverse/clickhouse";
 *
 * const kafkaClickpipe = new clickhouse.Clickpipe("kafka_clickpipe", {
 *     name: "My Kafka ClickPipe",
 *     serviceId: "e9465b4b-f7e5-4937-8e21-8d508b02843d",
 *     scaling: {
 *         replicas: 2,
 *         replicaCpuMillicores: 250,
 *         replicaMemoryGb: 1,
 *     },
 *     source: {
 *         kafka: {
 *             type: "confluent",
 *             format: "JSONEachRow",
 *             brokers: "my-kafka-broker:9092",
 *             topics: "my_topic",
 *             consumerGroup: "clickpipe-test",
 *             credentials: {
 *                 username: "user",
 *                 password: "***",
 *             },
 *         },
 *     },
 *     destination: {
 *         table: "my_table",
 *         managedTable: true,
 *         tableDefinition: {
 *             engine: {
 *                 type: "MergeTree",
 *             },
 *         },
 *         columns: [
 *             {
 *                 name: "my_field1",
 *                 type: "String",
 *             },
 *             {
 *                 name: "my_field2",
 *                 type: "UInt64",
 *             },
 *         ],
 *     },
 *     fieldMappings: [{
 *         sourceField: "my_field",
 *         destinationField: "my_field1",
 *     }],
 * });
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * ClickPipes can be imported by specifying both service ID and clickpipe ID.
 *
 * ```sh
 * $ pulumi import clickhouse:index/clickpipe:Clickpipe example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
 * ```
 */
export class Clickpipe extends pulumi.CustomResource {
    /**
     * Get an existing Clickpipe resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ClickpipeState, opts?: pulumi.CustomResourceOptions): Clickpipe {
        return new Clickpipe(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'clickhouse:index/clickpipe:Clickpipe';

    /**
     * Returns true if the given object is an instance of Clickpipe.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Clickpipe {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Clickpipe.__pulumiType;
    }

    /**
     * The destination for the ClickPipe.
     */
    declare public readonly destination: pulumi.Output<outputs.ClickpipeDestination>;
    /**
     * Field mapping between source and destination table.
     */
    declare public readonly fieldMappings: pulumi.Output<outputs.ClickpipeFieldMapping[] | undefined>;
    /**
     * The name of the ClickPipe.
     */
    declare public readonly name: pulumi.Output<string>;
    declare public readonly scaling: pulumi.Output<outputs.ClickpipeScaling | undefined>;
    /**
     * The ID of the service to which the ClickPipe belongs.
     */
    declare public readonly serviceId: pulumi.Output<string>;
    /**
     * Advanced configuration options for the ClickPipe. These settings are specific to each pipe. For the complete list of available options, see the OpenAPI documentation at https://clickhouse.com/docs/cloud/manage/api/swagger (search for the ClickPipes settings endpoint).
     */
    declare public readonly settings: pulumi.Output<any | undefined>;
    /**
     * The data source for the ClickPipe. At least one source configuration must be provided.
     */
    declare public readonly source: pulumi.Output<outputs.ClickpipeSource>;
    /**
     * The current state of the ClickPipe. This is a read-only field that reports the actual state from ClickHouse Cloud. Possible values include `Running`, `Stopped`, `Paused`, `Provisioning`, `Failed`, `InternalError`, etc.
     */
    declare public /*out*/ readonly state: pulumi.Output<string>;
    /**
     * Whether the ClickPipe should be stopped. Default is `false` (ClickPipe will be running). Cannot be set to `true` on creation — the ClickPipe must be created in a running state and then stopped via a subsequent apply.
     */
    declare public readonly stopped: pulumi.Output<boolean>;
    /**
     * Set to `true` to trigger a resync operation. Only applicable for Postgres pipes. Automatically resets to `false` after the resync is triggered. **Note:** This will always show a diff in `pulumi preview` after setting to `true` since it resets to `false` in state.
     */
    declare public readonly triggerResync: pulumi.Output<boolean>;

    /**
     * Create a Clickpipe resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ClickpipeArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ClickpipeArgs | ClickpipeState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ClickpipeState | undefined;
            resourceInputs["destination"] = state?.destination;
            resourceInputs["fieldMappings"] = state?.fieldMappings;
            resourceInputs["name"] = state?.name;
            resourceInputs["scaling"] = state?.scaling;
            resourceInputs["serviceId"] = state?.serviceId;
            resourceInputs["settings"] = state?.settings;
            resourceInputs["source"] = state?.source;
            resourceInputs["state"] = state?.state;
            resourceInputs["stopped"] = state?.stopped;
            resourceInputs["triggerResync"] = state?.triggerResync;
        } else {
            const args = argsOrState as ClickpipeArgs | undefined;
            if (args?.destination === undefined && !opts.urn) {
                throw new Error("Missing required property 'destination'");
            }
            if (args?.serviceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceId'");
            }
            if (args?.source === undefined && !opts.urn) {
                throw new Error("Missing required property 'source'");
            }
            resourceInputs["destination"] = args?.destination;
            resourceInputs["fieldMappings"] = args?.fieldMappings;
            resourceInputs["name"] = args?.name;
            resourceInputs["scaling"] = args?.scaling;
            resourceInputs["serviceId"] = args?.serviceId;
            resourceInputs["settings"] = args?.settings;
            resourceInputs["source"] = args?.source;
            resourceInputs["stopped"] = args?.stopped;
            resourceInputs["triggerResync"] = args?.triggerResync;
            resourceInputs["state"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Clickpipe.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Clickpipe resources.
 */
export interface ClickpipeState {
    /**
     * The destination for the ClickPipe.
     */
    destination?: pulumi.Input<inputs.ClickpipeDestination | undefined>;
    /**
     * Field mapping between source and destination table.
     */
    fieldMappings?: pulumi.Input<pulumi.Input<inputs.ClickpipeFieldMapping>[] | undefined>;
    /**
     * The name of the ClickPipe.
     */
    name?: pulumi.Input<string | undefined>;
    scaling?: pulumi.Input<inputs.ClickpipeScaling | undefined>;
    /**
     * The ID of the service to which the ClickPipe belongs.
     */
    serviceId?: pulumi.Input<string | undefined>;
    /**
     * Advanced configuration options for the ClickPipe. These settings are specific to each pipe. For the complete list of available options, see the OpenAPI documentation at https://clickhouse.com/docs/cloud/manage/api/swagger (search for the ClickPipes settings endpoint).
     */
    settings?: any | undefined;
    /**
     * The data source for the ClickPipe. At least one source configuration must be provided.
     */
    source?: pulumi.Input<inputs.ClickpipeSource | undefined>;
    /**
     * The current state of the ClickPipe. This is a read-only field that reports the actual state from ClickHouse Cloud. Possible values include `Running`, `Stopped`, `Paused`, `Provisioning`, `Failed`, `InternalError`, etc.
     */
    state?: pulumi.Input<string | undefined>;
    /**
     * Whether the ClickPipe should be stopped. Default is `false` (ClickPipe will be running). Cannot be set to `true` on creation — the ClickPipe must be created in a running state and then stopped via a subsequent apply.
     */
    stopped?: pulumi.Input<boolean | undefined>;
    /**
     * Set to `true` to trigger a resync operation. Only applicable for Postgres pipes. Automatically resets to `false` after the resync is triggered. **Note:** This will always show a diff in `pulumi preview` after setting to `true` since it resets to `false` in state.
     */
    triggerResync?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a Clickpipe resource.
 */
export interface ClickpipeArgs {
    /**
     * The destination for the ClickPipe.
     */
    destination: pulumi.Input<inputs.ClickpipeDestination>;
    /**
     * Field mapping between source and destination table.
     */
    fieldMappings?: pulumi.Input<pulumi.Input<inputs.ClickpipeFieldMapping>[] | undefined>;
    /**
     * The name of the ClickPipe.
     */
    name?: pulumi.Input<string | undefined>;
    scaling?: pulumi.Input<inputs.ClickpipeScaling | undefined>;
    /**
     * The ID of the service to which the ClickPipe belongs.
     */
    serviceId: pulumi.Input<string>;
    /**
     * Advanced configuration options for the ClickPipe. These settings are specific to each pipe. For the complete list of available options, see the OpenAPI documentation at https://clickhouse.com/docs/cloud/manage/api/swagger (search for the ClickPipes settings endpoint).
     */
    settings?: any | undefined;
    /**
     * The data source for the ClickPipe. At least one source configuration must be provided.
     */
    source: pulumi.Input<inputs.ClickpipeSource>;
    /**
     * Whether the ClickPipe should be stopped. Default is `false` (ClickPipe will be running). Cannot be set to `true` on creation — the ClickPipe must be created in a running state and then stopped via a subsequent apply.
     */
    stopped?: pulumi.Input<boolean | undefined>;
    /**
     * Set to `true` to trigger a resync operation. Only applicable for Postgres pipes. Automatically resets to `false` after the resync is triggered. **Note:** This will always show a diff in `pulumi preview` after setting to `true` since it resets to `false` in state.
     */
    triggerResync?: pulumi.Input<boolean | undefined>;
}
