// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Use this data source to look up a single RBAC role by ID or name. Exactly one of `id` or `name` must be set.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as clickhouse from "@pulumiverse/clickhouse";
 *
 * // Look up a system role by name
 * const admin = clickhouse.getRole({
 *     name: "Admin",
 * });
 * // Look up a custom role by ID
 * const custom = clickhouse.getRole({
 *     id: "47f0b035-d6ca-4600-8c69-9955551857e5",
 * });
 * ```
 */
export function getRole(args?: GetRoleArgs, opts?: pulumi.InvokeOptions): Promise<GetRoleResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("clickhouse:index/getRole:getRole", {
        "id": args.id,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getRole.
 */
export interface GetRoleArgs {
    /**
     * Unique identifier of the role. Exactly one of id or name must be set.
     */
    id?: string;
    /**
     * Name of the role to look up. Exactly one of id or name must be set.
     */
    name?: string;
}

/**
 * A collection of values returned by getRole.
 */
export interface GetRoleResult {
    /**
     * List of actors assigned to this role.
     */
    readonly actors: string[];
    /**
     * Timestamp when the role was created.
     */
    readonly createdAt: string;
    /**
     * Unique identifier of the role. Exactly one of id or name must be set.
     */
    readonly id: string;
    /**
     * Name of the role to look up. Exactly one of id or name must be set.
     */
    readonly name: string;
    /**
     * Owner ID of this role.
     */
    readonly ownerId: string;
    /**
     * List of policies attached to this role.
     */
    readonly policies: outputs.GetRolePolicy[];
    /**
     * Tenant ID that owns this role.
     */
    readonly tenantId: string;
    /**
     * Type of the role: 'system' or 'custom'.
     */
    readonly type: string;
    /**
     * Timestamp when the role was last updated.
     */
    readonly updatedAt: string;
}
/**
 * Use this data source to look up a single RBAC role by ID or name. Exactly one of `id` or `name` must be set.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as clickhouse from "@pulumiverse/clickhouse";
 *
 * // Look up a system role by name
 * const admin = clickhouse.getRole({
 *     name: "Admin",
 * });
 * // Look up a custom role by ID
 * const custom = clickhouse.getRole({
 *     id: "47f0b035-d6ca-4600-8c69-9955551857e5",
 * });
 * ```
 */
export function getRoleOutput(args?: GetRoleOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRoleResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("clickhouse:index/getRole:getRole", {
        "id": args.id,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getRole.
 */
export interface GetRoleOutputArgs {
    /**
     * Unique identifier of the role. Exactly one of id or name must be set.
     */
    id?: pulumi.Input<string | undefined>;
    /**
     * Name of the role to look up. Exactly one of id or name must be set.
     */
    name?: pulumi.Input<string | undefined>;
}
