// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * You can use the *clickhouse_service_scheduled_scaling* resource to manage time-based scaling rules for a ClickHouse Cloud service.
 *
 * A schedule is a set of recurring weekly windows. The server rejects any pair of entries that overlap in time, so at most one window is active at any moment. While a window is active the service uses the replica count, memory bounds, and idle-scaling settings declared on that entry; otherwise the service falls back to its base auto-scaling configuration.
 *
 * > **Note:** This resource is in alpha. Scheduled scaling must be enabled for your organization (`canUseScheduledAutoscaling`). Reach out to ClickHouse support if the API returns `403 FORBIDDEN`. The server currently requires `minReplicas == maxReplicas` per entry, and a maximum of 10 entries per schedule.
 *
 * ## Hour ranges
 *
 * Hour ranges are asymmetric:
 *
 * - `startHourUtc` accepts `0`–`23`.
 * - `endHourUtc` accepts `1`–`24`.
 * - `startHourUtc` and `endHourUtc` must differ.
 * - Set `startHourUtc = 0` and `endHourUtc = 24` for a 24-hour window.
 * - Set `endHourUtc < startHourUtc` to wrap overnight (e.g. `22` to `6` covers 22:00–06:00 next day).
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as clickhouse from "@pulumiverse/clickhouse";
 *
 * const example = new clickhouse.ServiceScheduledScaling("example", {
 *     serviceId: exampleClickhouseService.id,
 *     entries: [
 *         {
 *             name: "Business hours",
 *             weekdays: [
 *                 1,
 *                 2,
 *                 3,
 *                 4,
 *                 5,
 *             ],
 *             startHourUtc: 8,
 *             endHourUtc: 18,
 *             minReplicas: 3,
 *             maxReplicas: 3,
 *             idleScaling: false,
 *         },
 *         {
 *             name: "Overnight",
 *             weekdays: [
 *                 0,
 *                 1,
 *                 2,
 *                 3,
 *                 4,
 *                 5,
 *                 6,
 *             ],
 *             startHourUtc: 22,
 *             endHourUtc: 6,
 *             minReplicas: 1,
 *             maxReplicas: 1,
 *             idleScaling: true,
 *             idleTimeoutMinutes: 5,
 *         },
 *     ],
 * });
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * !/bin/bash
 * Scheduled scaling can be imported by specifying the service ID.
 *
 * ```sh
 * $ pulumi import clickhouse:index/serviceScheduledScaling:ServiceScheduledScaling example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
 * ```
 */
export class ServiceScheduledScaling extends pulumi.CustomResource {
    /**
     * Get an existing ServiceScheduledScaling resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ServiceScheduledScalingState, opts?: pulumi.CustomResourceOptions): ServiceScheduledScaling {
        return new ServiceScheduledScaling(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'clickhouse:index/serviceScheduledScaling:ServiceScheduledScaling';

    /**
     * Returns true if the given object is an instance of ServiceScheduledScaling.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ServiceScheduledScaling {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ServiceScheduledScaling.__pulumiType;
    }

    /**
     * Fallback configuration applied when no entry is currently active. Server-managed.
     */
    declare public /*out*/ readonly baseConfig: pulumi.Output<outputs.ServiceScheduledScalingBaseConfig>;
    /**
     * Recurring scaling windows. The server rejects any pair of entries that overlap in time, so at most one window is active at any moment; otherwise baseConfig applies.
     */
    declare public readonly entries: pulumi.Output<outputs.ServiceScheduledScalingEntry[]>;
    /**
     * ClickHouse Cloud service ID this schedule applies to.
     */
    declare public readonly serviceId: pulumi.Output<string>;

    /**
     * Create a ServiceScheduledScaling resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServiceScheduledScalingArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ServiceScheduledScalingArgs | ServiceScheduledScalingState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ServiceScheduledScalingState | undefined;
            resourceInputs["baseConfig"] = state?.baseConfig;
            resourceInputs["entries"] = state?.entries;
            resourceInputs["serviceId"] = state?.serviceId;
        } else {
            const args = argsOrState as ServiceScheduledScalingArgs | undefined;
            if (args?.entries === undefined && !opts.urn) {
                throw new Error("Missing required property 'entries'");
            }
            if (args?.serviceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceId'");
            }
            resourceInputs["entries"] = args?.entries;
            resourceInputs["serviceId"] = args?.serviceId;
            resourceInputs["baseConfig"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ServiceScheduledScaling.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ServiceScheduledScaling resources.
 */
export interface ServiceScheduledScalingState {
    /**
     * Fallback configuration applied when no entry is currently active. Server-managed.
     */
    baseConfig?: pulumi.Input<inputs.ServiceScheduledScalingBaseConfig | undefined>;
    /**
     * Recurring scaling windows. The server rejects any pair of entries that overlap in time, so at most one window is active at any moment; otherwise baseConfig applies.
     */
    entries?: pulumi.Input<pulumi.Input<inputs.ServiceScheduledScalingEntry>[] | undefined>;
    /**
     * ClickHouse Cloud service ID this schedule applies to.
     */
    serviceId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ServiceScheduledScaling resource.
 */
export interface ServiceScheduledScalingArgs {
    /**
     * Recurring scaling windows. The server rejects any pair of entries that overlap in time, so at most one window is active at any moment; otherwise baseConfig applies.
     */
    entries: pulumi.Input<pulumi.Input<inputs.ServiceScheduledScalingEntry>[]>;
    /**
     * ClickHouse Cloud service ID this schedule applies to.
     */
    serviceId: pulumi.Input<string>;
}
